### PR TITLE
Require accepting Terms of Service and Privacy Policy when registering

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Frontend part of https://github.com/enso-org/cloud-v2/issues/1427
  - Show ToS immediately, before login screen
  - Add entries to devtools to be able to clear ToS

### Important Notes
None

### Testing Instructions
- Please test that hash updates work fine. This can be tested by deleting the Local Storage key for *one* of the agreements (either ToS or privacy policy. Testing deleting both keys is optional.), and then (optionally?) refreshing.
- It may be useful to reset the locally saved settings, either by manually deleting the `enso` key in `localStorage` (through either browser devtools or by using JS (`delete localStorage.enso`), or by using the new Devtools entries to delete individual keys.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
- ToS should be moved to registration screen (registering should be disabled until accepted)
- Privacy policy should be added as well. Marking as draft because privacy policy is not yet ready

**Comment by somebody1234** [comment]
pinging @MrFlashAccount for review

**Comment by somebody1234** [comment]
one thing to note: there is a lot of duplication between the Agreements modal and the registration form (like, the entire thing is duplicated...)
it's *theoretically* possible to make it type-safe but it may be tricky on the types side so i'm hesitant to refactor it out to its own component
(the main issue is that in the registration page it should not be a form but rather a fieldset within a form)

more importantly, it'd be a lot *more* complicated if the fields could have arbitrary keys - although not impossible...

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
QA ✅ lgtm

**Pull request merged**
