### PR TITLE
Drag and drop for labels

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/721
  - Drag-n-drop for adding labels to an asset
    - Adds to a single asset when hovering over an asset that is not selected
    - Adds to all selected assets when hovering over an asset that is selected

### Important Notes
- The backend endpoint for associating labels with assets is currently broken - specifically, it errors when the new list of assets is empty.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Is possible to implement taking off the labels as well? 

If you drag a label on asset it should be visually removed. If the labels was between other labels the remaning on the right should scroll to the left. 

Otherwise if you drag row any other place it should stay as move asset around

**Comment by somebody1234** [comment]
@PabloBuchu do you mean dragging to rearrange (or delete, depending on where it's dragged) labels? otherwise clicking already removes it, so I'm not sure it makes sense to allow dragging as well

**Comment by somebody1234** [comment]
ohhh, you mean drag should remove an asset if it's already present. yeah, that's doable, I'll try to do it soon. one question though - what if some selected assets, but not all, have the label? should it toggle the label for each of them? maybe add or remove the label from all of them based on whether more than half already have the label

**Comment by somebody1234** [comment]
> If you drag a label on asset it should be visually removed

after some thought, i'm not sure this is the best option - it'll look like the drag is doing nothing (although the user will generally be able to see the difference when it initially gets visually removed). instead i think it should show as faded out (probably with a red border to indicate it is being removed, rather than added)

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
