### PR TITLE
New context menu

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/560
- New context menu
- Global keyboard shortcut handler
- Moves the existing "escape" keybindings (close modal, cancel editing names) to global keybind handlers

### Important Notes
- The "Upload To Cloud" action is not present in the Figma design. As such:
  - Its current icon is an edit of the "cloud_from" icon, with the arrow upside down
  - It does not have a corresponding keyboard shortcut

### Screencast

[screen-recorder-thu-aug-10-2023-18-26-45.webm](https://github.com/enso-org/enso/assets/4046547/0cd647db-0697-4a4b-b088-e8d07bdf71b6)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. Context menu is clickable only over table items. The problem is when I have only one item I tend to right click somewhere below. We should expand the area. Of course everything from "New" actions lands in root directory
2. We should add highlight on currently hovered option  
3.  I have only `move to trash` on empty table or empty directory. thus cant create asset in subdirectory or empty table

Screenshot 2023-08-02 at 11 50 12


4. `New <project|directory|file` icons are buggy but I believe it should be fixed in https://github.com/enso-org/enso/pull/7430. Basically I need to click twice to send a request to the API or have something in the table already.

5. Bug probably overlooked from new asset table:
https://github.com/enso-org/enso/assets/2855109/3aa81271-95f9-4d57-b78a-7a3730305719


6. Local should not have `New folder` / `New Data Connector` / `Upload Files` options. They are throwing errors right now

7. Upload file does nothing after selecting an image


8. If I dont select a directory shortcuts doesnt work. `New asset` actions should add stuff to root directory for now

**Comment by somebody1234** [comment]
addressed 2 and 6 because i'm doing other minor style changes, will address the rest some other time

**Comment by somebody1234** [comment]
1: will address very soon
3: should be fixed now
4: indeed seems to be fixed, so i will ignore this one unless it becomes a problem again
5: ah, i think i know what causes this:
  - new assets use a placeholder id since we don't know the actual id until the backend request completes
  - the list of children are inserted after the directory with `id = parentId`. specifically, `parentId` is *not* the placeholder id

but also i think it's out of scope for this issue; it's probably better to address it in another PR

7. should be fixed now
8. i don't think i encountered this issue (but i don't doubt this was an issue), *but* i don't seem to be able to repro it as of current commit, so i'm assuming it's been fixed

**Comment by somebody1234** [comment]
after addressing (1) i think i'll:
- implement some of the UI changes - mainly the assets table appearance and the new "share" button on the top right
- begin implementing the welcome screen
- try to get back to this to test it, before the end of today (or maybe early tomorrow)


on a tangent:
- the cloud/local backend switcher needs the `button` to be one level higher, otherwise the padding doesn't trigger the button. will fix in another PR soon.

**Comment by somebody1234** [comment]
:warning: "Upload To Cloud" does not update the remote backend's assets list. This is intentional as:
- it requires complex logic to somehow cache these assets
- this should be very rarely encountered by users, and I don't think it's severe enough that it makes the dashboard unusable

**Comment by somebody1234** [comment]
issues related to inserting items:
- [x] "new folder" etc in a directory's context menu does not add child to a directory (fixed by new commit)
- [x] newly inserted item is inserted at the end of the entire assets list if the directory is not currently open
- [x] newly inserted item has wrong indentation
- [x] newly inserted item is not in the right place when inserted while directory contents are loading
- [x] inserting item into empty folder does not remove the "this folder is empty" placeholder row
- [ ] deleting all children from a folder does not re-add the "this folder is empty" placeholder row
- [ ] new asset has the wrong number (always `_1`) when added when the parent folder is closed
- [x] fixes do not work for newly inserted directories, because the table id (the old id) does not match the asset id (the up-to-date id)
  - [ ] children of a newly inserted folder still appear at the end
- [x] inserting item does not expand parent directory
- [x] new asset has wrong number (scans folders in the parent directory) when added when the parent folder is closed (?!)
- [x] children of a directory load in when opening a directory, then closing it before the children load in
- [x] children of a directory load in when opening a directory, then closing and reopening it before the children load in
- [ ] (new) new asset always has suffix `_1` when added to root directory

other issues:
- [x] right clicking an item that is not selected, should select an item and deselect the old selection

**Comment by somebody1234** [comment]
some items intentionally not implemented. feel free to create new issues:
> deleting all children from a folder does not re-add the "this folder is empty" placeholder row

this requires tracking whether each child of a directory is visible. it might not be particularly difficult, but would be quite a big change, so it should probably be in another PR

> new asset has the wrong number (always `_1`) when added when the parent folder is closed

it's possible to wait until the parent folder is open instead, but this means increased latency. the logic, while it wouldn't be particularly complex, is not trivial either

another fix incoming shortly (edit: more fixes added)

**Comment by PabloBuchu** [comment]
Inserting into subdirectory still doesnt seem to work. Now it also lose the refrenece to opened directory (new one is added in place of opened and breaks closing)

https://github.com/enso-org/enso/assets/2855109/33906b4f-55ab-4a57-9915-0879907be149

**Comment by PabloBuchu** [comment]
1. cmd + u - upload file shortcut doesnt work
2.  cmd + enter - share modal is in weird place
Screenshot 2023-08-10 at 11 39 05
3. Right clicking on cloud project I see `upload to cloud` which actually tries to upload to cloud

**Comment by somebody1234** [comment]
ah right, so that's what the ref to the row was for (share modal location).
i guess it'd still look bad, so i'll move it to the center instead

**Comment by somebody1234** [comment]
cmd + u not working: nice catch, thanks. yeah it's because of the new refactor... i'm not sure what's the best way to fix that unfortunately, since file dialogs need a file input to work... i guess i'll define a hidden file input at the top level of the table

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
few small things I just spot:
- cmd + u without selected directory should upload to root
- move to trash shortcut doesnt work. It should respond to using backspace

**Comment by somebody1234** [comment]
noted, will implement + test + push

**Comment by somebody1234** [comment]
while i'm at it, the others should probably add to root too (new folder, new project). depending on backend of course

**Pull request merged**
