### PR TITLE
Support also COMMAND_RUN and COMMAND_DEBUG actions

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Turns out that #8923 isn't enough to support debugging of `Vector_Spec.enso` when root of Enso repository is opened as a folder/workspace. To allow debugging of `Vector_Spec.enso` two changes are needed. One is provided in this PR, the other one will be integrated as https://github.com/apache/netbeans/pull/7105

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      style guides. 
- All code has been tested:
  - [x] Manually tested debugging of `Vector_Spec`

### CODE REVIEW

**Review by radeusgd — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
Cannot merge right now. Waiting for https://github.com/apache/netbeans/pull/7059 to get in and be released.

**Review by Akirathan — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
Updating the upstream PR again: https://github.com/apache/netbeans/pull/7059#issuecomment-1959748773 and discussing next steps.

**Comment by JaroslavTulach** [comment]
https://github.com/apache/netbeans/pull/7105 has been merged. Now we are waiting for a newer release of [Apache NetBeans Extension](https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java) than `21.0.0`. If the _release gods_ are with us, it should be out in two months...

**Comment by JaroslavTulach** [comment]
Version 21.9.9 is out since 13. 4. 2024, let's verify if it fixes the problem! Download [VSCode Extension 1.33.440](https://github.com/enso-org/enso/actions/runs/8723304607?pr=9041) and test it!

Open `Number_Spec.enso` (while having root of Enso repository opened as a workspace - without the workspace the debugging was already working even  before). Put a breakpoint into the file and start debugging. You'll be asked for a location of `bin/enso` executable - provide one:

bin/enso

press Enter and then the execution starts. After a while the breakpoint is hit:

breakpoint hit

Great, **let's release**  [VSCode Extension 1.33.440](https://github.com/enso-org/enso/actions/runs/8723304607?pr=9041)!

**Comment by JaroslavTulach** [comment]
Version [1.33.440](https://marketplace.visualstudio.com/items?itemName=Enso.enso4vscode) has been uploaded to marketplace. Thank you @ola-lis!

**Pull request merged**
