### PR TITLE
Fix dashboard regressions

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/566
- Projects are now added to the start of the list (as expected) on local backend
- Opening a project should now close all other projects
- Fixes spinners for templates

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. So creating a local project and immediately switching to cloud will make the project vanish. Error message is shown. Also creating another one prompts error in console about unable to closing not running project.


https://github.com/enso-org/enso/assets/2855109/b1e41f46-1cf6-4272-be87-222a844fa942


2. I didn't say we should remove the spinners :) Can we fix them until we have the welcome screen?

**Comment by somebody1234** [comment]
hmm... seems like the spinner isn't going away

**Comment by somebody1234** [comment]
... actually, upon further testing, it seems like that only happens when the backend is switched before the project finishes opening. i guess the spinner should be cancelled when the backend is changed then

**Comment by PabloBuchu** [comment]
Looks like it is worse now? It tries to close every project on the list. @somebody1234 should we rollback the commit with new project table?

Spinner is also still spinning after opening project

https://github.com/enso-org/enso/assets/2855109/7165dd68-834f-484a-bb92-68af215d1e0c

**Comment by somebody1234** [comment]
> ... actually, upon further testing, it seems like that only happens when the backend is switched before the project finishes opening. i guess the spinner should be cancelled when the backend is changed then

unfortunately this issue seems to be really difficult to fix

**Comment by PabloBuchu** [comment]
If you waint for open to open automatically the spinner is fine. 

The spinner wont stop if you change the local / cloud after the set project open request success (but before ready to open)
https://github.com/enso-org/enso/assets/2855109/8a1f41e4-90ef-48b3-85bd-aaba2439459f

2nd issue is if you change local to cloud before set project open request success 

https://github.com/enso-org/enso/assets/2855109/fb7958d5-c9c4-4f96-b33c-2e478b31dacd


We can fix the 1st here in this PR and 2nd in separate if its non trivial @somebody1234 wdyt?

**Comment by somebody1234** [comment]
@PabloBuchu yeah the second issue is definitely non-trivial. i think *ideally* we'd just not fix it maybe? since it will be replaced with the welcome screen (and immediate switching to the IDE tab), right?
basically my thoughts are:
- i *think* it's quite hard to accidentally trigger, and
- i'm not sure it's worth spending the time to fix it when (well, *if*) it will be replaced fairly soon

**Comment by somebody1234** [comment]
can definitely create an issue for it though, in case plans change re: the welcome screen

**Comment by PabloBuchu** [comment]
Yes we can skip the 2nd issue for now. But we definitely need to fix current table view:

1. When try to open already created local project and wait it will open automatically with success
https://github.com/enso-org/enso/assets/2855109/820b3933-f419-4dd7-8d4c-09e86309043c

2. When do that the same but switch to local and back it will load indefinitely making it impossible to open.
https://github.com/enso-org/enso/assets/2855109/aded55d5-22ae-4ac9-9320-b7d36d5549c3

3. When creating new project from template (local) and switching to cloud and back makes the project and template load indefinitely and after reload the project is stoped 
https://github.com/enso-org/enso/assets/2855109/ad666ece-af66-40ba-9343-1dae9a5cd122

**Comment by somebody1234** [comment]
1. i'm assuming this isn't an issue
2. will investigate
3. unfortunately this is intentional - there is no way to list the currently open project(s) in the project manager. i can open an issue requesting either a new endpoint for that, or (more preferable) for the project manager to return opening state in the "list projects" endpoint

**Comment by PabloBuchu** [comment]
Aslo "New project" button doesnt work
Screenshot 2023-07-28 at 11 20 57

**Comment by somebody1234** [comment]
both issues *should* be fixed, but now the templates spinner is broken. i'll push the changes anyway, so the fixes can be tested

**Comment by somebody1234** [comment]
or not... no idea how it was working just now

**Comment by somebody1234** [comment]
@PabloBuchu should be ready for re-testing now?

(note: it doesn't solve the difficult spinner issue, but it does solve the simpler one i mentioned above)

**Comment by somebody1234** [comment]
actually i think i've managed to fix the difficult issue too... seems like i was overthinking it

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
