### PR TITLE
Fix dispatching events to assets table

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
It seems to be a race condition, so I've fixed it by delaying clearing the list of events to be handled.

### Important Notes
Not 100% sure delaying is completely safe. It is probably a good idea to stress-test this by adding a lot of assets at once? Maybe something like uploading a lot of small text files would work.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
I guess the current list projects is somewhere not being up to date. When I remove all my projects and the create new one I have all my previous ones back

https://github.com/enso-org/enso/assets/2855109/8645fb07-0757-452e-b104-df41faa87fd6

**Comment by PabloBuchu** [comment]
Seems still buggy. Removed 2 projects add and 2 appeared... There were also some other errors while removing projects 

https://github.com/enso-org/enso/assets/2855109/ad8a8044-d755-4d3d-a62c-d9bf1c123aeb

**Comment by somebody1234** [comment]
:/ yeah the original fix didn't work correctly
re: the "cannot remove open project", it seems to be quite difficult to get that working for delete multiple, since as it's set up currently, the top level table doesn't have access to the *current* values of each item. i can try and see if there's a nice solution tho

**Comment by PabloBuchu** [comment]
When I create any new project I am getting error "Unable to open New_Project_1: Invalid params". Its related to this branch since its not occurring on develop

Screenshot 2023-08-01 at 10 42 31

**Comment by somebody1234** [comment]
oops, getting `unable to open project` error, will fix... sometime soon?

**Comment by somebody1234** [comment]
it's because it's trying to open a project using the placeholder id

**Comment by somebody1234** [comment]
as for the "cannot remove open project" error, it's probably best to just wait until they are open for now. in the future they should be moved to trash so it won't be a long term issue anyway

**Comment by somebody1234** [comment]
self-testing wip:

- :heavy_check_mark: create new project and wait for it to open:
  - :heavy_check_mark: "invalid params" does not appear
  - :heavy_check_mark: spinner doesn't skip to finishing percentage
- :heavy_check_mark: creating multiple projects, only one is opening at any given time
- :x: when opening multiple projects, the last one opens. currently no projects open.
- :warning: "cannot close project that is not open" errors are currently silently ignored. ideally they shouldn't occur in the first place
- :warning: not yet tested with cloud backend

**Comment by PabloBuchu** [comment]
Something broke on cloud projects. Removing multiple works. But when I have opened one and hit reload it tries to issue `/open` request which ends in 500 (this needs to be fixed on backend thought). Now I can't open already running project either after reload or closing and reopening Enso.

I checked develop and there everything works fine projects stays openable on Enso close / reload 

https://github.com/enso-org/enso/assets/2855109/be79e2af-528f-4ca6-bedb-d35ea88b3571

**Comment by somebody1234** [comment]
just a heads up, i'll do stuff on other PRs before investigating (and more testing) here.
the recent commits have a lot of changes to how the project action button works, so i have some guesses what might be causing that issue

**Comment by somebody1234** [comment]
so opening cloud projects is still an issue, will investigate now

**Comment by somebody1234** [comment]
tests:
- :heavy_check_mark: refreshing cloud view does not `POST /open` again, and opening cloud project still works after refresh
  - :x: switching to local backend somehow results in "invalid params"

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
some testing:
- :heavy_check_mark: no more error when switching to local backend with cloud project open
- :heavy_check_mark: cloud project is not closed when switching backend
  - this is intentional, because opening a project is relatively expensive. it's reasonable to assume a user might want to switch backends without closing the current project, even if it is for a different backend
- :heavy_check_mark: can switch to project via page switcher (switching back is currently done by the "go to dashboard" button)
- :heavy_check_mark: placeholder is visible when all projects are removed
- :heavy_check_mark: new project is added, and auto-opens, with empty directory list
- :heavy_check_mark: when rapidly creating new projects, only the newest one is auto-opened
- :heavy_check_mark: projects don't mysteriously reappear after deleting multiple projects then creating a new one

**Pull request merged**
