### PR TITLE
Add "Invite" button on top right

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Implement https://github.com/enso-org/cloud-v2/issues/884
  - Add an "Invite" button that is present when the "Share" button is not present

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
We need to polish this modal a bit:
- make the input bigger 
- 
- remove add user button
- instead after user hits `space` you change the email into bubble/tag with `x` to remove it (like here https://kopi.dev/tailwind/tags-input/ but within the input)
- if I type email which doesnt meet the format lets color it red and prevent from submitting the whole modal

<blockquote><div> Kopidev</div><div><strong><a href="undefined/tailwind/tags-input/">Tags Input - Tailwind Component</a></strong></div><div>Tag Input allows to add, remove, manage, manipulate tags with Tailwind CSS user interface.</div></blockquote>

**Comment by somebody1234** [comment]
@PabloBuchu initial implementation of the new input has been added.

**Comment by PabloBuchu** [comment]
The text area seems big but the text can be only 24 characters wide.. 

Screenshot 2024-02-12 at 12 57 29

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
Ready to merge after fixing the conflicts

**Pull request merged**
