### PR TITLE
Bump electron-builder

### PR DESCRIPTION
**Pull request by mwu-tow**
### Pull Request Description
Now that #9815 has landed, we can finally bump electron-builder to the latest release. As this brings in python3 support out-of-the-box, workaround of the runtime-bump on macOS runners can be removed.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by MrFlashAccount — APPROVED** [review]

**Review by MrFlashAccount — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@mwu-tow so whats needed to be able to build develop on mac now? I am having problems atm 

Screenshot_2024-05-09_at_11 33 11

**Comment by mwu-tow** [comment]
@PabloBuchu Having `python` installed is still required, it is that it can be `python3`, so workarounds to install outdated `python2` on newer macOS are not longer needed.

Do you have `python` in your PATH?

**Comment by PabloBuchu** [comment]
its not a missing python problem. tried with venv, python3 etc.

**Comment by PabloBuchu** [comment]
`/usr/bin/python` is hardcoded in the repo.. this alias is no longer present on mac os

**Comment by mwu-tow** [comment]
> /usr/bin/python is hardcoded in the repo.. this alias is no longer present on mac os

It is not hardcoded in the repo, at least not ours. This is transitive dependency of the `electron-builder`. If you have proper Python in the PATH, it should be picked up (as it happens on CI). The `/usr/bin/python` seems to appear as a fallback only.

**Pull request merged**
