### PR TITLE
Clear Changelog

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Cleared changelog, as last "officially" released was old, and was with old GUI.

Updated the list of gathered statistics

### Important Notes

I also removed the old changelog of libraries and engine, despite it not being rewritten in the meantime, but I assumed nobody will be interested in differences between alpha versions from 2 years ago.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by farmaazon** [comment]
I have no idea what to write in #Next release section, so if anyone proficient in writing nice documentation/marketing text may write their propositions.

**Review by JaroslavTulach — APPROVED** [review]
I thought we'll rename `CHANGELOG.md` to `CHANGELOG-2023.md` and start a new one.

**Comment by farmaazon** [comment]
> I thought we'll rename `CHANGELOG.md` to `CHANGELOG-2023.md` and start a new one.

Good idea! However, I kept only actual releases in CHANGELOG-2023.md. If anyone wants to keep something from the mile-long "Next release" section, it always waits in git history.

**Comment by JaroslavTulach** [comment]
> I kept only actual releases in CHANGELOG-2023.md. 

I see. I wasn't participating at those. Then it should be named CHANGELOG-2021 as that's the year of its latest release.

> If anyone wants to keep something from the mile-long "Next release" section, it always waits in git history.

That's the part of history I consider important - it contains my changes.

**Pull request merged**
