### PR TITLE
Update autoAccept branch to develop and add comment only on PRs

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

This PR fixes a couple of issues that were not tested in #11522 :
1. We no longer comment things out outside of PR
2. We auto accept the new screenshots on Chromatic in develop (instead of main)
3. Animations now disabled during screenshot testing
4. Another tiny improvements in CI process based on the early feedback

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]

**Comment by vitvakatu** [comment]
I advise against using meaningless descriptions for PRs. No description is better than a long (but pointless) one.

**Comment by MrFlashAccount** [comment]
> I advise against using meaningless descriptions for PRs. No description is better than a long (but pointless) one.

WDYM by "pointless" here? I mean, from my perspective the description is clear enough. Would love to see your opinion

**Comment by vitvakatu** [comment]
> WDYM by "pointless" here? I mean, from my perspective the description is clear enough. Would love to see your opinion

Sure, let’s take a look:

> This pull request includes two commits.

This is already misleading because it contains seven.

> The first commit updates the autoAccept branch from "main" to "develop". The second commit adds a condition to only comment on pull requests.

I could see it from the names of the commits as well as from 2 lines of code being changed.

> These changes ensure that the autoAccept feature is applied to the correct branch and that comments are only made on pull requests.

It is the previous sentence being rephrased.

So, in three sentences and half a hundred words, we have one misleading and one obvious statement. I would rather like to see an explanation of _Why_ the change was done. Of course, I can guess that it is a fixup for CI after recent changes, but the description does not contain this explanation.

**Comment by MrFlashAccount** [comment]
Thanks! will adjust the description based on your feedback

**Review by jdunkerley — APPROVED** [review]

**Pull request merged**
