### PR TITLE
Fix #5075: stop panning on full-screen visualisation

### LINKED ISSUE #5075: Dragging fullscreen visualisation view also moves camera in graph editor
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184345926).
<hr />

Repro steps:
1. launch fullscreen visualisation
2. drag the view with the mouse
3. exit fullscreen view

See the attached video for example

## Comments:
 (Greg Ociepka - Jan 30, 2023)
<hr />
Seems related to the navigator. Clearly GUI only issue.  (Michael Mauderer - Feb 1, 2023)
<hr />

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

Closes #5075: dragging or scrolling while a visualisation is in full screen caused the camera to move in the graph editor.

The problem was that clicking on the visualisation triggered some FRP node that indicated that the project list should be closed, which then indicated that the navigator shouldn't be disabled. However, the FRP code in the graph editor interpreted "shouldn't be disabled" as "should be enabled", ignoring the fact that there's also a full-screen visualisation, which should always disable the navigator.

https://user-images.githubusercontent.com/607786/235908932-0b579d69-5fd8-438e-a82b-02678d8e6156.mp4

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]

**Comment by MichaelMauderer** [comment]
QA: :green_circle:

**Comment by sylwiabr** [comment]
@mwu-tow @Procrat any idea why it was not merged for 17 hours? (or what is happening with the CI)

**Comment by somebody1234** [comment]
@sylwiabr i think it was partly because i committed something that broke the lint CI - it should be fixed now so adding the `CI: keep up to date` label should fix it

**Comment by somebody1234** [comment]
there are other lints that seem to be failing as well, not sure what the cause is though

**Pull request merged**
