### PR TITLE
Fix the `--ide-option` handling.

### LINKED ISSUE #6236: --ide-option does not work for ./run ide watch
### Discord username

_No response_

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

It seems all `--ide-option` arguments are silently ignored when running `./run ide watch`. 

Standalone distribution built with `./run ide build` works fine, though.

It is reproduced on the latest develop, the cause of the issue is [`e7668ebc3ae39a489149bf0d0a51e45b7ef7b427`](https://github.com/enso-org/enso/pull/6077)

### Expected behaviour

I can use `--ide-option` arguments to customize IDE options.

### How we can reproduce it?

```
./run ide watch --backend-source=release --backend-release="2023.1.1-nightly.2023.3.30" --skip-wasm-opt --ide-option -debug.dev-tools=true --ide-option -debug --ide-option -startup.project=Unnamed_27
```

It is supposed to open dev-tools and a project, but it loads the welcome screen without dev-tools.

### Screenshots or screencasts

_No response_

### Enso Version

e7668ebc3ae39a489149bf0d0a51e45b7ef7b427

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

MacOS, Linux

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by mwu-tow**
### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
weirdly enough, this was last changed by @vitvakatu:
https://github.com/enso-org/enso/blame/0f4f8a0542a246b3d83f461d4ad26f759a24d5ac/app/ide-desktop/lib/client/watch.ts#L113

maybe there's an inconsistency before OSes?

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/app/ide-desktop/lib/client/watch.ts at 0f4f8a0542a246b3d83f461d4ad26f759a24d5ac · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by mwu-tow** [comment]
@somebody1234 
I think it was always supposed to work with the `--` separator between flags to the `electron` runner and IDE flags, but there was a bug. @vitvakatu solved it by removing the `--`, but in the meantime, I fixed `--` parsing on my branch; hence when it landed, it caused the bug to reappear (this time another way around).

@vitvakatu Do you have any further insight?

**Comment by vitvakatu** [comment]
I believe you're right, @mwu-tow. Do you need QA for this PR?

**Comment by mwu-tow** [comment]
@vitvakatu 
> I believe you're right, @mwu-tow. Do you need QA for this PR?

Yes, it'd be great if anyone other than me confirmed that this works. :)

**Comment by vitvakatu** [comment]
I'll check it now

**Review by vitvakatu — APPROVED** [review]
QA passed

**Pull request merged**
