### PR TITLE
Initial Support for paywalls

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

This PR introduces:
1. Set of Paywall components: PaywallButton, PaywallDialog
2. Adds Devtools
3. Implement Paywall Configuration 

This PR partially depends on https://github.com/enso-org/enso/pull/10199

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Can't build and test
```
TRACE ide_ci::program::command: npmℹ️ <START>
TRACE ide_ci::program::command: npm⚠️ <START>
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️ > enso-gui2@0.1.0 build
 INFO ide_ci::program::command: npmℹ️ > npm --workspace enso-dashboard run compile && run-p typecheck build-only
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️ > enso-dashboard@0.1.0 compile
 INFO ide_ci::program::command: npmℹ️ > tsc
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/components/PaywallButton.tsx(43,6): error TS2375: Type '{ children: string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode>; ... 35 more ...; variant: "delete" | ... 9 more ... | undefined; }' is not assignable to type 'IntrinsicAttributes & (ButtonProps & RefAttributes<HTMLButtonElement>)' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
 INFO ide_ci::program::command: npmℹ️   Type '{ children: string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode>; ... 35 more ...; variant: "delete" | ... 9 more ... | undefined; }' is not assignable to type 'Omit<ButtonProps, "type" | "children" | "onPress">' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
 INFO ide_ci::program::command: npmℹ️     Types of property 'className' are incompatible.
 INFO ide_ci::program::command: npmℹ️       Type 'string | ((values: ButtonRenderProps & { defaultClassName: string | undefined; }) => string) | ((values: LinkRenderProps & { defaultClassName: string | undefined; }) => string)' is not assignable to type 'string | ((values: ButtonRenderProps & { defaultClassName: string | undefined; }) => string)'.
 INFO ide_ci::program::command: npmℹ️         Type '(values: LinkRenderProps & { defaultClassName: string | undefined; }) => string' is not assignable to type 'string | ((values: ButtonRenderProps & { defaultClassName: string | undefined; }) => string)'.
 INFO ide_ci::program::command: npmℹ️           Type '(values: LinkRenderProps & { defaultClassName: string | undefined; }) => string' is not assignable to type '(values: ButtonRenderProps & { defaultClassName: string | undefined; }) => string'.
 INFO ide_ci::program::command: npmℹ️             Types of parameters 'values' and 'values' are incompatible.
 INFO ide_ci::program::command: npmℹ️               Type 'ButtonRenderProps & { defaultClassName: string | undefined; }' is not assignable to type 'LinkRenderProps & { defaultClassName: string | undefined; }'.
 INFO ide_ci::program::command: npmℹ️                 Property 'isCurrent' is missing in type 'ButtonRenderProps & { defaultClassName: string | undefined; }' but required in type 'LinkRenderProps'.
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/UpgradeButton.tsx(54,33): error TS2339: Property 'getContactSalesURL' does not exist on type 'typeof import("/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/src/appUtils")'.
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/UpgradeButton.tsx(54,73): error TS2339: Property 'getUpgradeURL' does not exist on type 'typeof import("/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/src/appUtils")'.
 ```

**Comment by MrFlashAccount** [comment]
@PabloBuchu  I love typescript 😄

Fixed the compilation problem

**Comment by PabloBuchu** [comment]
@MrFlashAccount not sure what you meant but still having issues. Please ping me when this PR will be ready for QA,

```
 INFO ide_ci::program::command: npmℹ️ > enso-gui2@0.1.0 build
 INFO ide_ci::program::command: npmℹ️ > npm --workspace enso-dashboard run compile && run-p typecheck build-only
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️ > enso-dashboard@0.1.0 compile
 INFO ide_ci::program::command: npmℹ️ > tsc
 INFO ide_ci::program::command: npmℹ️
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/PaywallDialogButton.tsx(17,51): error TS2312: An interface can only extend an object type or intersection of object types with statically known members.
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/PaywallDialogButton.tsx(26,11): error TS2339: Property 'feature' does not exist on type 'PaywallDialogButtonProps'.
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/UpgradeButton.tsx(54,33): error TS2339: Property 'getContactSalesURL' does not exist on type 'typeof import("/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/src/appUtils")'.
 INFO ide_ci::program::command: npmℹ️ src/components/Paywall/UpgradeButton.tsx(54,73): error TS2339: Property 'getUpgradeURL' does not exist on type 'typeof import("/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/src/appUtils")'.
 ```

**Comment by MrFlashAccount** [comment]
@PabloBuchu I should've tested it better, my apologies! Now it should compile well.

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
