### PR TITLE
Save backend type in localStorage, and automatically open projects when ready

### LINKED ISSUE #6666: `--startup.project` option does not work with the new dashboard.
When providing `--startup.project` option, the IDE went directly to the project view, now it displays Dashboard instead. We should fix this or remove the option from the list.

The latter is less preferable, as it's convenient to me to run something like `enso-build-cli ide watch --skip-wasm-opt --ide-option --debug.dev-tools --ide-option --startup.project --ide-option Unnamed_7` so I don't have to pick the project on every electron restart.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Properly fixes #6666
- Closes [cloud-v2/#448](https://github.com/enso-org/cloud-v2/issues/448)
- Closes [cloud-v2/#449](https://github.com/enso-org/cloud-v2/issues/449)
  - Implements context menu action to open projects as well

### Important Notes
Needs a *very* thorough QA. There are quite a lot of changes to the state logic, so it'll take a little time to test them all:
- `-startup.project` + the wrong backend
- canceling project creation on local backend, and canceling auto-open when you decide to open another project (either through play button or through context menu)

### Screencast

https://github.com/enso-org/enso/assets/4046547/a7980621-bfb7-49e2-932f-5d13b4835afe

Note: This recording does show a few issues:
- The project name is not changed, which breaks all projects after the first one with error "Module 'local.Name_Of_The_First_Project.Main' not found". This seems to be an issue with the Project Manager, quick debugging says that 
  - Upon further thinking... it's because the command-line's `startup.project` overrides the one passed by the dashboard. This will be fixed in the next commit(s).
- There are issues with getting the resources check to run consistently.
- Sometimes, saving the current backend type does not work. The cause is unclear.
If anyone can reliably reproduce these problems, or can figure out the cause, that would be great. I'll see if anything can be done to simplify the state logic though (and whether the simplifications will remove the issue)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
ok re: removing `startup.project`, the code may need to be updated to work with the auth flow changes in #6668 once that is merged

**Comment by somebody1234** [comment]
note: I don't think swapping the order (URL params before explicitly passed options) is a good idea, which is why it's not being considered as a potential solution here. `startup.project` *should* be immediately removed, because it is only intended as a shortcut

**Comment by somebody1234** [comment]
The first two mentioned issues should now be fixed. Haven't been able to repro the third issue for a while though

**Comment by PabloBuchu** [comment]
First run after the build results in weird error while connecting to project manager. It's always first run the nexts are clean

Screenshot 2023-05-18 at 13 48 25

**Comment by PabloBuchu** [comment]
```
When using local backend and user clicks play icon he/she is immediately taken to workspace (no need for double click to spin and open project).
```
This isn't working

**Comment by somebody1234** [comment]
QA:

`./run ide watch`:
:heavy_check_mark: log in
:heavy_check_mark: play to immediately open
:heavy_check_mark: double click to immediately open
:heavy_check_mark: right click -> "open for editing" to immediately open
:heavy_check_mark: registration flow works - previously, :x: passwords were not required in the initial sign up screen
:heavy_check_mark: change password flow works - previously :question: ugly error from server for certain values of "old password"
:heavy_check_mark: user menu - previously:
  - :question: disabled option "your profile" looked like it was enabled
  - :question: clicking the user icon after clicking outside to unset the modal, does nothing - this is because `isUserMenuVisible` is still `true`

:heavy_check_mark: search works - now made case-insensitive
:heavy_check_mark: creating project works (local backend) - both empty, and from all templates
:heavy_check_mark: deleting project works (local backend)
:heavy_check_mark: renaming project works (local backend) - validation too
:heavy_check_mark: deleting project works (local backend)
:heavy_check_mark: creating project works (cloud backend)
  - :warning: project order is very wonky

:heavy_check_mark: renaming project works (cloud backend)
:heavy_check_mark: table looks ok - previously :x: was full-width. for some reason `width: 0` (`w-0`) is needed
:heavy_check_mark: persisting backend type works - previously :x: it was overwritten to `remote` every refresh
:heavy_check_mark: search bar looks ok - previously :question: was the default `size="20"` so it would push the help chat and user profile offscreen at around ~740px viewport width
:heavy_check_mark: templates look ok - adjusted so the tiles are a fixed size (and still 5 columns at 1280px width)
:heavy_check_mark: `document.body` scrollbar now uses the same scrollbar as visualizations - previously :question: default scrollbar
:heavy_check_mark: folder navigation + path saving both work (cloud backend)
:heavy_check_mark: shared with is still hidden on local backend
:heavy_check_mark: last modified date is still visible
:warning: many icons are still using placeholders because they did not exist on the figma design - this is definitely way out of scope, but still worth noting

:heavy_check_mark: can go back to dashboard from `-startup.project` - previously :x: broken
:heavy_check_mark: invalid `-startup.project` now displays an error - previously :x: did not exist
:heavy_check_mark: `-startup.entry` (with and without `-startup.project`, even though it does nothing)
:heavy_check_mark: `-startup.project` works when selecting `ide` entry point after passing invalid `-startup.entry`
:heavy_check_mark: `-startup.project` works with `gui watch`

(QA not 100% thorough but should be more than enough for one PR?)

logins:
:heavy_check_mark: logins work on `gui watch` (google, github, password)
:heavy_check_mark: logins work on `watch-dashboard` (google, github, password) - previously :question: redirected to `cloud.enso.org` - was intentional, however might as well take advantage of the build tooling to override it now that it exists
:heavy_check_mark: logins work on `ide watch` (google, github, password) - :warning: this logs in through the builtin browser
:question: logins work on `ide build` - cannot test as i have neither a windows nor a mac machine handy

**Comment by somebody1234** [comment]
:warning: there's an issue with the spinner starting at 75% instead of 5% after certain actions
:warning: there's also issues related to opening multiple projects at once (it tries to auto-start multiple IDE instances at once)
  - well, it's probably more related to cancelling autostart not working properly. if you click play and then click stop right after, the IDE will still launch

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
just merged and am doing a bit of testing before pushing - it turns out there's an issue with trying to delete the project before it's closed - what should we do? i think the main issue is that the spinner is currently not set up to spin on closing - which isn't a bad thing, i think it would be a little confusing

however this means that this issue doesn't really have a good solution (that i can think of, at least)

also :warning: creating a cloud project and immediately deleting it causes issues:
- the first time, it went back to the loading stage
- the second and third times, it didn't go back to the loading stage but the toast notification stayed around forever

might be fixed now but not 100% sure

**Comment by PabloBuchu** [comment]
@somebody1234 
|  it turns out there's an issue with trying to delete the project before it's closed - what should we do?

We should grey out (disable) the `Delete` option in context menu and add small tooltip on hover "can't remove running project"
Screenshot 2023-06-05 at 10 06 09

**Pull request merged**
