### PR TITLE
Add IRDumper for Scala IR

### PR DESCRIPTION
**Pull request by Akirathan**
### Pull Request Description

Debugging/inspecting/watching changes in the [Scala IR](https://github.com/enso-org/enso/blob/fe0f9046dbff0c005adfb69a5eb6e3787e7cdda9/engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java) has always been very tricky. The only way to do that, other than attaching the debugger and inspecting nested object structures, has been [IR.pretty](https://github.com/enso-org/enso/blob/fe0f9046dbff0c005adfb69a5eb6e3787e7cdda9/engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java#L91) method, that is not useful for large IRs. This PR add an [IRDumper](https://github.com/enso-org/enso/blob/a98b674f9ec109b01c7d7e3600c5e01b1c9d5ce5/engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java) utility class that dumps the `IR` into a [GraphViz](https://graphviz.org/) textual format that can be further processed by the [dot](https://graphviz.org/download/) program to generate, e.g., svg files from these IRs.

A simple example (dumped by `IRDumper` into a file that is processed with `dot -O -Tsvg file`):
fqn_end_tmp gv

### Important Notes

- GraphViz format is even simpler than JSON format.
- No dependencies added, just 3 simple Java classes.
- Dumping the IR is optional and not used anywhere, when desired, one can dump IRs for example from [Compiler.runPipeline](https://github.com/enso-org/enso/blob/9a91b7bcc61ec4b72cdfb25aadafe08fcbe93ae8/engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala#L438)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]
I'd move the code to a separate SBT project. Otherwise, it looks good to me

**Comment by hubertp** [comment]
> I'd move the code to a separate SBT project. Otherwise, it looks good to me

Yes, maybe it should reside in `tools`?

**Comment by Akirathan** [comment]
> I'd move the code to a separate SBT project. Otherwise, it looks good to me

@4e6 @hubertp I don't think this is a viable option for now. This tool (a single class) is meant to be used inside the `runtime-compiler` project, for example from `Compiler.runCompilerPipeline` or inside `PassManager` to dump graphs after every IR pass. It is not really a standalone tool.

**Comment by JaroslavTulach** [comment]
I believe that having this output in the [IGV format](https://javadoc.io/static/org.graalvm.compiler/compiler/19.1.1/org/graalvm/graphio/package-summary.html) would allow us to compare individual pipeline steps more easily.

**Pull request merged**
