### PR TITLE
Adjust retries for IDE tests

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Comment by farmaazon** [comment]
We should rather prefer https://github.com/enso-org/enso/pull/11602. Retries are not perfect, as they still make builds longer + 5 may be still too few (Jaroslav reported getting error 8 times in a row).

**Comment by MrFlashAccount** [comment]
> We should rather prefer https://github.com/enso-org/enso/pull/11602. Retries are not perfect, as they still make builds longer + 5 may be still too few (Jaroslav reported getting error 8 times in a row).

Yeah, it's a draft and more like a playground to test ideas. Though retries are abslolutely necessary

**Comment by farmaazon** [comment]
> Though retries are abslolutely necessary

Why? I think _fixing the tests_ is necessary, not retries :)

**Comment by MrFlashAccount** [comment]
Retries is a common practice for tests on CI as there are always unavoidable fluctuation due to concurrent access to resources and many other instabilities. Adjusting retries help to reduce the amount of cases when tests fail due to false-positive scenarios.

We do retries though, as you mentioned, even up to 8 times, manually. Why wouldn't we do that automatically?

**Comment by farmaazon** [comment]
> Retries is a common practice for tests on CI as there are always unavoidable fluctuation due to concurrent access to resources and many other instabilities. Adjusting retries help to reduce the amount of cases when tests fail due to false-positive scenarios.

The same fluctuations may happen on user's machines, and they will blame us for that.

> We do retries though, as you mentioned, even up to 8 times, manually. Why wouldn't we do that automatically?

We should not do. If tests require 8 retries, then they should be blocked and fixed.

In GUI playwright tests, we had several cases of flaky tests. After a closer look it, it was _never_ due to CI instability, but
1. The tests were written badly, usually not waiting for some action completion
2. Our application code had a race condition - quite a common case, actually!

Retries will make us blind to those issues. That's why in GUI we decided to _repeat_ tests instead of _retrying_ them (to increase the chance that any irregular failure would be caught before merging).

**Comment by MrFlashAccount** [comment]
Yeah I agree there are different cases and retries _might_ hide potential problems.

But the Gui tests aren't a good example here as they run in `isolated` environment, compared to the real e2e tests. 

If we want to detect flaky tests, lets setup a job that runs on cron once a day/week during off hours and post reports about the flaky tests on discord automatically. It's trivial to implement and you get the best from both worlds

**Comment by MrFlashAccount** [comment]
> Retries will make us blind to those issues. That's why in GUI we decided to repeat tests instead of retrying them (to increase the chance that any irregular failure would be caught before merging).

I hope I proved you by my recent CI changes that it was a mistake and gives nothing except anger from peers

**Comment by farmaazon** [comment]
> I hope I proved you by my recent CI changes that it was a mistake and gives nothing except anger from peers

Not at all. The Project View tests are actually fairy stable. So actually, those proved long ago that I'm right. The anger comes from the fact that dashboard tests are constantly failing.

And now, package tests failed, for the first time. And I prefer to just block them, as I did, and this way unblock the peers, and fix the tests properly

**Comment by farmaazon** [comment]
> But the Gui tests aren't a good example here as they run in isolated environment, compared to the real e2e tests.

I don't see any connection here. Even more, e2e should not be flaky - if they are flaky for CI, they will be flaky for users.

**Comment by MrFlashAccount** [comment]
> The Project View tests are actually fairy stable. So actually, those proved long ago that I'm right

This is not correct, if you wasn't notified about these failures, this doesn't mean they're stable. Relying on the other devs that tend to just restart a task instead of getting notified about flaky tests automatically is very naive

**Comment by MrFlashAccount** [comment]
> I don't see any connection here.

More moving parts, more instability

**Comment by farmaazon** [comment]
> This is not correct, if you wasn't notified about these failures, this doesn't mean they stable. Relying on the other devs that tend to just restart a task instead of getting notified about flacky tests automatically is very naive

That's why I regularly check actions on develop and track failures there. Thence, I know that the failures are mostly in dashboard tests. I even tracked a record here: https://github.com/enso-org/enso/issues/11458

Of course, notifications in discord would help. But the problem of angry men due to tests instability is better solved by just not-running them on unrelated changes.

In case of E2E (package) tests, retries will avail nothing: seeing flaky test, everyone must make sure before that _their_ PR does not introduce flakiness.

**Comment by MrFlashAccount** [comment]
> That's why I regularly check actions on develop and track failures there. Thence, I know that the failures are mostly in dashboard tests. I even tracked a record here: https://github.com/enso-org/enso/issues/11458

Let's enable reruns on develop then. This is exactly what I'm pointing: we shouldn't block the work of peers just to check if there are flaky tests. It's unproductive for us and gives nothing but angry. I'm proposing a different approach: instead of checking this in PRs, check on cron (e.g. over nightly builds) or, as you mentioned over develop. Create issues for flaky tests, plan the work and fix them

**Comment by MrFlashAccount** [comment]
Btw, an example of a job that fails due to `project-view` tests, that passed only on third retry: https://github.com/enso-org/enso/actions/runs/11942912488/job/33291219580

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</div></blockquote>

**Comment by farmaazon** [comment]
> Btw, an example of a job that fails due to `project-view` tests, that passed only on third retry: https://github.com/enso-org/enso/actions/runs/11942912488/job/33291219580
> 

I checked that. This is actually a dashboard failure (look at line 1053 of the log: https://github.com/enso-org/enso/actions/runs/11942912488/job/33291219580#step:7:1053) The logs before are actually expected failures in expectations (stray console.log, I will remove it on some occasion) and they do not cause test fail - I checked that on similar failure on develop.


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Fix React Compiler lints + improve performance · enso-org/enso@a5f000b</div></blockquote>

**Comment by farmaazon** [comment]
> we shouldn't block the work of peers just to check if there are flaky tests. It's unproductive for us and gives nothing but angry.

So we've already fixed that, right? Because peers won't be affected by GUI tests if they didn't change GUI.

If they _did_ change, they have to check anyway, if they don't introduce flaky tests in their PR. So it gives _something_.

The flaky tests shall be fixed very ASAP anyway; they _always_ may obscure actual failures if they'll wait, more flaky tests will be merged, and even retries won't avail us - again PRs will be blocked.

**Comment by MrFlashAccount** [comment]
Anyway I'd prefer having automated reports for flaky tests, and btw retries do mark flaky tests as well

By peers I mean any of your colleagues, not only the guys working on libs/engine stuff. 

I'm still standing on the position to iterate faster and just plan a day/couple of hours to fix flaky tests during a sprint, if there are some.

**Comment by farmaazon** [comment]
> By peers I mean any of your colleagues, not only the guys working on libs/engine stuff.

As I said, then I would need to check anyway if it isn't _my_ code which introduces flakiness.
Having flaky tests cumulating will also slow down iteration: if your PR is blocked, you must spend more time realizing which of, let's say, 3 failures are real and which because of inherited flakiness.
Project View confirms, that if tests are fixed _right away_ (or blocked), the slowdown of iteration is little, because the tests are just stable. But this stability is earned by _repeating and not retrying_ tests.

**Pull request closed without merging**
