### PR TITLE
Generate index when invoking `buildStdLib` tasks

### LINKED ISSUE #5999: `buildStdLib***` tasks do not re-generate the corresponding stdlib index
### Motivation

https://github.com/enso-org/enso/pull/5700 and https://github.com/enso-org/enso/pull/5698 introduced additional step when building the distribution that builds indexes for individual stdlib components (caches and suggestions, respectively).
Library team makes a heavy use of `buildStdLib***` tasks that only rebuild libraries without touching runtime. Those tasks, however, do not trigger index rebuild.

This is slowing down library team.

### Expected result

sbt's `buildStdlIb` tasks should also rebuild indexes, if necessary.

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

The change adds support for generating suggestions and bindings when using the convenient task for building individual stdlib components. By default commands do not generate index since it adds build time. But `buildStdLibAllWithIndex` will.

Closes #5999.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] ~The documentation has been updated, if necessary.~
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~Unit tests have been written where possible.~
  - [ ] ~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]

**Comment by radeusgd** [comment]
Can we make this opt-out? I suggest a parameter like `buildStdLibAllNoIndex` which could do the rebuild in the same way as it used to, without rebuilding the indices.

I'm using `buildStdLibAll` **a lot** when iterating on libraries. Currently, it takes about 0-2s to update on changes. With this change, a single line change in Base takes 14s to update. That's not very bad, but it does a wait time that is a bit annoying if I run it multiple times throughought the day.

Of course I appreciate being able to quickly rebuilt indices, but I think in many cases we can iterate on libraries without it, so it would be good to be able to do so and have instantaneous iteration times.

Second thing is - I noticed that after I change a thing for example in `Base`, apparently the first invocation is for example 14s, second is 8s and only third one is 0s. And looking at the logs, both first and second invocation after change contain:
```
[IJ]buildStdLibAll
[info] Building standard library package for 'Base'
[info] No changes detected for 'Base' package
Generating index for built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base
```

This is suspicious - it should be cached after the first run, right? Somehow it requires two runs to properly 'settle in'.

**Comment by hubertp** [comment]
I could also do the opposite - provide `buildStdLibAllWithIndex` rather than always generating the index.
The initial problem was discovered by @jdunkerley, so maybe you can mention what's your preference?

**Comment by jdunkerley** [comment]
> I could also do the opposite - provide `buildStdLibAllWithIndex` rather than always generating the index. The initial problem was discovered by @jdunkerley, so maybe you can mention what's your preference?

I guess that makes sense to make the default not include - as we only need index if we change signatures etc.

**Comment by hubertp** [comment]
@radeusgd found the reason for second generation. Also, added `buildStdLibAllWithIndex` to generate the index rather than making it the default.

**Review by radeusgd — APPROVED** [review]
CooL!

> found the reason for second generation.

Out of curiosity: what was it?

**Comment by hubertp** [comment]
> Out of curiosity: what was it?

Regex matched `.enso` directory which was obviously updated due to the generated caches.

**Pull request merged**
