### PR TITLE
docs: fix link to Rust style guide

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

The link in gui/docs/CONTRIBUTING.md was broken for some time due to changes on website. I think I found the correct one.

### Important Notes

Applying `npx prettier --write gui/docs` leads to huge changes to all markdown files, so Markdown style guide was ignored in this PR and manual formatting was used.

### Checklist

Please include the following checklist in your PR:

- ~~The documentation has been updated if necessary.~~
- ~~All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.~~
- ~~All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.~~
- ~~All code has been tested where possible.~~

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]

**Comment by wdanilo** [comment]
Why this PR is not merged yet? It was accepted 6 days ago. @4e6 do you know what happened here? :)

**Comment by 4e6** [comment]
@vitvakatu needs to resolve conflicting files

**Comment by vitvakatu** [comment]
This PR requires manual conflicts resolution now and CI will fail because this PR was created from enso's fork. I'd rather make a new one. 

Also there are multiple places in project files with invalid links:
```
❯ rg 'dev\.enso\.org'
app/gui/language/ast/impl/src/opr.rs
29:/// https://dev.enso.org/docs/enso/syntax/naming.html#operator-naming

app/gui/docs/CONTRIBUTING.md
105:[Rust style guide 2](https://dev.enso.org/docs/style-guide/rust.html) before
168:  [`ENSO_DATA_DIRECTORY/dist`](https://dev.enso.org/docs/enso/distribution/distribution.html#installed-enso-distribution-layout).

app/gui/language/ast/impl/src/macros.rs
27:/// https://dev.enso.org/docs/enso/syntax/imports.html#import-syntax

app/gui/controller/engine-protocol/src/project_manager.rs
4://! here https://dev.enso.org/docs/enso/language-server/protocol-project-manager.html

app/gui/controller/double-representation/src/tp.rs
41:/// See https://dev.enso.org/docs/distribution/packaging.html for more information about the

app/gui/controller/double-representation/src/module.rs
148:/// See https://dev.enso.org/docs/distribution/packaging.html for more information about the

app/gui/view/graph-editor/src/builtin/visualization/native/error.rs
31:/// [here](http://dev.enso.org/docs/ide/product/visualizations.html).

app/gui/view/graph-editor/src/component/visualization/instance.rs
142:    /// [here](http://dev.enso.org/docs/ide/product/visualizations.html).

app/gui/view/graph-editor/src/component/visualization/foreign/java_script/definition.rs
5://! * [visualization documentation](https://dev.enso.org/docs/ide/product/visualizations.html).

app/gui/view/graph-editor/src/component/visualization/foreign/java_script/visualization.js
64:     * Please refer to [documentation]{@link https://dev.enso.org/docs/ide/product/visualizations.html#lazy-visualizations}

app/gui/view/graph-editor/src/component/visualization/metadata.rs
12:    /// section [here](http://dev.enso.org/docs/ide/product/visualizations.html).
```
I will create a task to fix it

**Comment by vitvakatu** [comment]
@4e6 done, don't know what it was, merge did not require any conflict resolution

**Pull request merged**
