### PR TITLE
Remove `forceCreate` from backend requests; minor bugfixes

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Remove unused `forceCreate` parameter from backend requests
- Also undo bad change to behavior of sorting assets:
  - https://github.com/enso-org/enso/pull/7540#issuecomment-1683699696
- Fix https://github.com/enso-org/cloud-v2/issues/910
  - Closing a project now doesn't close other projects.
  - Unable to properly test, as I cannot get the second project to open
- Fix https://github.com/enso-org/cloud-v2/issues/908
  - Use the `download` module that already exists to download the app...
- Add correct arrow icon for collapsing/expanding folders
  - Turns out this icon had always existed, and I just didn't see it for the longest time
- Hide irrelevant parts of search bar on Local Backend
  - The row of labels
  - `no:`, `has:`, `label:`, `-label:`, `description:`, `-description:` (and their corresponding autocomplete entries)
  - Also change text to say "Type to search for projects." because the other asset types mentioned do not (and will never) exist on the Local Backend.
- Fix search bar eating up `"` and ` ` keypresses
- Fix icons for Data Links and Secrets being swapped in `AssetIcon`

### Important Notes
- The fix for https://github.com/enso-org/cloud-v2/issues/908 has not been tested on Safari (I don't have a macOS machine.)

### Screenshots
Collapsed folder:
image

Expanded folder:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
@somebody1234 I guess I need ask you for help. I tried introducing new `Scheduled` state. This state is intermediate between `Created|Closed` and `OpenInProgress`. I added `Scheduled` to as you can see in my commit but:
- when I open project the request is being issued twice: 1st with success and project state is `Scheduled` and immediately after which results in 500 (cause conditionals on our db fails). I am guessing there is somewhere a  conditional which retries opening if project is not in `OpenInProgress`
- when trying to close project in `Scheduled` no request is being sent

**Comment by somebody1234** [comment]
> which retries opening if project is not in `OpenInProgress`

not too sure about this. it's possible that it's because React Strict mode runs React Effects twice... i'll have to take a look.

> when trying to close `Scheduled` project no request is being sent.

uh oh... will take a look.

**Comment by somebody1234** [comment]
@PabloBuchu i think i've found what's wrong, haven't really tested though

**Comment by somebody1234** [comment]
hmm. actually there's one more issue that i might want to add - specifically:
the dashboard should probably also be switching to presigned urls for downloading files.
and it's a small enough change that it probably belongs in this PR

**Comment by somebody1234** [comment]
*finally* got around to it (among some other fixes)

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
