### PR TITLE
Apply enso-formatter

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Somebody forgot to apply `./run fmt` before committing to develop, so now we have a lot of whitespace changes in files.

### Important Notes

See https://github.com/enso-org/enso/issues/5166

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]

**Review by 4e6 — APPROVED** [review]

**Review by mwu-tow — APPROVED** [review]

**Review by farmaazon — APPROVED** [review]

**Comment by vitvakatu** [comment]
Oh, it is actually hilarious. `enso-formatter` and `rustfmt` are fighting with each other over changes, so `./run lint` fails after `./run fmt`. Any ideas? @farmaazon @wdanilo @mwu-tow

**Comment by mwu-tow** [comment]
> Oh, it is actually hilarious. `enso-formatter` and `rustfmt` are fighting with each other over changes, so `./run lint` fails after `./run fmt`. Any ideas? @farmaazon @wdanilo @mwu-tow

This is really strange. IIRC `enso-formatter` worked by rewriting the Rust files and then finally calling `rustfmt` to overwrite it once more. Having something conflicting with `rustfmt` would be no good, as it would make it impossible (or at least impractical) to use autoformatting in the IDE.

**Comment by vitvakatu** [comment]
I will try to investigate it a bit

**Comment by vitvakatu** [comment]
It seems the issue was that `enso-formatter` actually failed to process one of the files and didn't call `rustfmt` as a result.

**Review by kazcw — APPROVED** [review]

**Pull request merged**
