### PR TITLE
Show REPL console at the end of `main`

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

For any program started with `--repl`, show REPL console at the end of `main` method. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by JaroslavTulach** [comment]
@radeusgd, @Akirathan how do you like this idea? With this change we can execute any program with `--repl` and the execution will stop at the end of `main` method. E.g. you can prepare a script to import whatever you want and just start it with `--repl`.

**Comment by JaroslavTulach** [comment]
One open question is: when one uses `Debug.breakpoint` and it is hit, shall we still stop at the end or not? Vote: +1 to stop, -1 to not stop.

**Comment by radeusgd** [comment]
> One open question is: when one uses `Debug.breakpoint` and it is hit, shall we still stop at the end or not? Vote: +1 to stop, -1 to not stop.

I have mixed feelings. It feels like stopping one more time in that case is only annoying - I ran to hit a breakpoint I set, additionally stopping at the end is usually not desired in that case.

OTOH it feels less consistent then - if the stop-at-end depends on if some breakpoint was hit or not.

**Comment by Akirathan** [comment]
Stopping at the end of the `main` method implicitly with `--repl` option does not seem like a good idea. Most importantly, I think that after https://github.com/enso-org/enso/pull/10709, the name of `--repl` is misleading. I believe a better name would be something like `--enable-debug-server`, or shortly `--debug`.

**Comment by JaroslavTulach** [comment]
One of the motivations for this PR was to demonstrate we **don't need** `Debug.breakpoint` to specify where to stop. That has been demonstrated.

However otherwise this PR received no warm welcome, so I am closing it to re-purpose it in other incarnation.

**Comment by JaroslavTulach** [comment]
Reincarnated in
- #10842

**Pull request closed without merging**
