### PR TITLE
Do not ignore package-lock.json files

### PR DESCRIPTION
**Pull request by PabloBuchu**
### Pull Request Description

This PR fixes inconsistency with semi ignoring package-lock.json. The file was stated as ignore in .gitignore but at the sam time we had some of them in repo (and some not...). This resulted in weird random dependency updates. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by kazcw — APPROVED** [review]

**Review by wdanilo — COMMENTED** [review]
I believe that both `build/prettier/package-lock` and the root `package-lock` should be ignored, as they are build/prettier related and it is safe to bump they even on every build. We Laso want to keep prettier up to date. What do you think of it?

**Comment by PabloBuchu** [comment]
> I believe that both `build/prettier/package-lock` and the root `package-lock` should be ignored, as they are build/prettier related and it is safe to bump they even on every build. We Laso want to keep prettier up to date. What do you think of it?

I don't have strong opinion on that since I don't know full usage of the modules you listed. On the other hand I am fan of consistency. Imho all locks files should be history tracked. 

But I won't fight over it :) If you say so I can ignore them

**Comment by mwu-tow** [comment]
> I believe that both build/prettier/package-lock and the root package-lock should be ignored, as they are build/prettier related and it is safe to bump they even on every build. We Laso want to keep prettier up to date. What do you think of it?

I am against this. Updates to prettier (or linter tools) can result in broken builds. This is what happened on Monday and there was ton of confusion ("why my PRs suddenly fail? The error shows up in a place that I havent touched")

**Review by mwu-tow — APPROVED** [review]

**Comment by wdanilo** [comment]
ok :)

**Pull request merged**
