### PR TITLE
Investigate Oracle GraalVM translated exception issue

### LINKED ISSUE #9457: Random CI failure on Oracle GraalVM: `jdk.internal.vm.TranslatedException: Error decoding exception`
I think I see this failure like this popping here and there:

https://github.com/enso-org/enso/actions/runs/8301012063/job/22720189516#step:8:3770 (Dry-run benchmark `Sieve.Without_Types` in **Oracle GraalVM Engine job**)

```
Execution finished with an error: java.lang.RuntimeException: jdk.internal.vm.TranslatedException: Error decoding exception: [B@71cdcc63
        at <java> org.graalvm.jniutils/org.graalvm.jniutils.JNIExceptionWrapperEntryPoints.createException(JNIExceptionWrapperEntryPoints.java:89)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.newCompiler(Native Method)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.lambda$getOrCreateIsolate$0(LibGraalHotSpotTruffleCompiler.java:72)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalIsolate.getSingleton(LibGraalIsolate.java:99)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.resolveIsolateHandleImpl(LibGraalHotSpotTruffleCompiler.java:80)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.getOrCreateIsolate(LibGraalHotSpotTruffleCompiler.java:70)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.installTruffleCallBoundaryMethod(LibGraalHotSpotTruffleCompiler.java:119)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotTruffleRuntime.installCallBoundaryMethods(HotSpotTruffleRuntime.java:529)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotTruffleRuntime.bypassedInstalledCode(HotSpotTruffleRuntime.java:451)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.interpreterCall(OptimizedCallTarget.java:609)
        at <java> 
…
```

### PR DESCRIPTION
**Pull request by Akirathan**
Fixes #9457

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by Akirathan** [comment]
Trying to reproduce
```
Execution finished with an error: java.lang.RuntimeException: jdk.internal.vm.TranslatedException: Error decoding exception: [B@71cdcc63
        at <java> org.graalvm.jniutils/org.graalvm.jniutils.JNIExceptionWrapperEntryPoints.createException(JNIExceptionWrapperEntryPoints.java:89)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.TruffleToLibGraalCalls.newCompiler(Native Method)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.lambda$getOrCreateIsolate$0(LibGraalHotSpotTruffleCompiler.java:72)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalIsolate.getSingleton(LibGraalIsolate.java:99)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.resolveIsolateHandleImpl(LibGraalHotSpotTruffleCompiler.java:80)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.getOrCreateIsolate(LibGraalHotSpotTruffleCompiler.java:70)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.libgraal.LibGraalHotSpotTruffleCompiler.installTruffleCallBoundaryMethod(LibGraalHotSpotTruffleCompiler.java:119)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotTruffleRuntime.installCallBoundaryMethods(HotSpotTruffleRuntime.java:529)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotTruffleRuntime.bypassedInstalledCode(HotSpotTruffleRuntime.java:451)
        at <java> org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.interpreterCall(OptimizedCallTarget.java:609)
        at <java> 
…
```

In the dry-run benchmarks in `Oracle GraalVM Engine` job

**Comment by Akirathan** [comment]
The verbose option passed to the JVM (https://github.com/enso-org/enso/pull/9481/commits/763cdc61e26418302847e0ba1d5bf6baf9a65741) does not help, i.e., nothing more is printed as can be seen in https://github.com/enso-org/enso/blob/2ea2a576517995bb89886d3191d0568314858fec/engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java#L78

**Comment by Akirathan** [comment]
Since the problem has already been fixed on the JDK side (https://github.com/enso-org/enso/issues/9457#issuecomment-2089908888), let's close this PR as it adds no added value to the solution of the problem.

**Comment by JaroslavTulach** [comment]
Request for backport of [JDK-8329564](https://bugs.openjdk.org/browse/JDK-8329564) into JDK 21 has been entered into _My Oracle Support_:



as SR **3-37944867291**.

**Pull request closed without merging**
