### PR TITLE
Fix issue with circular import

### LINKED ISSUE #8088: Cannot run new GUI
I see blank screen and log:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'recent')
    at index-d13623be.js:13:84778
    at index-d13623be.js:13:193079
```
Tested on c5825719e93ee9ef193a53ded1eb57313929d8bd

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
A recent PR introduced issues with circular imports in `categorySwitcher.ts` - the reason why this wasn't found before merge is because bundlers work fine with circular imports - it's just GUI2's dev mode that doesn't do well with them

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
@PabloBuchu or @indiv0 this needs approval btw

**Comment by farmaazon** [comment]
Fixes #8088

**Comment by PabloBuchu** [comment]
what is `GUI2's dev mode` and how to use it? Is this the one initialized in `gui2/src/main.ts`?

**Comment by PabloBuchu** [comment]
I don't like the idea there is somewhere the same dashboard embeded differently. This should be somehow merged

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
