### PR TITLE
Background translucency

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/558
- Uses the background from the Figma design

### Screenshots

image

### Important Notes
Should double check macOS `--vibrancy` and compare with `--vibrancy` on `develop` to make sure I didn't accidentally break anything

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
oops, forgot to test `ide build` and `ide watch`, will test very soon

**Comment by PabloBuchu** [comment]
@somebody1234 I had to merge with develop (there was a fix for macos build) but I cant open a dashboard see sreenshot
Screenshot 2023-07-25 at 08 58 20

**Comment by PabloBuchu** [comment]
Can we make the same background for the authentication part?

**Comment by somebody1234** [comment]
still not able to test `ide build` and `ide watch`, and i was having issues when running lints because i did a `./run git-clean`

**Comment by somebody1234** [comment]
lints: passing
`watch-enso`: seems like it works (new background is being bundled correctly)
`ide build`: ran into issue building again :( it's the "No matching asset for target" issue

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
