### PR TITLE
Make the code editor editable again

### LINKED ISSUE #7474: Text editor should be editable
Currently the text edit box has become read-only.

It is a useful way to repair imports at the moment.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #7474 

Again, a quite complicated issue. The code editor was broken by https://github.com/enso-org/enso/pull/7167 for a few reasons:
1. The text component's shortcuts depend on the `focused` FRP endpoint, which is controlled by `deprecated_(de)focus` inputs. `focused` output was not changed by the code editor `model.focus()` call. (we still use `deprecated_focus` for all other components)
2. `focus()` FRP input was added to the text component but never triggered. It's too easy to confuse it with the `focus()` method of the `object::Instance` (Deref is evil!)
3. The graph editor handles clicks on the background by `blur_tree()`, effectively blurring any focused element in the application. But clicking on code editor (to focus it) also causes a click on the background! So we focus the code editor, and then handle the background click, defocusing it from the graph editor's point of view. It allows graph editor to open CB on <kbd>Enter</kbd> while the code editor is still active.

I solved (3) by disallowing CB opening while code editor is visible. Not ideal, but I guess it solves the issue.

Do you think the other solution is possible – to add some overlay for the code editor and avoid triggering `blur_tree` when clicking on it? That won't work because you still can't defocus the code editor using the new API, so it will always be focused.

So we have a situation when half of the app uses the new focus system, another half uses the old one, and none works properly.

https://github.com/enso-org/enso/assets/6566674/3a0d36ed-4d50-4606-9486-272fbd5d9cb7

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by kazcw — APPROVED** [review]

**Review by farmaazon — APPROVED** [review]
So, does the text component use new focus, or old deprecated focus? I feel we could fix it properly in the new focus, but of course there are other priorities right now.

**Comment by vitvakatu** [comment]
> So, does the text component use new focus, or old deprecated focus? I feel we could fix it properly in the new focus, but of course there are other priorities right now.

The old one, using the new focus is basically not supported at the moment.

**Comment by MichaelMauderer** [comment]
QA: :red_circle: 

While this might not be the original issue, it is related to focus, and it is still broken: when having the editor open and starting to edit a node, the editor does not lose focus. The editor actually gains another cursor. 

Peek 2023-09-20 16-28

**Comment by farmaazon** [comment]
We still warn about using graph editor having code editor opened: https://github.com/enso-org/enso/blob/b9ec6d4ec307cc5e3c5949688588b08f3b9f978a/app/gui/docs/product/shortcuts.md#L40

So I would not block PR because of this issue.

**Comment by vitvakatu** [comment]
Unfortunately we can't merge it. Marking as draft until the issue is addressed.

**Comment by vitvakatu** [comment]
I had to merge this PR with `new-ide-build` branch, because I couldn't test it otherwise. I will rebase on develop once the `new-ide-build` is merged.

The issue reported by Michael is mitigated by hiding the code editor when we select or edit nodes in the graph editor. A proper solution supporting the new focus API for the text component proved much more complicated (in particular, I accidentally broke nodes in the graph editor when implementing it).


https://github.com/enso-org/enso/assets/6566674/f6676357-7952-4c30-823c-ab27ba5aa72e

**Comment by MichaelMauderer** [comment]
QA: :green_circle:

**Pull request merged**
