### PR TITLE
Even more dashboard fixes

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix https://github.com/enso-org/cloud-v2/issues/1383
  - Fix file download - both on Electron, and in browser
  - Refresh versions list when uploading neww file version
  - Fix app crashing when asset is opened in asset panel while switching to Local Backend
  - Don't show asset id when asset is opened in asset panel, but user is on the Local backend, resulting in the internal Asset ID being shown
  - Fix drag-n-drop
  - :warning: `npm run dev` is NOT fixed in this PR - however it should already be fixed in another PR which has already been merged. This needs testing to confirm whether it is fixed though.

Other changes:
- Add support for "duplicate project" endpoint on Local Backend
- Fix downloading project from nested directory on Local Backend (not working)
- Refactor more E2E tests to use the "new" architecture
- Simplify "new" E2E architecture to minimize boilerplate

### Important Notes
- When testing downloads, both Electron and browser should be tested as they use completely separate implementations for how files are downloaded.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
QA ✅

**Comment by farmaazon** [comment]
Seeemingly it also fixes [#10487](https://github.com/enso-org/enso/issues/10487)

**Comment by somebody1234** [comment]
ah, right yeah. i don't remember why i bumped electron in this PR... i guess it was to access some extra parameters on Electron's file download

**Comment by somebody1234** [comment]
i think it makes sense to leave that issue open though because i haven't reviewed the `electron.app.commandLine.appendSwitch` stuff

**Pull request merged**
