### PR TITLE
Better `release` build time; new maximum-performance `production` profile.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Using the new tooling (#3491), I investigated the **performance / compile-time tradeoff** of different codegen options for release mode builds. By scripting the testing procedure, I was able to explore many possible combinations of options, which is important because their interactions (on both application performance and build time) are complex. I found **two candidate profiles** that offer specific advantages over the current `release` settings (`baseline`):
- `thin16`: Supports incremental compiles in 1/3 the time of `baseline` in common cases. Application runs about 2% slower than `baseline`.
- `fat1-O4`: Application performs 13% better than `baseline`. Compile time is almost 3x `baseline`, and non-incremental.  
(See key in first chart for the settings defining these profiles.)

We can build faster or run faster, though not in the same build. Because the effect sizes are large enough to be impactful to developer and user experience, respectively, I think we should consider having it both ways. We could **split the `release` profile** into two profiles to serve different purposes:
- `release`: A profile that supports fast developer iteration, while offering realistic performance.
- `production`: A maximally-optimized profile, for nightly builds and actual releases.

Since `wasm-pack` doesn't currently support custom profiles (rustwasm/wasm-pack#1111), we can't use a Cargo profile for `production`; however, we can implement our own profile by overriding rustc flags.

### Performance details

perf

As you can see, `thin16` is slightly slower than `baseline`; `fat1-O4` is dramatically faster.

<details>
  <summary>Methodology (click to show)</summary>

I developed a procedure for benchmarking "whole application" performance, using the new "open project" workflow (which opens the IDE and loads a complex project), and some statistical analysis to account for variance. To gather this data:

Build the application with profiling:
`./run.sh ide build --profiling-level=debug`

Run the `open_project` workflow repeatedly:
`for i in $(seq 0 9); do dist/ide/linux-unpacked/enso --entry-point profile --workflow open_project --save-profile open_project_thin16_${i}.json; done`

For each profile recorded, take the new `total_self_time` output of the `intervals` tool; gather into CSV:
`echo $(for i in $(seq 0 9); do target/rust/debug/intervals < open_project_thin16_${i}.json | tail -n1 | awk '{print $2}'; do`
(Note that the output of intervals should not be considered stable; this command may need modification in the future. Eventually it would be nice to support formatted outputs...)

The data is ready to graph. I used the `boxplot` method of the [seaborn](https://seaborn.pydata.org/index.html) package, in order to show the distribution of data.
</details>

#### Build times
thin16

In the case of changing a file in `enso-prelude`, with the current `baseline` settings rebuilding takes over 3 minutes. With the `thin16` settings, the same rebuild completes in 40 seconds.

(To gather this data on different hardware or in the future, just run the new `bench-build.sh` script for each case to be measured.)

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run.sh ide dist` and `./run.sh ide watch`.

### CODE REVIEW

**Comment by kazcw** [comment]
Most of the implementation of this is actually in the build scripts, since wasm-pack doesn't support custom profiles.

@mwu-tow

The build script changes to support this are:
- Offer two different profiles for optimized, non-debug builds: `release` and `production`.
- Invoke `wasm-opt` from the build script after all release/production builds (this PR disables `wasm-pack` running it). We should use the same options `wasm-pack` has been using, except:
  - For `release` builds, pass `-O3`
  - For `production` builds, pass `-O4`
- For `production` builds, override some of the Cargo profile's codegen options via `RUSTFLAGS`:
  - `RUSTFLAGS="-Clto=fat -Ccodegen-units=1 -Cincremental=false"`

And in CI:
- Nightly builds should use the `production` profile. This will take about 3x as long to build, largely due to less parallelism. However this way we will be able to use nightlies to try the app with the performance of real releases.

Merging this PR:
- Because we are moving responsibility for running `wasm-opt` from `wasm-pack` to the build scripts, this PR should be merged together with the corresponding build-script changes; otherwise developers may experience doubly-optimized or under-optimized release builds in the interim between updates to the two repos.

Does all that make sense?

**Comment by mwu-tow** [comment]
@kazcw 
It makes sense. That's a great write-up.👍

**Comment by mwu-tow** [comment]
@kazcw 
While implementing this I've encountered an issue.
Setting `RUSTFLAGS="-Clto=fat -Ccodegen-units=1 -Cincremental=false"` causes the compilation to fail:

```error: lto can only be run for executables, cdylibs and static library outputs```
I suspect that it is trying to apply these flags even to the proc-macro outputs. Do you encounter the same issue?

**Comment by kazcw** [comment]
@mwu-tow
Sorry, I had only tested these settings by modifying a Cargo profile, and expected `RUSTFLAGS` would be equivalent; I didn't realize `RUSTFLAGS` had a broader effect.

We can't override these profile settings with `RUSTFLAGS`. I think the only option currently available is to generate a `Cargo.toml` to define the profile dynamically, but that is pretty gross.

It seems like it should be really simple for `wasm-pack` to handle custom profiles. However, I'm not sure it's worth writing a PR; they have a huge backlog of PRs and issues, and haven't responded to our month-old PR implementing a 0-code fix to an annoying bug (rustwasm/wasm-pack#1136). @wdanilo mentioned on Discord that we might do without `wasm-pack`; if we were running Cargo directly, we wouldn't have this problem.

So, maybe we should (@wdanilo, what do you think?):
- For now, switch `release` builds to the `thin16` profile options--I don't think the lack of a current way to enable `production` builds needs to hold up improving developer productivity. One way or another we can get `production` builds working long before we do a real release.
- Look in to ditching `wasm-pack`, and implement the `production` profile according to how that turns out.
  - If we can do without `wasm-pack`, we can simply use the original version of this PR; the only accompanying build script change would be allowing `production` as a profile argument.
  - If we must use `wasm-pack`, we could either fix the issue and use our own fork (until upstream accepts the changes, if ever); or, implement the dynamically-generated `Cargo.toml`.

**Comment by mwu-tow** [comment]
@kazcw 
Ok, so for now I'll skip `production` profile support and integrate the rest.

As for `wasm-pack` — I'd be leaning towards forking it (and upstreaming changes later if mainteners show interest), this looks doable. And makes more sense than trying to work around the tool. But that's for later.

**Comment by wdanilo** [comment]
Let's fork it then. I'm always afraid of forking and maintaining projects TBH. @kazcw could you write an email to https://github.com/drager mentioning this issue (that our PR is not being merged and we are concerned if other PRs will, and we are thinking about forking and maintaining a fork, but we would prefer not to)? If you can, add me to CC, please.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/drager">drager - Overview</a></strong></div><div>🦀. drager has 84 repositories available. Follow their code on GitHub.</div></blockquote>

**Comment by mwu-tow** [comment]
Merging with the updated build script.

One item to note is that I had to bump 4.5MiB -> 4.84MiB, which is due to lower optimization level. We should get that back when we introduce the `production` profile.
That will be tracked as https://www.pivotaltracker.com/story/show/182443428

<blockquote><div><strong><a href="https://www.pivotaltracker.com/story/show/182443428">Support custom profiles in wasm-pack - Pivotal Tracker</a></strong></div></blockquote>

**Pull request merged**
