### PR TITLE
Disable signing artifacts for PRs and develop

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Added `*-sign-artifacts` to disable/enable signing. By default it is true, except for PRs and develop.

### Important Notes

#11082

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by hubertp** [comment]
Please be gentle, my Rust is rusty.

**Review by jdunkerley — APPROVED** [review]

**Comment by hubertp** [comment]
Screenshot from 2024-09-16 20-37-42
1h15' -> 26'

**Comment by hubertp** [comment]
So opening non-notarized/unsigned Enso app will show a big red error on MacOS. The only possibility is to enable opening such files via https://support.apple.com/en-us/102445#openanyway, right-click and open anyway.
@jdunkerley is this acceptable?

<blockquote><div> Apple Support</div><div><strong><a href="https://support.apple.com/en-us/102445">Safely open apps on your Mac - Apple Support</a></strong></div><div>macOS includes a technology called Gatekeeper, that's designed to ensure that only trusted software runs on your Mac.</div></blockquote>

**Comment by Frizi** [comment]
For me that's OK, as long as this is limited to PR builds. Faster PR checks are a big deal, and we shouldn't publish those builds anyway. For occasional debugging purposes the extra step to open is not a big deal.

**Review by Frizi — APPROVED** [review]

**Review by somebody1234 — APPROVED** [review]
approving added arg to `electron-builder-config.ts`

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
