### PR TITLE
Disable opening projects that are already opened by other users

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/568
  - Disable project with an `openedBy` that is not the current user

Fixes other issues:
- Fixes freshly restored saved projects not being unset when clicking stop before the editor first opens
- Changes "unable to" in errors to "could not", for consistency
- Users with insufficient permissions now see a network (node graph) icon instead of a play button:

image

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
@somebody1234 

The whole row should be disabled with rename / trash... I can even bypass the secuirty by right click -> open

Screenshot 2023-08-28 at 13 06 17

**Comment by somebody1234** [comment]
ah... good catch, thanks. will fix soon

**Comment by somebody1234** [comment]
@PabloBuchu should be ready for re-testing now

**Comment by PabloBuchu** [comment]
Also I've just spoted a bug where the `https://xw0g8j3tsb.execute-api.eu-west-1.amazonaws.com/projects/project-2Ubrc2XW5hDYd7jKPbpbCE3eG2r/open` was issued under the hood 

it was during testing this PR but need to double check with develop and after this fix

**Comment by somebody1234** [comment]
yeah that *should* be fixed after the latest commit in this branch

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
