### PR TITLE
Add React compiler

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

This PR adds React Compiler to the dashboard
Read more about the compiler: https://github.com/reactwg/react-compiler/discussions/5

- This PR expects that these PRs are merged:
  - #11380
  - #11382

## Reasoning

On our codebase adding React compiler led to significant perf improvements across the whole app. But the most impact was on the AssetsTable (see video attachment). Adding React compiler reduced the rerender scope of the AssetsTable from the whole table to the certain elements that changed, and made the table much more usable.

Without compiler (page freezed):

https://github.com/user-attachments/assets/16505b40-123b-4153-9c22-880f5dfa211c

Compiler solves the issue:

https://github.com/user-attachments/assets/6a298876-f28d-4b3d-8247-50b0c7ecb7f8

This PR requires thorough testing of the dashboard for potential bugs introduced by the compiler

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark: 

very minimal code changes, most changes are in `pnpm-lock.yaml`

**Comment by MrFlashAccount** [comment]
@PabloBuchu tests have passed

**Comment by somebody1234** [comment]
there was a merge conflict but it was caused by removed code in `AssetRow`, resolved conflict by removing the code in the conflict

**Comment by somebody1234** [comment]
hmm oops forgot  to pull

**Comment by MrFlashAccount** [comment]
@somebody1234 Thank you!

**Comment by somebody1234** [comment]
i unstuck the funny stuck CLA check with https://cla-assistant.io/check/enso-org/enso?pullRequest=11405 just as a heads up/PSA

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/">GitHub · Build and ship software on a single, collaborative platform</a></strong></div><div>Join the world's most widely adopted, AI-powered developer platform where millions of developers, businesses, and the largest open source community build software that advances humanity.</div></blockquote>

**Pull request merged**
