### PR TITLE
Dashboard improvements

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Frontend part of https://github.com/enso-org/cloud-v2/issues/1397
  - Show organization details to everyone (behavior unchanged)
  - :warning: Allow editing only for admins
    - :warning: Currently there is no backend endpoint to get organization permissions
  - Stop (incorrectly) submitting *all* settings inputs twice
- Frontend part of https://github.com/enso-org/cloud-v2/issues/1396
  - Fix "remove invitation" sending wrong request
  - Stop sending `organizationId` in "create invitation" request
  - Not adding `email` autocomplete to `/registration`
    - Currently already exists
    - but it will need to be revisited after the new sign up flow PR is merged.
- Fix https://github.com/enso-org/cloud-v2/issues/1407
  - Fix project open request being sent multiple times
- Address https://github.com/enso-org/enso/issues/10633#issuecomment-2252540802
  - Fix path to local projects (previously gave the path to their containing folder

Other fixes:
- Various fixes for autocomplete:
  - Fix autocomplete appearance (dropdown is no longer detached from main input)
  - Add tooltips for overflowing autocomplete entries
- Add tooltips for overflowing usernames in "manage permissions" modal
- Animate height of "asset search bar" dropdown and "autocomplete" dropdown
- Auto-size names of object keys in Datalink input

Other changes:
- Avoid gap with missing background on right side of tab bar when resizing window due to the clip path being animated
- Add <kbd>Cmd</kbd>+<kbd>W</kbd> and <kbd>Cmd</kbd>+<kbd>Option</kbd>+<kbd>W</kbd> to close tab
- Make <kbd>Escape</kbd> only close tab if it is the Settings tab (a temporary tab)

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
i guess we need a better way to display input errors...

image

we *do* have a dedicated form component but i think it operates on the form as a whole, whereas here (currently) we are treating each input as its own mini form.

should we perhaps be switching to explicit "save" and "discard"/"cancel" buttons?

**Comment by PabloBuchu** [comment]
> Stop (incorrectly) submitting all settings inputs twice

create_user request is also being send twice. project open sometimes 3 times.. can we take a look across the dashboard and check?

**Comment by somebody1234** [comment]
> create_user request is also being send twice

oh forgot that this will probably be fixed by the new sign up flow but fixed locally on this branch anyway. will investigate the other stuff

**Comment by somebody1234** [comment]
should be fixed, pushing now

**Comment by PabloBuchu** [comment]
@somebody1234 can we disable `remove` in Members page under self user? Things will go south really quickly if I remove myself

**Comment by somebody1234** [comment]
umm... yeah that's probably be a good idea. should be fixed now

**Comment by PabloBuchu** [comment]
> Not adding email autocomplete to /registration

For emails with `+` like: "pawel.buchowski+new@enso.org" autofilled value skip the `+` making it invalid email
Screenshot 2024-07-30 at 11 57 09

**Comment by somebody1234** [comment]
ah... that's because `+` means ` ` in urls. i've fixed it by escaping the email on the frontend side, not sure whether backend ever makes its own redirect link?

**Comment by PabloBuchu** [comment]
`Resend` uses wrong url.. it tries to `POST /invitations` but we should reuse same url we use for inviting which is `/users/invite`

**Comment by PabloBuchu** [comment]
> Allow editing only for admins
> ⚠️ Currently there is no backend endpoint to get organization permissions

@somebody1234 would it help if I add `is_admin` to `organizations/me` flag?

**Comment by somebody1234** [comment]
yeah `is_admin` would work

**Comment by PabloBuchu** [comment]
so I will add it and if we can please do the same for members and users_groups. so all can view but only is_admin can edit

**Comment by somebody1234** [comment]
@PabloBuchu all new comments should be addressed now

**Comment by PabloBuchu** [comment]
maybe not exactly about "Address https://github.com/enso-org/enso/issues/10633#issuecomment-2252540802
Fix path to local projects (previously gave the path to their containing folder" but since we touched this.. if I create a project and immediately try to move it to subfolder (while opening in progress) things will get messy with prject manager (in cloud as well). I think we should disable draging around project that are opening or are opened

https://github.com/user-attachments/assets/79def788-3e0f-40b7-8ffe-0fec09038b7b

**Comment by PabloBuchu** [comment]
@somebody1234 dragging local projects doesn't work right now at all :| also disabling draging project while not in `created|closed` should also be implemented for `Cloud`

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
QA ✅ lets merge it and deploy to prod

**Pull request merged**
