### PR TITLE
User & Team spaces

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Depends on https://github.com/enso-org/cloud-v2/pull/1344
- Implement https://github.com/enso-org/cloud-v2/issues/1342
  - Refactor `Category` type to allow for extra metadata (user/team id and home directory path)
  - Show list of users and teams in sidebar
  - Add "My Files" category for users with team/enterprise plan - because in that case, the directory opened by the "Cloud" category is the organization's root directory, not the user's root directory

### Important Notes
None

### Testing Instructions
- Make sure "Copy As Path" copies the correct paths

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Things to add / improve:
1. Auto append newly create asset to user home directory (currently tries to add next to `Users` and `Teams` folders)
2. Block adding assets to `Users` and `Teams`
3. When I add something to the team home directory the `Own` permission is created on the fly for the request user. In those folders the owner is the group (proper permission show up after reload)
4. Clear trash should only try clearing assets

**Comment by somebody1234** [comment]
> Auto append newly create asset to user home directory

not sure about this one tbh. maybe it should be replaced with a button that navigates the user to the "my home" category?

> Clear trash should only try clearing assets

what should it not try clearing?

**Comment by PabloBuchu** [comment]
>>Clear trash should only try clearing assets

>what should it not try clearing?


Sorry should have been more clear. Right now when I navigate to trash and hit `clear trash` it starts with removing `Users` and `Teams` directories which ends up with 403 and thus stopping clearing the rest. We should exclude `Users` `Teams` and users and user groups home dirs from the requests


https://github.com/user-attachments/assets/4b00c8c9-e613-4995-a05a-a31746cf1dc8

**Comment by PabloBuchu** [comment]
this button `create assets in my files` and hidden creation buttons is misleading. Lets rollback this and leave as it was before. We will consult with James and Sylwia on demo and then decide.

The rest is LGTM and I think we can create PR

**Comment by somebody1234** [comment]
@PabloBuchu both issues *should* be addressed although re-QA might be a good idea. not sure whether i should mark this PR as ready for review though as the corresponding backend PR is also in draft state still

**Comment by PabloBuchu** [comment]
1. No mather what I select the top creation bar is always disabled

Screenshot 2024-07-22 at 15 30 21

2. From the console
Screenshot 2024-07-22 at 15 30 50

lets open both PRs

**Comment by somebody1234** [comment]
> No mather what I select the top creation bar is always disabled

uh oh, yeah i forgot buttons add to the currently selected asset (i think...)

> duplicated key error from the console

yeah it's due to this:
image

so for the time being i'm considering it as a [wontfix]

**Comment by somebody1234** [comment]
#1 should finally be properly addressed

**Comment by PabloBuchu** [comment]
1. When I copy from user to team I get wrong owner in share with table (when moving we also need to change it so it always become a group asset).
2. Please block moving assets from team spaces -> user space (the API will return 400 so we can just make sure visually it wont be appended)

**Comment by somebody1234** [comment]
both points should be addressed - i've also fixed a bug where the context menus don't check for team permissions when checking for the permission level of the user

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
