### PR TITLE
(even more) Dashboard fixes

### LINKED ISSUE #7589: Empty project opened after pressing enter to confirm project name change
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I finished typing new name for the project I have pressed Enter to confirm the name change. This started opening the project (with old name) but it opened a blank project (just like a new project with starting node). When I closed it the project had it's name renamed and when I have opened it it had all the nodes I have created previously.

https://github.com/enso-org/enso/assets/108271897/d425f8cd-b705-48e8-96f0-9af5638528d1

^^ repro recording

This is error message I have gotten after I managed to confirm the name change with the checkbox after pressing enter (that opened the project):
image
^^ error from 1st occurrence 

Another issue that happened after this weird behavior is that Enso in assets view didn't recognize the name changed and crashed on launch of this project (but I couldn't repro that).

### Expected behaviour

Enter confirming name change, nor opening the project.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

2023.8.15 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fixes display of the assets table in Firefox. Before this fix, the table header grows instead of the table footer.
It seems like the correct behavior for tables is to [not be valid flex children](https://stackoverflow.com/a/41421700/3323231), so the correct fix is to add a `flex` wrapper div.
- Fixes missing error toast notification when `startup.project` is invalid
- Fixes #7589
  - Enter (incorrectly) causes projects to be opened when the name is being edited
- Gracefully fail when `projectState` is missing from an asset
- Avoid opening editor for previously opened project, when `startup.project` is provided
- Fixes https://github.com/enso-org/cloud-v2/issues/688
  - Fixes CSS for search bar
- Fixes https://github.com/enso-org/cloud-v2/issues/689
  - Adds "New <X>" entries back to context menus for regular assets
- Fixes https://github.com/enso-org/cloud-v2/issues/692
  - Fix `z-index` of top left (page switcher) icons
- Fixes https://github.com/enso-org/cloud-v2/issues/693
  - Fix restoring local projects after closing and reopening
- Adds blur to top right menu bars for extra visibility

### Important Notes
Testing should test Firefox and Chrome (testing on Safari is optional) to make sure the following is working correctly:
- The table looks normal
- The context menu still triggers below the table (both with and without items being selected)
- There is no scrollbar if the table is shorter than the viewport

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
@PabloBuchu / @indiv0 pinging for visibility

**Comment by PabloBuchu** [comment]
I am having problems with `-startup.project` it looks like it doesn't search for projects locally... also I think it should prioritize local projects over cloud if they have the same names.

Screenshot 2023-09-26 at 13 33 15
Screenshot 2023-09-26 at 13 33 13

**Comment by somebody1234** [comment]
@PabloBuchu `startup.project` only ever checks on the current backend - i don't think that's a bad thing. we could maybe add a `startup.backend` if we want to explicitly open a cloud project?

it *is* true however, that it's sometimes useful to search the local backend at least, in case the user is opening a project from a file (so the IDE is passed the project ID)... thoughts?

**Comment by PabloBuchu** [comment]
@somebody1234 
| only ever checks on the current backend 
take a look on the recording. I opened Enso to show that local was latest backend. Then used `-startup.project` and it only searched in cloud


https://github.com/enso-org/enso/assets/2855109/4f1d4b4a-4ed4-4dce-b71c-6563e307246c

**Comment by somebody1234** [comment]
ah that's odd, will take a look then

**Comment by somebody1234** [comment]
ah i think that's a regression? may or may not have found the cause.
also note that some of the issues above have not been pushed yet

**Comment by somebody1234** [comment]
changes pushed. not 100% sure about the fix for this one:
- https://github.com/enso-org/cloud-v2/issues/693

**Comment by PabloBuchu** [comment]
> changes pushed. not 100% sure about the fix for this one:
> 
> * [Retrieving local project from localStorage is broken cloud-v2#693](https://github.com/enso-org/cloud-v2/issues/693)

So retrieving works but:
1. After reruning Enso and success retrieval of opened project when I go back to dashboard I don't have `play` icon. If I now exit the Enso and go back I won't be able to open running project (see video).
2. The empty bacground screen when you open Enso and when the Enso spinner shows up is weird. Are we able to do something about it? Can we display the Enso spinner from the beginning?


https://github.com/enso-org/enso/assets/2855109/fdcbb67a-c5da-49ff-afee-ca83c956cedc

**Comment by somebody1234** [comment]
> Can we display the Enso spinner from the beginning?
no, it's not part of our codebase

i agree that the empty background is weird though. i can see whether it's possible to display a blank screen until the spinner shows up?

**Comment by somebody1234** [comment]
@PabloBuchu on second thought, i think it's preferable to stick with the empty background for now. it *might* be possible to show a white screen until the spinner shows up, but if the spinner never shows up then the white screen would never go away

**Comment by PabloBuchu** [comment]
So the retrieving is broke again. Are we able to fix this on dashboard layer? 

```
[INFO] [2023-09-29T10:18:26+02:00] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[INFO] [2023-09-29T10:18:27+02:00] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [8152f262-1f9f-4dc0-b8e2-7439d776204a]
[INFO] [2023-09-29T10:18:27+02:00] [org.enso.languageserver.boot.MainModule] Closed Language Server main module.
[INFO] [2023-09-29T10:18:27+02:00] [org.enso.languageserver.boot.LanguageServerComponent] Terminated main module.
[INFO] [2023-09-29T10:18:27+02:00] [ch.qos.logback.classic.net.SocketNode] Caught java.io.EOFException closing connection.
[INFO] [2023-09-29T10:18:27+02:00] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Language server shut down successfully [Project(aeda375b-b841-4755-bdad-3b4799c91113,New_Project_1,New_Project_1,local,UserProject,2023-09-14T10:24:31.402623Z,Some(Edition(Some(2023.2.1-nightly.2023.9.29),None,Map(),Map())),/Users/pawelbuchowski/enso/projects/New_Project_1,Some(2023-09-29T08:18:02.350466Z),Some(2023-09-14T10:24:32Z))].
[WARN] [2023-09-29T10:18:27+02:00] [org.enso.projectmanager.infrastructure.languageserver.ShutdownHookActivator] Shutdown hook activator has no recollection of project aeda375b-b841-4755-bdad-3b4799c91113. Either it was closed already or it never existed. Ignoring.
[INFO] [2023-09-29T10:18:27+02:00] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] All language servers have been killed.
[INFO] [2023-09-29T10:18:27+02:00] [akka.actor.LocalActorRef] Message [org.enso.projectmanager.infrastructure.languageserver.package$GracefulStop$] from Actor[akka://project-manager/user/language-server-registry/language-server-controller-aeda375b-b841-4755-bdad-3b4799c91113#103816318] to Actor[akka://project-manager/user/language-server-registry/language-server-controller-aeda375b-b841-4755-bdad-3b4799c91113/bootloader-language-server-aeda375b-b841-4755-bdad-3b4799c91113#-1528237616] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://project-manager/user/language-server-registry/language-server-controller-aeda375b-b841-4755-bdad-3b4799c91113/bootloader-language-server-aeda375b-b841-4755-bdad-3b4799c91113#-1528237616] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [2023-09-29T10:18:27+02:00] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
```

https://github.com/enso-org/enso/assets/2855109/a099b11f-086d-4afb-95b1-f6317c2300ee

**Comment by PabloBuchu** [comment]
@somebody1234 please fix linter and we should be good to merge

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
