### PR TITLE
Replace special characters while uploading a file

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

Closes: https://github.com/enso-org/cloud-v2/issues/1489

This PR replaces all special characters with `:`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark:

**Comment by PabloBuchu** [comment]
Looks like nothing is being send right now to the backend. Can we rebase on `main` and merge with multipart upload?


https://github.com/user-attachments/assets/92cecd6f-e023-45cb-a735-f4c48f531bc6

**Comment by MrFlashAccount** [comment]
@PabloBuchu rebased over the latest dev

**Comment by PabloBuchu** [comment]
Sorry but file upload is completely broken. Neither drag n drop nor 'import' icon works. No requests are being send to cloud or local fs

**Comment by MrFlashAccount** [comment]
Will take a look, maybe something went wrong after latest merge

**Comment by somebody1234** [comment]
QA :white_check_mark: after fixing bugs

**Pull request merged**
