### PR TITLE
Dashboard improvements (from 24 September 2024 + 30 September 2024)

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/1508
  - :warning: Labels modal - add selection indicator where user can (de)select multiple labels
    - Checkboxes currently still cause the dialog to (incorrectly) close
  - Edit datalink -> select enso secret -> options are too narrow for enso path. Strip enso://Users(Teams), if possible make the options list longer on the left side
    - Added (or rather, re-enabled via CSS) horizontal scroll instead
  - Make Versions, Sessions, Settings as tabs similar to documentation panel in graph editor
  - Edit description in context menu should open asset panel with description input active
  - Edit secret should be moved to asset panel (same like datalink)
  - Dim background when "edit description", "edit secret", or "edit datalink" are clicked/triggered via shortcut to highlight input
  - Hide unused (= no backend support) columns and icons: accessed by projects and accessed data
- *Partial* frontend fixes for https://github.com/enso-org/cloud-v2/issues/1529
  - (1) Fix settings title being horizontally centered and split on multiple lines
  - (2) :x: backend issue
  - (3) :x: out of scope
  - (4) :x: backend issue
  - (5) :x: out of scope
  - (6) :x: out of scope
  - (7) :x: backend issue
  - (8) :x: already fixed in #11126
  - (9) :x: out of scope (potentially requires a way to trigger a tooltip on a disabled button)
  - (10) :x: out of scope
  - (11) :x: out of scope
  - (12) :x: out of scope
  - (13) URL encode `enso://` URLs in "copy as path"
  - (14) Double click on datalink make asset open and close (not sure if this has already been fixed)
  - (15) Clicking anywhere on Asset Panel no longer deselects assets (not sure if this has already been fixed)
  - (16) :x: addressed in #11268
  - (17) Make list of labels in Asset Panel (right sidebar) horizontal instead of (incorrectly) vertical
  - (18) Only show "Billing" settings tab for organization admins
  - Use "workspace" instead of "network" icon for project tabs
- Other fixes:
  - Fix Asset Panel (right sidebar) not being able to be toggled off if it is temporarily open (when triggered from editing description, or editing secret, or editing datalink)
  - Make "cancel" and "reset" buttons default to outline variant, instead of ghost variant
  - Fix style of dropdown
  - Change Datalink editor dialog so that object keys are above inputs, not beside them. This gives inputs much more horizontal space for children of deeply nested objects.

Issues left to fix:
- Checkboxes currently still cause the dialog to (incorrectly) close
- "Edit description" actions etc. do not properly focus inputs

Issues left to do (out of scope):
- Show username of user currently using a project (possibly as tooltip?) if the project is currently disabled.
- Dropdown and autocomplete entries should be in their own dialog, so that they can escape the parent dialog if they are too long

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
@PabloBuchu this should be *mostly* ready for QA, although I'm still debugging something (dialogs still disappearing when checkboxes are being checked) so I haven't actually made sure that everything is (mostly) working yet - I'll probably properly test later so feel free to delay QA

**Comment by PabloBuchu** [comment]
The labels modal. When I hit `+` next to the asset I get list of all labels (with marked checkboxes) thats ok but:
1. When I hit create new labels is being created (✅ ) but it is not being associated to the asset I was editing (🔴 ) and the modal is g
2. Please align colors 
Screenshot 2024-10-04 at 10 40 32
one (🔴 ). The newly created label should be appended to the list and associated with asset.

3. Edit datalink -> Username -> Switch from Text to Enso Secret -> kboom (also no list secrets request is being send)
 Screenshot 2024-10-04 at 10 43 06

4. Asset Panel -> Edit description -> Enter text -> Submit -> Text disapears although after reload all is preserved so the requests is being send properly
5. | Edit description in context menu should open asset panel with description input active
Can we make the input with active cursor?
6. | Edit secret should be moved to asset panel (same like datalink)
Yeah that works. Can we unify the forms? Make it to look the same as datalinks?

**Comment by somebody1234** [comment]
1. done locally
2. done locally
3. will investigate soon
4. will be fixed on next PR
5. done locally
6. done locally (?)  more or less at least

**Comment by somebody1234** [comment]
3: weird, cannot repro?

**Comment by PabloBuchu** [comment]
1. Sorry but can we use just the same styles for the forms in asset panel? now they look completely different
Screenshot 2024-10-07 at 10 07 01
Screenshot 2024-10-07 at 10 07 06
2. Edit secret -> why reset button? (it resets name and name is readonly) `Update` is enough
3. Here is video for `3.` this looks serious:

https://github.com/user-attachments/assets/a56723b4-b74d-426c-a84a-ed807fd4709e

**Comment by somebody1234** [comment]
@PabloBuchu issues should be fixed. the datalink input in the sidebar isn't *perfect*, but there is a follow on branch that should properly fix this stuff

**Comment by PabloBuchu** [comment]
In secret form you renamed `Reset` to `Cancel` but it works the same it clears the name and only way to bring it back is to reload. Lets remove the `Cancel` button completelty (also in the datalink form it does nothing there as well). Else looks good so I will leave ✅ 
Screenshot 2024-10-08 at 12 50 14

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
> clears the name

yeah my bad. it shouldn't clear the name but will probably fix in the next PR then (which already includes various fixes for forms)

**Pull request merged**
