### PR TITLE
Run IDE with Project Manager endpoint instead of Language Server endpoints, when on local backend

### LINKED ISSUE #6756: Cannot rename project
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Inside Enso I cannot rename the project to any name - by entering text in the project name field
image

I can rename it in the dashboard and it carries to the folder name in the projects folder.

### Expected behaviour

I'd like to be able to rename projects.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

2023.5.18 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

### LINKED ISSUE #6804: Remove old "Open Project" view.
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

With the new dashboard, when I open the project list to switch to a different project, it shows up empty:
bug

### Expected behaviour

I expect the project list to be populated with my projects.

### How we can reproduce it?

1. Run Enso with `-feature-preview.new-dashboard`.
2. Open a project.
3. Press `ctrl-o` to open the project switcher.
4. Notice that it's empty.

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

This is a fix for a couple of recent regressions:
- Fixes #6756: Projects couldn't be renamed anymore from within the project view.
- Fixes #6804: One could no longer switch between projects from within the project view.
- It also unblocks the issue with the spinner (that got reverted), but that probably needs some extra attention.

It might be the long-term goal to have different UX solutions to these cases, but this should fix those regressions in the short term at least.

Thanks to @somebody1234 for the in-depth conversation (and the actual code!).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] ~~The documentation has been updated, if necessary.~~
- [ ] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
not much code to review. the `const engineConfig` does look a little funky, but i'm not sure the alternatives are any better:
- `switch (backend.platform)` - this requires `engineConfig` to be declared with an explicit type annotation first, because TypeScript cannot infer things
- inlining the object - a bad idea in general

**Comment by somebody1234** [comment]
crosspost:
It has been brought up that the dashboard does `project/open`, and then the IDE does `project/open` again.
It's possible to work around this on the dashboard side, but I'm not sure whether the added complexity is worth the performance improvements in avoiding opening the same project twice.

I guess it depends on how long this workaround will stick around

**Comment by Frizi** [comment]
QA Status: 🟡 
---
I can create, open and rename projects. I am also able to switch between projects using ctrl+o. The remaining issue is that after changing the project name in project view and going back to the dashboard, the old name is still displayed on the list until I refresh/reopen the application. I don't think that this has been introduced with this changeset though.

**Comment by somebody1234** [comment]
@Frizi the latest commit should fix that

**Comment by Frizi** [comment]
QA status: 🟢 
---
The project name change is now also immediately reflected in the dashboard.

**Pull request merged**
