### PR TITLE
Fix CB discarding changes if pressed Ctrl + Enter too quickly

### LINKED ISSUE #6722: Full screen visualization hindered by "Unsupported Engine version..." message
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The `Unsupported Engine version` or in fact any kind of notification that pops up (like connectivity issues) is blocking the view of the graph and of full screen visualization.
Maybe worse is that it can't be moved or mitigated in any way, sometimes hindering the view of data.

### Expected behaviour

Semi-transparent notification would be sufficient.

### How we can reproduce it?

Start a locally built engine. 

### Screenshots or screencasts

Screenshot from 2023-05-17 11-45-43

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #6733: If user press ctrl+enter too quickly after finishing node edit the last edit is not saved
### Discord username

_No response_

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/6f5ac34c-3b3a-45f5-947e-c0d4f08c9396

### Expected behaviour

The last version of the code on the node should be saved.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

develop 17.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Now, quick typing in component browser and pressing "enter" should not cut off the last part typed. Fixes #6733 

https://github.com/enso-org/enso/assets/3919101/3979ed5a-ba4e-4e25-93e6-672e731b7bd8

On this occasion, also fixed "go-to-dashboard" button and "Unsupported engine version" being over the full-screen visualization. Fixes #6722 

### Important Notes

I did a significant refactoring of Project View:
1. The huge `frp::extend` block was split into multiple `init` methods.
2. Remaining of the "Old searcher" were removed.
3. The "Edited" event from node's input is emitted only when in edit mode (it's consistent with other API terminology, and makes FRP for showing CB much simpler.

The code was _mostly_ moved around, but the check is advised anyway, as there were small changes here and there. 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]

**Comment by Frizi** [comment]
QA report: 🔴
---
1. When entering edit mode on a node containing a type constructor, the component browser incorrectly selects the type itself as an option. Pressing enter then enters into that type, and confirming it again results in an arbitrary other method (not constructor in this case) being selected.

https://github.com/enso-org/enso/assets/919491/aa5ca38c-ef2d-4127-a633-3985dfb8781f

2. When selecting a type suggestion, component browser immediately switches selection to a different entry.

https://github.com/enso-org/enso/assets/919491/6ed67bc9-a28e-4c4e-ab92-f8557cbdea02

**Comment by farmaazon** [comment]
1. It's on develop, but I have a quickfix and try to add it here.
2. It's also on develop. It was partially worked around recently, so after last merge you should not have a problem in _this_ specific scenario. The full fix is tracked by https://github.com/enso-org/enso/issues/6124

**Comment by farmaazon** [comment]
@Frizi fix landed, please check out.

**Comment by Frizi** [comment]
QA Status: 🍌
---

Ctrl+enter works correctly, It will always accept currently written input. The issues mentioned above are now fixed.

There is still an issue related to input lag when simply using `enter`, as the component browser takes a while to respond to the input, and the accepted suggestion is effectively outdated at the time of key press. I'm going to say it is a separate issue, and likely needs further general performance improvements to be adressed properly. Here is how it looks though:

https://github.com/enso-org/enso/assets/919491/e1899661-7780-4e4e-abfa-8ae4dec7fe68

**Pull request merged**
