### PR TITLE
use new icon for adding new nodes

### PR DESCRIPTION
**Pull request by marthasharkey**
new-icon-new-node

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by vitvakatu — APPROVED** [review]
The inconsistency in icon name (`-` vs `_`) is a bit concerning, but it is not the issue with this particular PR.

**Comment by AdRiley** [comment]
Let's fix the name in this PR. Update icons.svg manually and I will fix Figma to match.

**Comment by AdRiley** [comment]
They should be underscores

**Review by AdRiley — APPROVED** [review]

**Review by farmaazon — APPROVED** [review]
What about changing also the icon in Component Browser (from "plus" to this one) @AdRiley @marthasharkey ?

**Comment by AdRiley** [comment]
> What about changing also the icon in Component Browser (from "plus" to this one) @AdRiley @marthasharkey ?

Yes good call. We should do that one too. @marthasharkey Are you OK to include in this MR?

**Pull request merged**
