### PR TITLE
Organization settings page

### PR DESCRIPTION
**Pull request by somebody1234**
:warning: The corresponding backend functionality should be implemented first, before this is merged.

### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/840
  - Add organization page
  - Add wrappers for required API endpoints (get, update, delete org; upload org picture)

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Let's remove "delete this organization" button also there is noticable delay when you go to `organization` tab and wait for organization data.. are we able to smooth it out a bit?

**Comment by somebody1234** [comment]
@PabloBuchu both should now be addressed.

**Comment by PabloBuchu** [comment]
- after I upload an organization picture I still see the grey placeholder
- org data from `organizations/me` is not being properly filled into the form
- 404 on `organizations/me` is blocking the form. if `organizations/me` returns 404 then fine. it means no data was submitted we should still allow for update

**Comment by PabloBuchu** [comment]
here is a repopnse from `organizations/me`
```
{
    "pk": "organization-2cGQ7qsNp28Ci79mjiVoc5pshvk",
    "organization_name": "adsad",
    "email": "pawel.buchowski@gmial.com",
    "website": "https://google.com",
    "address": "asdsa",
    "picture": "https://pb-enso-organizations-pictures.s3.eu-west-1.amazonaws.com/organization-2cGQ7qsNp28Ci79mjiVoc5pshvk/file-2cGUfJopfX9imE86zmKuessh7UT/file-2cGUfJopfX9imE86zmKuessh7UT.png"
}
```

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
