### PR TITLE
"User groups" settings page

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/907
  - Add a settings page for listing groups
  - Add users list with drag-n-drop into user groups
  - Show users below user groups
  - Add delete button for users and user groups

Other changes:
- Add delete button for users on "Members" settings page. Note that it currently does not work as corresponding backend functionality is missing.

### Important Notes
None

### Testing Instructions
Just the new "User Groups" page, and testing deletion of users in the "Members" page

### Screenshots
User groups table:
- The last group has two users, shown as indented rows.
- Both users in the "Users" table below (to the right, if on a wider screen) are selected. These rows have the same styling as in the rest of the tables when not selected.
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Sorry we made you waiting with this. 

Member Roles
1. No `Roles` but `User Groups`
2. On group row make the same `x` as with the invitation emails (on hover). delete user group
```
DELETE /usergroups/usergrup-12313/
```
3. 2nd table with users list (in format `username (user email)`
4. Drag n drop user -> group to add user to that group. 
```
PUT /users/{user_id}/usergroups {userGroups: [ids]}
```
5. Users being appended to the list below the group. You can indent this sublist a bit

Members

1. Add small `x` on the user same on hover

**Comment by somebody1234** [comment]
member roles:
1. done
2. todo
3. done, but i've decided to just use the same table as we are using on the members page instead. so two columns
4. done, but there are minor style issues when a row for a usergroup is being hovered over, when dragging a user over the usergroup
5. *theoretically* done, but i'm not able to test

members:
1. todo, just like (2) on member roles. i think though, that we shouldn't be using the same `x` (mostly because table rows are a different size, partly because table rows can be very wide. i think it would make sense to have a "floating" (and larger) `(x)` to the left of the row. i imagine the appearance would be similar to the `(+)` buttons for the "shared with" and "labels" rows

**Comment by PabloBuchu** [comment]
So managing users and groups is broken. The groups disappear and it looks like user can be in only one group:

https://github.com/enso-org/enso/assets/2855109/155c2fa0-8497-4b9c-bb48-62f50c714f24


You can use my environment and user to reproduce problems
```
pawel.buchowski@enso.org
Enso12#$
```
Lemme know if BE fixes are needed

**Comment by PabloBuchu** [comment]
btw I fixed issue when you try to remove last usergroup from a user

**Comment by somebody1234** [comment]
oops. should be fixed, plus some additional fixes

**Comment by MrFlashAccount** [comment]
@somebody1234 found one small thing: If a user is on a free tier(or maybe not enabled?) the UI struggles trying to constantly refetch the data.

I think we should hide the tab for those accounts or display an error instead of a loader. 

https://github.com/enso-org/enso/assets/61194245/c82d0fa2-27dc-40d2-884b-f4eea2955272

---

Btw, I'm not sure how old this PR is, but I think it is worth considering: Recently we added `react-query` which is the recommended way to fetch data (or work with any async flow). I think if we rewrite this PR to using `react-query` we'll fix the double fetching issues and significantly improve readability without losing any features(optimistic updates, loading states, etc)

CleanShot 2024-04-29 at 15 55 46@2x

Also worth noting: showing 2 loaders instead of one is a bad ux practice. We should avoid it as much as possible

**Comment by somebody1234** [comment]
> showing 2 loaders instead of one is a bad ux practice

ehh, not too sure about this one. ideally we'd be using skeletons, and showing both skeletons is for sure not a bad practice.

but yeah it's true that a bunch of the tabs should be hidden depending on tier (and permissions, although i'm not sure whether we can restrict access based on permissions yet)

**Comment by MrFlashAccount** [comment]
@somebody1234 skeletons are okay, I agree(bc people consider them as a single loader).

**Comment by MrFlashAccount** [comment]
CleanShot 2024-04-29 at 16 08 00@2x

Can we add a `cursor: grab` + `cursor: grabbing` while dragging here?

**Comment by MrFlashAccount** [comment]
CleanShot 2024-04-29 at 16 10 20@2x

By dragging back and forth between groups, I somehow got into a state, where both groups had the same user. Is it expected?

And I can't remove myself from a group anymore 🫣 


https://github.com/enso-org/enso/assets/61194245/16d1e31c-fe1c-4e09-b4be-f671b5217c7c

@somebody1234 I think we should refetch the backend data after the mutation and do not rely only on the `optimistic state`

**Comment by somebody1234** [comment]
re: 2 loaders - perhaps not ideal, but i prefer two loaders rather than one fullscreen loader that would have to obscure the entire screen (otherwise it looks like it's a loader for only one of the tables). it's not ideal but it's probably the least bad solution here, for consistency if nothing else.

re: dragging back and forth between groups
yes, groups can have multiple users. but i don't think users in the "groups" table should be draggable. if they are, it's probably a mistake

**Comment by MrFlashAccount** [comment]
@somebody1234 in this situation, show up a single loader is better, since we need to load both tables to operate groups.

re: dragging back and forth between groups
But is it allowed for a user to be in multiple groups?

**Comment by somebody1234** [comment]
> But is it allowed for a user to be in multiple groups?

yes - imagine e.g. having user groups on github for dashboard and cloud backend. it's possible that someone would want to (at least temporarily) be more than one of the groups, and it also makes more sense to configure those groups separately

**Comment by MrFlashAccount** [comment]
When I drag a user over a group, nothing happens (maybe we can show a notification that a user's already in this group?).
But when I drag a user over a user - I get an error:

https://github.com/enso-org/enso/assets/61194245/c1cc2ef1-1f98-44a3-a4eb-e536b233ec88

Imo, this should behave the same way as dragging over a group.

**Comment by somebody1234** [comment]
>  I think we should refetch the backend data after the mutation and do not rely only on the optimistic state

we don't rely on optimistic state, we do rollbacks if a request fails. we *could* do a full query but i'm not convinced it's a good idea because we'd potentially be scanning the entire table for the full list of users in a group (very expensive!)

> When I drag a user over a group they are already in, nothing happens

yeah, dropping a user on that group should probably be disabled

**Comment by MrFlashAccount** [comment]
> we don't rely on optimistic state

@somebody1234 but for some reason I'm struggling to work with the table because I need to reload the page each time I make changes, because I can't _trust_ `optimistic updates`.

here are few examples:

1. I delete a user from both groups, but after reload the user is still present in both groups

https://github.com/enso-org/enso/assets/61194245/57755f76-0d1f-4006-93f0-b9b6138db46a

2.  I add the same user into both groups, user jumps from the first group to the second one. I reload the page, user is present in both groups.

https://github.com/enso-org/enso/assets/61194245/c00a4624-2063-4df8-aee2-724d5b691f01

**Comment by somebody1234** [comment]
sure, but if the state is inconsistent between backend and frontend, it's because *the code is bugged*. it's not an inherent flaw of optimistic updates

**Comment by MrFlashAccount** [comment]
CleanShot 2024-04-29 at 16 37 22@2x

Small, but worth noting: we should show an error message on why we block the submit button(a group with the same name is already created). Imagine an enterprise with 20+ groups and 100+ users, someone tries to create a new group with an existing name and gets frustrated when sees a disabled button without any indication.

**Comment by MrFlashAccount** [comment]
Imho, the highlighting shouldn't "jump" when I drag a user over a group


https://github.com/enso-org/enso/assets/61194245/357c9c68-ecce-405a-bf3e-543d5129f73b

**Comment by MrFlashAccount** [comment]
CleanShot 2024-04-29 at 16 44 04@2x
Can we make the table wider?
Also: me might want to truncate long names(see screenshot)

**Comment by MrFlashAccount** [comment]
> sure, but if the state is inconsistent between backend and frontend, it's because the code is bugged. it's not an inherent flaw of optimistic updates

Maybe rewriting to react-query will help? 😄

**Comment by somebody1234** [comment]
> Maybe rewriting to react-query will help?

i don't think so. we use rollback functions rather than (incorrectly) restoring old state, which means if we switch to react-query...

... we need to pass to pass the rollback functions to react-query verbatim in the first place. so we will encounter the exact same class of bugs.

**Comment by MrFlashAccount** [comment]
@somebody1234  Sorry for my review to be messy 🥲

**Comment by somebody1234** [comment]
> user is on a free tier(or maybe not enabled?) the UI struggles trying to constantly refetch the data

should be fixed now, will test later

> double fetching issues

not an issue

> significantly improve readability

i'm not 100% sure this is true

> showing 2 loaders instead of one is a bad ux practice

[citation-needed], i'm not quite sure how two skeletons are considered as a single loader (especially when they are positioned side by side instead of stacked vertically, and loaded at different times)

> `cursor: grab`

done

> `cursor: grabbing` while dragging

implicitly happens becaus of OS-native drag handling

> both groups had the same user. is it expected?

yes, it is intentional

> can't remove myself from a group anymore

seems like a backend issue (see below)

>  I think we should refetch the backend data after the mutation instead of relying on optimistic state

as mentioned elsewhere, if optimistic state is wrong then that is a bug. doing full queries is potentially orders of magnitude more expensive as many such requests may have to scan through all rows

> delete a user from both groups, but after reload the user is still present in both groups

seems like a backend issue (user is not removed from usergroups that are no longer present in the "set usergroups" request). @PabloBuchu can you confirm?

> user jumps from the first group to the second one

will investigate

> When I drag a user over a group [that they are already in], nothing happens

:warning: we explicitly don't want toast notifications for successful actions, it's distracting. however, we can't disable the action, not when we can't access the drag payload...

> But when I drag a user over a user - I get an error. Imo, this should behave the same way as dragging over a group.

drop action has been disabled for those.

> can't trust optimistic updates

as mentioned above if they aren't 100% accurate then that's a bug. backend error/response should tell us all we need to know about how the state changed

> should show an error message on why the submit button is blocked

implemented. wasted a bunch of time wondering why native validation isn't working with realtime validation... turns out i was looking in the wrong section and native validation doesn't actually work for setting validation messages :(

> highlighting shouldn't "jump"

yeah this is because react-aria-components is weird. fixed (with minor changes on all other tables with alternating colors)

> Can we make the table wider?

fixed by using `whitespace-nowrap`. intentionally avoided truncation, horizontal scrolling is fine imo, at least for now

> Maybe rewriting to react-query will help

as mentioned above the functions we need (either to rollback, or to store temporary state somewhere) are the same in either case. so i don't think react-query makes things *simpler* here.

**Comment by MrFlashAccount** [comment]
> fixed by using whitespace-nowrap. intentionally avoided truncation, horizontal scrolling is fine imo, at least for now

No, horizontal scrolling here is not okay.

**Comment by somebody1234** [comment]
oh? any other alternatives? i think truncation is even worse than horizontal scrolling, fwiw... you should at least be able to see the full name

**Comment by MrFlashAccount** [comment]
> oh? any other alternatives? i think truncation is even worse than horizontal scrolling, fwiw... you should at least be able to see the full name

We can show a tooltip on hover with the full name(or put the name into the `title` prop) as a workaround for now. 
As a part of the billing screen, I'm working on a dedicated `<Text />` component that will have an `ellipsis` prop and will display a tooltip on hover if text truncates. If you want to, I can show you a work-in-progress prototype tomorrow

**Comment by somebody1234** [comment]
should be more or less ready for re-QA?

**Comment by somebody1234** [comment]
wait no i think there's a crash that i forgot about?

**Comment by MrFlashAccount** [comment]
QA iteration 2 Failed ⛔️

You did a great job fixing the issues from the latest QA. There I provided a list of thing we should fix before merging the PR:

1. If I add a user to a group, and then add the same user to another group -> the user jumps from the first group to the second group.
2. I think we should preserve the delete icon on the right side of the group name/user. Clicking the right button each time I want to remove a user/group is annoying.
3. **Question** Do we treat groups 'Test' and 'test' as the groups with the same name?
4. I can create group 'test ' with existing 'test' group (we should truncate the names)
5. Button 'create new group' shouldn't scroll with groups (same for the title)
CleanShot 2024-05-06 at 10 16 02@2x
6. We need a bottom margin at the end of the groups list to show that there's noting below(I'd suggest mb-16)
7. Stripped Text should end with `...`
CleanShot 2024-05-06 at 10 33 59@2x

**Comment by somebody1234** [comment]
1. (done) yeah i kinda forgot about this one because removing users from groups is still broken on the backend i think? which makes it a bit more difficult to debug... but not super hard so i'll take a look at it after addressing everything else
2. (done) yeah makes sense. tbh the main reason it's gone is that it's placed past the right edge of the `overflow` container...
    - for now i'll just move it left so that it no longer gets clipped into non-existence
3. (done) i guess we should disallow it. added to backend issue mentioned in part (4)
4. (done) opened issue for backend as well:
    - https://github.com/enso-org/cloud-v2/issues/1197
5. (done)
6. (done) mb-16 is a lot! for now i've decided to use `mb-4 lg:mb-8`. that said... we're supposed to be using a shadow on the bottom to indicate if it is still scrollable
    - edit: replaced with shadow. it might be a bit *too* hard to see though...
7. (idk?) yeah this is mainly an issue with CSS... i did try getting it to work for a long while but had no luck. maybe that was only an issue when i was using `aria.Button` as a workaround to get the tooltips to trigger.
    - upon further testing it seems like using ellipsis still breaks tooltips for some reason.

**Comment by MrFlashAccount** [comment]
> edit: replaced with shadow. it might be a bit too hard to see though...

Yea shadow is great, and together with margins should be an awesome solution

**Comment by MrFlashAccount** [comment]
> upon further testing it seems like using ellipsis still breaks tooltips for some reason.

I haven't seen your solution for tooltips yet, but I assume it's because they are inside the element with ellipsis applied. Moving it away from the container should fix the issue.

**Comment by somebody1234** [comment]
> together with margins should be an awesome solution

note that i've more or less removed margins for now.
pushed changes if you want to test (every point other than (7) should be addressed now).
i'm not *against* margins, but we do need to be careful that it doesn't make spacing look funky. also note that the scrollbar will extend into the margins as well, which (imo) looks more like a bug than a feature

**Comment by somebody1234** [comment]
still no clue why point 7 is broken unfortunately

**Comment by MrFlashAccount** [comment]
> still no clue why point 7 is broken unfortunately


I did a fix in your branch, now it should be ok

**Comment by somebody1234** [comment]
@MrFlashAccount doesn't work unfortunately. i've tried that before, and just tested it out on the current commit.
the tooltip is broken now, *and* the formatting too:
image

(no tooltip + blank line)

**Comment by MrFlashAccount** [comment]
QA ✅

Nice work, @somebody1234 !

**Review by MrFlashAccount — APPROVED** [review]

**Pull request merged**
