### PR TITLE
Correct expression updates of partially applied constructors

### LINKED ISSUE #6903: Atom constructor is using two function calls
Consider the example

```py
type T
    A x y

main =
    x = T.A 1 2
```

The `T.A 1 2` expression is  executed in two steps:
- Unresolved symbol `A` is resolved to a method `T.A` (method `A` with a self parameter `T`) https://github.com/enso-org/enso/blob/ab159238ddb27a3a2d1ea228b2dd23a4e19694f6/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java#L176-L185
- Method `T.A` then returns a function with two arguments `x` and `y` that constructs the `A` instance https://github.com/enso-org/enso/blob/ab159238ddb27a3a2d1ea228b2dd23a4e19694f6/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java#L162-L173

## Issue

When instrumented, the `T.A 1 2` expression returns the underlying method call `A self`. Instead, we want to report a method `A x y` as it looks from the user (and the suggestion database) perspective.

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #6903

Works this way:
- Detect the call to the constructor on function enter
- On the expression return, check if it was a partially applied constructor call. Then build the function info from the resulting function

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by JaroslavTulach — COMMENTED** [review]
As [written here](https://github.com/enso-org/enso/issues/6903#issuecomment-1572850032):

I believe we are trying to tackle the problem from a wrong angle. What's the goal? _When there is a partially applied function, then we want to know what arguments have been applied_. That is not information about "a call" that has happened, but about a "future call" - we have a function value and the IDE needs to know what to do with it.

That means (in my opinion) that [ProgramExecutionSupport.scala](https://github.com/enso-org/enso/blob/03371803849aa44d267856f3c6b828f97e602e7a/engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala#L386) needs to do following when composing `sendExpressionUpdate`:
- when the `value.getType` is `Standard.Builtins.Main.Function`
- accompany the information with a `MethodPointer` to the function definition
- use `(value.value : runtime.Function).getSchema()` to obtain `hasPreApplied` array and send it to the IDE somehow

I don't think the `IdExecutionInstrument` shall differentiate between constructors and other executables. The solution presented in this PR continues to push the solution in the **wrong direction** - at least according to my opinion. Or I am completely confused. In any case I cannot approve it.

**Comment by 4e6** [comment]
- If we just detect that the expression returns a function (on the expression return), we don't have enough information to build a method pointer from it. It has to be captured (and stored) before (on the function call return)
- Expression update contains information about the computed expression, not the expression that will be computed. 

```py
main =
    x1 = func1 1
    x1

func1 x = func2 x
func2 x y z = x + y + z
```

Following your logic, the expression update of the `func1 1` will return arguments of the `func2` call.

**Review by JaroslavTulach — CHANGES_REQUESTED** [review]
@Frizi [wrote](https://github.com/orgs/enso-org/discussions/6762#discussioncomment-6090661):

>   If you are able to ... fill methodPointer (or a function schema for that matter) before actual execution, the IDE should be ready to accept it

Pawel also noted that the current implementation is a significant source of buggy behavior:

> this behavior is also a cause of some issues during graph reevaluation, where new Pending updates are setting methodPointers to null, causing widgets and arguments to disappear for a moment

Based on that I _request changes_. We don't want any more workarounds in `IdExecutionInstrument` - we want to make sure that [ProgramExecutionSupport.sendExecutionUpdates sends info about `Function` values](https://github.com/enso-org/enso/pull/6939#pullrequestreview-1458985852) to the IDE. Tracked as
- #6957

**Comment by 4e6** [comment]
Pawel is talking about sending the method pointers in the compile time when the Pending updates are sent. It has nothing to do with this change. 

Regarding his idea. The engine doesn't have sophisticated enough static analysis to do that right now. What IDE can do is preserve the information about the method pointer when it receives the Pending update instead of erasing all the information about the node. I assume erasing only the type information should be enough to gray out the nodes

**Comment by 4e6** [comment]
Superseded by #6957

**Comment by JaroslavTulach** [comment]
> Pawel is talking about sending the method pointers in the compile time when the Pending updates are sent. 
> It has nothing to do with this change.

Yeah, now I get it too. Enso doesn't have a static type checker. The only thing we can do is to deliver the information during runtime. We just have to make sure we deliver the right information as #6957 suggests.

**Pull request closed without merging**
