### PR TITLE
Fix file associations on Windows + opening project bug

### LINKED ISSUE #10983: WIndows Installer not registering the file types

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

* Fixes [#10983](https://github.com/enso-org/enso/issues/10983) The `ext` field was not set according to the documentation in rust
* Also discovered a regression in opening project by passing argument/clicking the file: we store the file location as `file://` URL, but without caution, it made a havoc with windows paths.

### Important Notes

- [x] **Need to confirm that everything works on macOS** (installation with file associations + opening project when process is running and when not)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- ~~[ ] Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by vitvakatu** [comment]
Working on MacOS:
- Opening `.enso-project` files while running/not running the app
- Opening `.enso` files while running/not running the app

Although I might note a small detail: it is impossible to open multiple projects simultaneously when clicking files in Finder – the latest project always takes precedence and the previous one will be closed. It is the issue on develop as well, though, so not to block this PR.

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark:

**Comment by somebody1234** [comment]
@vitvakatu i think being able to only open a single project is intentional, but tbh I'm not 100% sure it is intended behavior for the local backend. @jdunkerley can you confirm or deny?

**Comment by jdunkerley** [comment]
Yes currently we only support opening one project at a time. We will improve that later.

**Review by MrFlashAccount — APPROVED** [review]

**Pull request merged**
