### PR TITLE
Update Dashboard to latest Figma design

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Update Dashboard to latest Figma design
  - Remove Home icon from top left. Clicking on the *currently active tab* (the one with its icon at full opacity) now navigates to the Home page.

- Other changes
  - Layout pages side by side (Home, Drive, Editor, Settings)
  - Animate between pages

### Important Notes
None

### Screencast

https://github.com/enso-org/enso/assets/4046547/8163af82-0a55-4c99-9b5f-87360cf30797

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]
Approving GUI changes (if they work).

**Comment by somebody1234** [comment]
yeah i've done *basic* testing on GUI but i suspect this should really be properly tested

**Comment by jdunkerley** [comment]
@somebody1234 can we have screenshots and a rough description of what was changed please?

**Comment by somebody1234** [comment]
@jdunkerley done.

**Comment by jdunkerley** [comment]
Thanks for the details - please hold off on merging this for now. The 115 design is still very much a work-in-progress and we need to think a little more before removing home button.

**Comment by somebody1234** [comment]
i think we *could* still merge this in with just the animations between pages - but not 100% sure that's something we want

**Comment by somebody1234** [comment]
obsoleted by newer design.

**Pull request closed without merging**
