### PR TITLE
Improve mouse and keyboard UX

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/914
  - Add selection brush for selecting multiple assets using mouse
    - Port selection brush over from GUI2
    - Support <kbd>Ctrl</kbd>-select to select multiple ranges
  - Add various actions when *exactly one* asset is selected:
    - <kbd>Enter</kbd> for various assets to trigger their double-click actions
      - Projects are opened
      - Directories are toggled open/closed
      - Secrets show the "upsert secret modal"
    - <kbd>ArrowLeft</kbd> now collapses the selected folder
    - <kbd>ArrowRight</kbd> now expands the selected folder
    - <kbd>ArrowUp</kbd> and <kbd>ArrowDown</kbd> change the selected asset to the previous/next asset
      - The newly selected asset (technically: any asset that is the only selected asset, whether this is a result of a drag, mouse click, or keypress) is automatically smoothly scrolled to.
  - Improvements to the search bar
    - <kbd>Escape</kbd> cancels tabbing through suggestions (and discards the selected suggestion)
    - <kbd>ArrowUp</kbd> and <kbd>ArrowDown</kbd> behave like <kbd>Shift</kbd>+<kbd>Tab</kbd> and <kbd>Tab</kbd> to move to the previous/next suggestion respectively
  - <kbd>Shift</kbd>+<kbd>ArrowUp</kbd> and <kbd>Shift</kbd>+<kbd>ArrowDown</kbd> to select multiple assets using the keyboard
  - <kbd>Ctrl</kbd>+<kbd>Space</kbd> to toggle assets using the keyboard
  - <kbd>Escape</kbd> to deselect all assets
  - Add CSS-only focus ring to highlight most recently selected item, but only when navigating via keyboard
  - Enter and double-click to temporarily open the sidebar to edit a Data Link

Optional features that have not yet been implemented:
- Move the "update secret" modal to the sidebar as well

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
| Ctrl+Space to toggle assets using the keyboard

this seems to have no effect on mac. cmd + space opens system `spotlight search` maybe this is why

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
makes sense. we should probably just copy macOS' equivalent shortcut to Ctrl+Space?

**Comment by PabloBuchu** [comment]
Apart from above and merge conflitcs looks good. Lemme know if we want to fix this in separate PR or not

**Comment by somebody1234** [comment]
yeah, probably doesn't make sense to block this PR

**Pull request merged**
