### PR TITLE
Fix tooltip display and other refinements across dashboard

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
might as well remove the closeButton prop from Dialog as well

also just a heads up that the start modal intentionally didn't have a title because it doesn't have one on the figma design (nor does it need one as it already has a much bigger title)

**Comment by MrFlashAccount** [comment]
In Figma, the start screen seems more like a separate screen 

CleanShot 2024-06-16 at 12 54 05@2x

**Comment by MrFlashAccount** [comment]
> might as well remove the closeButton prop from Dialog as well

Let's leave it for now, maybe it makes sense but requires additional refinement

**Comment by somebody1234** [comment]
note that that's an outdated design - if it were its own page it would not be accessible because it no longer has its own tab. the correct design is present on the "drive" page, as "start with template pop up"

**Comment by somebody1234** [comment]
you'll need to clone the design to be able to edit the visibility though

**Comment by MrFlashAccount** [comment]
> you'll need to clone the design to be able to edit the visibility though

Oh god. 

---

My main disagreement with the floating button located this way is that it messes up the content below: 

https://github.com/enso-org/enso/assets/61194245/cc55faa6-d433-4ad0-aeef-84329364b283

And adding a title looks the best at the moment. Designers make pictures, we make interfaces. We must think about how the design works and adapt it.

**Comment by somebody1234** [comment]
it's trivial to solve by adding a title bar but leaving it blank and without a border in between. and again, having a title makes zero sense here as there is already a larger title.

(another option is to add a clip path that omits just the window buttons but I'm not sure whether that would look good)

**Comment by MrFlashAccount** [comment]
Empty title bar looks ugly.

**Comment by MrFlashAccount** [comment]
https://github.com/enso-org/enso/assets/61194245/96c49396-53d4-4acf-bc99-42ba117b5cbb

Now looks better

**Pull request merged**
