### PR TITLE
Add dashboard skeleton

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Removes placeholder dashboard in preparation for the actual dashboard implementation.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
force-pushing as this is a *very* minimal PR, and no reviews have been done yet.

**Comment by PabloBuchu** [comment]
@somebody1234 whats the status here? can we update this so I can review?

**Comment by somebody1234** [comment]
@PabloBuchu this should be a relatively minor change, it *should* just be merging backend + frontend endpoints, then replacing the placeholder dashboard for an empty one with placeholder elements

**Comment by somebody1234** [comment]
there are a lot of of PRs open, i could combine the backend + frontend endpoints PRs into this one to reduce clutter?

**Comment by PabloBuchu** [comment]
@somebody1234 are we ready to open this for review?

**Comment by somebody1234** [comment]
(merged because diff was showing changes from another PR. this should be much more manageable now.)

**Comment by somebody1234** [comment]
hey @wdanilo - just want to confirm that this PR shouldn't require a changelog, as it would fall under the "Added boilerplate React app for authorization via Cognito+AWS Amplify" item?
(this does change the dashboard, however it is still a placeholder, same as it was before this PR)

i think the future PRs (e.g. the one adding table view) would need a separate changelog item (or multiple) - it'd be great to confirm this as well

**Comment by PabloBuchu** [comment]
@kazcw or @MichaelMauderer can I get 👍  on this small one? most of the changes was merged in previous PRs

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
