### PR TITLE
Update top-bar styles and implement changePassword feature.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Recreate #5857 and #6064. Implementation by @Nctdt.

- Adds dashboard <-> project switcher
- Adds search input (does nothing for now)
- Adds help button - currently links to the official Discord server
- Adds user account menu containing:
  - Username
  - User profile (does nothing for now)
  - Change password button
  - Sign out button
- Adds modal to change password

### Important Notes
N/A

### Screenshots
image
image
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
QA results from previous PR (quoted):
- changing password seems to error with message: "Access Token does not have required scopes" and __type: "NotAuthorizedException". this might be an error with ~~backend~~ aws configuration though

**Comment by somebody1234** [comment]
to do: consider removing arbitrary tailwind values `propname-[custom-value]` syntax in preference of extending the tailwind config.

**Comment by somebody1234** [comment]
This one is technically no longer blocked, however I think it should wait until #6015 is reviewed + merged, as that PR introduces custom tailwind configuration, which will greatly simplify the HTML here

**Comment by PabloBuchu** [comment]
@somebody1234 can we close the password reset modal after success? also please apply the bugfix for flags here as well. 

QA:
- build & run: 🟢 
- ide watch 🟢 
- gui watch 🟢  

@wdanilo can you do a code review?

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
@PabloBuchu bugfix for flags should be merged in now, and the modal should be closed now. worth noting that i am still getting the error of "access token does not have required scopes".
here i'm closing the modal after success as requested, however i think for most of the other modals (for the upcoming interactivity PR) they are closed on submit - should those be changed to close only on success?

(i think the reasoning for closing on submit was to prevent submitting a form twice - however we can very easily prevent that by debouncing instead)

**Review by PabloBuchu — APPROVED** [review]

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
