### PR TITLE
Project Description/Settings sidebar

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/629
  - Project Description/Settings sidebar

### Important Notes
:warning: This is blocked by backend support for asset descriptions.

When the sidebar is opening, there is one jumpy animation:
- The search bar switches from being centered in the screen, to having an equal gap between itself and its siblings

### Screenshots

To be added

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
closing for now. it's getting out of date, plus blocked on backend functionality that is (for now) lower priority

**Comment by PabloBuchu** [comment]
@somebody1234 can we fix merge conflicts and merge this?

**Comment by somebody1234** [comment]
@PabloBuchu merge conflicts fixed.

**Comment by PabloBuchu** [comment]
@indiv0 some regression? I think toggle sidebar is disabled now

**Comment by somebody1234** [comment]
@PabloBuchu was working for me when i tested - did i miss an interaction? settings button in the top right works for both enabling and disabling the sidebar, deselecting an asset intentionally doesn't disable the sidebar... although to be fair i don't see much of an effect on convenience either way so it would definitely be easy enough to change the behavior

**Comment by PabloBuchu** [comment]
I guess it was late for me... merging

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
