### PR TITLE
Add comment, warning, error icons.

### PR DESCRIPTION
**Pull request by jdunkerley**
### Pull Request Description

Add some state icons.
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by kazcw — APPROVED** [review]

**Comment by somebody1234** [comment]
wait, we already an icon for trash (well, actually we have two... somehow *both* of them are currently used by the dashboard)

**Comment by jdunkerley** [comment]
> wait, we already an icon for trash (well, actually we have two... somehow _both_ of them are currently used by the dashboard)

so I see - was asked for one so added
will remove.

**Review by farmaazon — CHANGES_REQUESTED** [review]
I don't like that icons have defined colors. All our icons so far had currentColor, which was specified in usage place.

This way, for example, error/warning icon could be used to represent a component (Warning.attach, or Panic.catch come to mind), and then it will match the group color. Or the error icon could change color depending if it's a Dataflow error or a Panic.

AFAIK, our tool turns black to currentColor, so we can make those icons black in figma, and set proper colors in our app.

**Comment by jdunkerley** [comment]
> I don't like that icons have defined colors. All our icons so far had currentColor, which was specified in usage place.
> 
> This way, for example, error/warning icon could be used to represent a component (Warning.attach, or Panic.catch come to mind), and then it will match the group color. Or the error icon could change color depending if it's a Dataflow error or a Panic.
> 
> AFAIK, our tool turns black to currentColor, so we can make those icons black in figma, and set proper colors in our app.

Ok have made them currentColor
Please use FBBC05 for warning (orange) and EA4335 for error (red).

Have also added a comment icon for that story.

**Review by farmaazon — APPROVED** [review]

**Pull request merged**
