### PR TITLE
Fix dashboard issues (part 2)

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fixes [cloud-v2/#411](https://github.com/enso-org/cloud-v2/issues/411)
- Fixes [cloud-v2/#412](https://github.com/enso-org/cloud-v2/issues/412)
- Fixes [cloud-v2/#414](https://github.com/enso-org/cloud-v2/issues/414)
- Fixes [cloud-v2/#415](https://github.com/enso-org/cloud-v2/issues/415)
- Fixes [cloud-v2/#417](https://github.com/enso-org/cloud-v2/issues/417)

### Screencasts
411: (project list no longer flickers)

https://user-images.githubusercontent.com/4046547/235684486-a006ccc1-5007-420d-9909-3eb39e9b9887.mp4

412:

https://user-images.githubusercontent.com/4046547/235686524-117cddf5-d2fe-4b56-b47e-a79ac3706bb5.mp4

414:

https://user-images.githubusercontent.com/4046547/235706192-ae286305-35db-4e26-aab9-23e42d95afde.mp4

415:

https://user-images.githubusercontent.com/4046547/235687658-978525f1-6165-40cc-ab8c-84fd4e6be3d8.mp4

417:

https://user-images.githubusercontent.com/4046547/236173884-d28c6bfa-726f-487b-b4a6-ea21a3bc72ed.mp4

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
note: cloud/# 413 not fixed here as it will be fixed in #6507

**Comment by somebody1234** [comment]
more notes:
- this points to the other fix PR. the commits can be cherry-picked onto the main branch if desired.
- cloud-v2/# 416 is not fixed yet

**Comment by somebody1234** [comment]
force-pushed to clean up history (and list of files changed)

**Comment by somebody1234** [comment]
base changed to develop to speed things up

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
