### PR TITLE
Change folder icon to arrow on hover

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/628
  - Change folder icon to arrow on hover

### Important Notes
The arrow used is the same one used in the chat side panel.

### Screencast

[screen-recorder-mon-aug-28-2023-23-38-41.webm](https://github.com/enso-org/enso/assets/4046547/927dcadc-010e-40f3-95c4-6998457a7e86)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
I think we need to adjust the hit box a bit. I am constantly opening rename input rather than toggle directory.. also we should change it to toggle on one click cause now it works on double on my mac. Also many consecutive hits in arrow fails doing nothing 

https://github.com/enso-org/enso/assets/2855109/5c6752b9-52d2-4256-a2ac-118d1a6693e5

**Comment by somebody1234** [comment]
ah whoops, yeah currently there's no special event handling for the arrow. i'll add a click event handler to the arrow and see if it's any better

**Comment by somebody1234** [comment]
@PabloBuchu added a click event handler. notes:

- the arrow takes up the full 16x16 box, so the same as the folder. it just happens that that's how the arrow svg was like already. so the hitboxes should be fine, i think
- every click toggles the directory - there is no double click handler anymore. i think this should be fine though

**Comment by somebody1234** [comment]
looking at the original issue... i was thinking maybe rows should animate height from 0 to full as they appear/disappear... but i guess it's out of scope of this PR either way

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
