### PR TITLE
Fix z-index of top bar

### LINKED ISSUE #7536: Top bar icons are visible over full screen visualizations
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

image

User can not interact with the visualization or close it if they accidentally clicked on one of the buttons.

### Expected behaviour

Top bar icons should not be on the top of full screen visualization

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

nightly 09.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes #7536
  - Top bar is now below fullscreen visualizations

Other changes:
- Fully hides mouse cursor in editor view

### Important Notes
There should be basically no logic changes - check the code to be extra sure.
The main things that should be tested are:
- cursor should be hidden on top bar in the editor, and visible when not in the editor
- cursor should be visible in the "change password" modal

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by vitvakatu** [comment]
QA Report: 🟡 

Mainly fine, though the cursor is less visible now when hovering over the buttons of the top bar. Also, I spotted weird flickering of the system cursor when hovering the dashboard button (it doesn't seem to happen with other buttons):


https://github.com/enso-org/enso/assets/6566674/15e6b308-aa59-4ab6-89f2-5e7472bb2a39

**Comment by somebody1234** [comment]
@vitvakatu re: the cursor flickering, see this https://github.com/enso-org/enso/pull/7488#issuecomment-1665568168

i think it's the same issue as before so at the very least it shouldn't be a regression...

unfortunately i'm not sure if it's possible to solve purely on the React side

**Comment by vitvakatu** [comment]
@somebody1234 I see. We need to show the system cursor over the documentation panel (and over visualizations), so removing the function from the Rust side is not an option.

But I don't understand who sets `cursor: auto` you mentioned here: https://github.com/enso-org/enso/pull/7488#issuecomment-1665552839 IDE shouldn't do that when hovering the top bar.

**Comment by somebody1234** [comment]
@vitvakatu the top bar is currently still in the normal dashboard section of the DOM tree, and so when the cursor moves to/from the React top bar, it fires the `mouseleave` and `mouseenter` events of the scene root (?)

**Comment by somebody1234** [comment]
one potential fix would be to debug why the change to `cursor: none` has a delay of one frame tbh... not sure whether the change is being delayed by a `setTimeout(, 0)` or whether maybe it's just a limitation of wasm

**Comment by somebody1234** [comment]
another fix would be moving the top bar (via a React portal) to `#root`, while the editor is open

**Comment by somebody1234** [comment]
upon further testing that doesn't work; it needs to be a child of `#root > .scene` instead, and that's difficult as it does not exist until the editor is opened.

so @vitvakatu i think it's ready for re-testing

**Comment by vitvakatu** [comment]
> one potential fix would be to debug why the change to cursor: none has a delay of one frame tbh... not sure whether the change is being delayed by a setTimeout(, 0) or whether maybe it's just a limitation of wasm

This is most likely caused by our implementation of hover events, and we can't fix that. There is some lag between hovering and receiving information about it in the ensogl. 

I just checked https://github.com/enso-org/enso/pull/7537/commits/c422bcda8cea628c1f6aa0a199478c6de0d136c1, and it seems to be working perfectly fine, the system cursor is even visible inside the IDE, which is great for UX.

Testing https://github.com/enso-org/enso/pull/7537/commits/075583944db071c0853ed571bb6af5dc16b477c8, it still has this issue with mouse flickering, I don't see other changes.

**Comment by somebody1234** [comment]
@vitvakatu my bad, got the css precedences mixed up. new commit should fix this - the flickering is technically still there, as it was on https://github.com/enso-org/enso/commit/c422bcda8cea628c1f6aa0a199478c6de0d136c1. i don't think the react portal actually helps, you can still see that the style on `document.body` changes between `cursor: auto` and `cursor: none` - it's just that, because the cursor is already visible, being one frame late doesn't matter

**Comment by vitvakatu** [comment]
QA passed 🍏

**Comment by somebody1234** [comment]
@PabloBuchu @indiv0 code review needed here too btw

**Comment by sylwiabr** [comment]
@indiv0 please review - it is a very annoying bug and we should merge it ASAP

**Review by indiv0 — APPROVED** [review]
LGTM

**Comment by indiv0** [comment]
@somebody1234 looks like there's an issue w/ the prettier check?

**Comment by somebody1234** [comment]
@indiv0 whoops, fixed

**Pull request merged**
