### PR TITLE
Fix restoring cloud projects that have been closed (e.g. from inactivity)

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fix issues restoring cloud projects that have been closed.
On current develop, the frontend assumes cloud projects are still open from the last time they were open. If this is not the case, it tries to open WebSocket endpoints that no longer exist

### Important Notes
For a relatively easy way to test:
- Run `Enso.dmg` or `./ide run watch`
- Open a cloud project
- Refresh Electron to make sure restoration is working
- Go to `localhost:8080`
- Close the project
- Refresh Electron to make sure startup + restoration is working

Should also test restoring local projects to make sure that didn't break.

I was unable to properly test cloud projects (the one I tested with opened, but was blank with just the IDE background and no cursor and no nodes, for some reason)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
i think there are still issues with cloud project behavior - e.g. if they should open in the background

**Comment by PabloBuchu** [comment]
Ok so when the cloud project isn't available anymore we don't throw any errors that ok but the working ones are not available under `currently opened workspace`.. 

https://github.com/enso-org/enso/assets/2855109/2d6f093d-0f4c-4dce-a82f-cece1d8b64c7

When switching to from cloud to local tab I see my project was dropped in the background (I havent opened any local project)

Retrieving local project after closing Enso works fine

**Comment by somebody1234** [comment]
@PabloBuchu that should be fixed now

**Comment by somebody1234** [comment]
actually nvm... one second

**Comment by PabloBuchu** [comment]
Not sure what was fixed but works completely the same:
1. Just switch between modes drops currently opened project in the background
2. Closing Enso with opened cloud project and reopning doesn't bring it back

https://github.com/enso-org/enso/assets/2855109/351e072e-7f30-41ff-b30d-9798e865a0a6

**Comment by somebody1234** [comment]
@PabloBuchu you might have forgotten to rebuild enso

**Comment by PabloBuchu** [comment]
~@somebody1234 hmm I thought I rebuild it.. The problem with dropping project in background on mode switch is gone but still does not put active workspace after I close Enso with cloud project ready to open~

**Comment by PabloBuchu** [comment]
No it doesnt work both bugs are still present... Try to reopen Enso couple of times

**Comment by somebody1234** [comment]
oh nvm. if you're reopening relatively quickly i think i know what the issue could be

**Comment by somebody1234** [comment]
still can't repro unfortunately... it's definitely a problem, i might need more specific repro steps?
can you repro on windows?

**Comment by PabloBuchu** [comment]
Ok so problem with dropping project when switching between cloud / local is gone.

Still If I have running cloud project and close Enso. After relaunch can use top icon to go to workspace.. (the same for local works fine)


https://github.com/enso-org/enso/assets/2855109/26d06955-7c94-41b2-8102-caa59b0b8e85

**Comment by somebody1234** [comment]
@PabloBuchu could you possibly record with localstorage open? (Application -> Local Storage), and have the `enso` key expanded

(note that if you're opening the project somewhere else, e.g. the browser or `run watch`, so that it doesn't exist in `localStorage`, then not opening the project in the background is the intended behavior)
(*but*, if that's what is happening, it should be doable to load whichever cloud project is running, just want to make sure it's not some other issue that doing this would silently hide)

if the localStorage thing isn't helpful, maybe change this:
```ts
    const [projectStartupInfo, setProjectStartupInfo] =
        React.useState<backendModule.ProjectStartupInfo | null>(null);
```
into:
```ts
    const [projectStartupInfo, setProjectStartupInfo] =
        hooks.useDebugState<backendModule.ProjectStartupInfo | null>(null);
```

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@somebody1234 I recorded a properly working flow in `develop` vs this `branch` with `localStorage.enso` expanded.

https://github.com/enso-org/enso/assets/2855109/8af4ca84-98f1-4f71-afc5-8fca547cac82

**Comment by somebody1234** [comment]
side note: i just realized that projects that aren't visible, are not closed (because of course, the frontend doesn't know about them). maybe it means the backend should eventually close the user's previously opened project itself

edit: or perhaps they should stay open, because the user may have it open on another device???

**Pull request merged**
