### PR TITLE
Fix #6011. Don't use debug-assertion; fix sanity check that wasn't being run.

### LINKED ISSUE #6011: Build fails due to font texture panic
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Starting Enso started throwing a panic for me. Only a blank window opens up.
```
╭ Starting the application
│ ╭ Starting the backend process with the following options: .
│ │ Backend has been spawned (pid = 533665).
│ ╰ Done in 6.9 ms.
│ ╭ Starting the content server.
│ │ Server started on port 8081.
│ │ Serving files from '/home/procrat/repos/enso/tmp/.mount_enso-lqwQ0NE/resources/app.asar/assets'.
│ ╰ Done in 9.8 ms.
│ ╭ Creating the window.
│ ╰ Done in 123.7 ms.
│ Loading the window address 'http://localhost:8081?startup.platform=linux&engine.preferredVersion=2023.1.1-nightly.2023.2.22'.
╰ Done in 335.4 ms.
[info] [2023-03-20T13:17:25.349Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Project Manager...
[info] [2023-03-20T13:17:25.691Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server

IPC error:

panicked at 'assertion failed: `(left == right)`
  left: `6144`,
 right: `32`', lib/rust/ensogl/component/text/src/font/msdf/src/texture.rs:87:9

Stack:

Error
    at eval (eval at <anonymous> (http://localhost:8081/index.js:74:5709), <anonymous>:17788:19)
    at logError (eval at <anonymous> (http://localhost:8081/index.js:74:5709), <anonymous>:16936:14)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8081/index.js:74:5709), <anonymous>:17787:12)
    at console_error_panic_hook::Error::new::h089d5da412a450cc (http://localhost:8081/pkg-opt.wasm:wasm-function[410639]:0x4cf5a41)
    at console_error_panic_hook::format_panic_impl::h81fa303ff68f5b78 (http://localhost:8081/pkg-opt.wasm:wasm-function[84542]:0x2d0c95f)
    at console_error_panic_hook::format_panic::hd347a3ec156114f0 (http://localhost:8081/pkg-opt.wasm:wasm-function[469459]:0x4dd37d7)
    at enso_web::report_panic::he0fbc91535466bec (http://localhost:8081/pkg-opt.wasm:wasm-function[19365]:0x195ab2a)
    at core::ops::function::Fn::call::he49ee373b556e9fa (http://localhost:8081/pkg-opt.wasm:wasm-function[326963]:0x4a330c2)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8081/pkg-opt.wasm:wasm-function[92213]:0x2e9ed81)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8081/pkg-opt.wasm:wasm-function[149491]:0x38ca817)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8081/pkg-opt.wasm:wasm-function[337298]:0x4abab4d)
    at rust_begin_unwind (http://localhost:8081/pkg-opt.wasm:wasm-function[278434]:0x46fd746)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8081/pkg-opt.wasm:wasm-function[328557]:0x4a4a7b9)
    at core::panicking::assert_failed_inner::hbe435a5cb328de46 (http://localhost:8081/pkg-opt.wasm:wasm-function[25779]:0x1c53f24)
    at core::panicking::assert_failed::h10ce3e73e7a46628 (http://localhost:8081/pkg-opt.wasm:wasm-function[94668]:0x2f1d8fa)
    at ensogl_text_msdf::texture::Texture::set_data::hc253137f51a2265e (http://localhost:8081/pkg-opt.wasm:wasm-function[17860]:0x188da31)
    at ensogl_text::font::FontTemplate<ensogl_text::font::NonVariableFamily>::load_cache::hc1d8d5d046b02804 (http://localhost:8081/pkg-opt.wasm:wasm-function[3225]:0xb52b27)
    at ensogl_text::font::Embedded::load_font::{{closure}}::h9e576e91f37c9a62 (http://localhost:8081/pkg-opt.wasm:wasm-function[5456]:0xea44da)
    at core::option::Option<T>::map::h812b6955fac1e67f (http://localhost:8081/pkg-opt.wasm:wasm-function[54711]:0x25f1563)
    at ensogl_text::font::Embedded::load_font::hfb05c129d877afd3 (http://localhost:8081/pkg-opt.wasm:wasm-function[140663]:0x376efa3)
    at ensogl_text::font::RegistryData::try_load::hbab6d8939fcc9bf7 (http://localhost:8081/pkg-opt.wasm:wasm-function[3291]:0xb70c49)
    at ensogl_text::font::RegistryData::load::h46a39297e589e87f (http://localhost:8081/pkg-opt.wasm:wasm-function[156922]:0x39ec1c5)
    at ensogl_text::font::Registry::load::hafd30540ca4c3782 (http://localhost:8081/pkg-opt.wasm:wasm-function[151090]:0x3908f9d)
    at ensogl_text::font::glyph::System::new::h5b972a0d0dd8385f (http://localhost:8081/pkg-opt.wasm:wasm-function[18381]:0x18d6f75)
    at ensogl_text::component::text::TextModel::new::hb1a5f7c9c161e5e0 (http://localhost:8081/pkg-opt.wasm:wasm-function[2572]:0xa06fe5)
    at ensogl_text::component::text::Text::new::h98de8e1d3022ffc2 (http://localhost:8081/pkg-opt.wasm:wasm-function[19773]:0x198fe61)
    at ide_view::status_bar::Model::new::hda3159a0711aa135 (http://localhost:8081/pkg-opt.wasm:wasm-function[4960]:0xe04703)
    at ide_view::status_bar::View::new::hd562ab344ff21701 (http://localhost:8081/pkg-opt.wasm:wasm-function[426]:0x20a849)
    at ide_view::root::Model::new::h5f753d224d012cd0 (http://localhost:8081/pkg-opt.wasm:wasm-function[19833]:0x19979b1)
    at ide_view::root::View::new::ha32b3bd90382fd6d (http://localhost:8081/pkg-opt.wasm:wasm-function[15941]:0x1770dfc)
    at <ide_view::root::View as ensogl_core::application::command::View>::new::h94d5f0999daf825f (http://localhost:8081/pkg-opt.wasm:wasm-function[466195]:0x4dc9652)
    at ensogl_core::application::view::Registry::new_view::h08cbfd448d71d041 (http://localhost:8081/pkg-opt.wasm:wasm-function[59647]:0x274571a)
    at ensogl_core::application::Application::new_view::h59eb072516dc9b7e (http://localhost:8081/pkg-opt.wasm:wasm-function[330385]:0x4a65542)
    at enso_gui::ide::initializer::Initializer::start::{{closure}}::h1967391010cf6244 (http://localhost:8081/pkg-opt.wasm:wasm-function[531]:0x2d4d38)
    at enso_gui::entry_point_ide::{{closure}}::hdb6f268bbf66bd22 (http://localhost:8081/pkg-opt.wasm:wasm-function[9559]:0x12cd362)
    at <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::hc5b18caddbef99b4 (http://localhost:8081/pkg-opt.wasm:wasm-function[164651]:0x3affb40)
    at <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::h60c3fe5491b539e4 (http://localhost:8081/pkg-opt.wasm:wasm-function[2592]:0xa12997)
    at futures_util::stream::stream::StreamExt::poll_next_unpin::h6202272bb3e6914d (http://localhost:8081/pkg-opt.wasm:wasm-function[306426]:0x48fb536)
    at futures_executor::local_pool::LocalPool::poll_pool::h67fd0de4001b01fc (http://localhost:8081/pkg-opt.wasm:wasm-function[31652]:0x1ea2177)
    at futures_executor::local_pool::LocalPool::run_until_stalled::{{closure}}::hc2f74ba06a33a3c2 (http://localhost:8081/pkg-opt.wasm:wasm-function[112388]:0x329e3de)
    at futures_executor::local_pool::run_executor::{{closure}}::h40157e6db3fbbc29 (http://localhost:8081/pkg-opt.wasm:wasm-function[40823]:0x21b533a)
    at std::thread::local::LocalKey<T>::try_with::h65dd8f2fb48b79b6 (http://localhost:8081/pkg-opt.wasm:wasm-function[53384]:0x2591219)
    at std::thread::local::LocalKey<T>::with::he0fe003f885a6786 (http://localhost:8081/pkg-opt.wasm:wasm-function[159579]:0x3a4d8f1)
    at futures_executor::local_pool::run_executor::h547d80cb5ec03c3e (http://localhost:8081/pkg-opt.wasm:wasm-function[157431]:0x39fed60)
    at futures_executor::local_pool::LocalPool::run_until_stalled::h71d1a7bbe0e0988e (http://localhost:8081/pkg-opt.wasm:wasm-function[280289]:0x472448e)
    at enso_executor::web::EventLoopExecutor::runner::{{closure}}::h6089ee6d5d33161d (http://localhost:8081/pkg-opt.wasm:wasm-function[119413]:0x33e70ac)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::hebd1f46300d69887 (http://localhost:8081/pkg-opt.wasm:wasm-function[120600]:0x341c1a2)
    at ensogl_core::animation::loops::create_callback_wrapper::{{closure}}::hbb1faccb3f85c001 (http://localhost:8081/pkg-opt.wasm:wasm-function[156538]:0x39de280)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h6f8e2a9f79f81774 (http://localhost:8081/pkg-opt.wasm:wasm-function[280112]:0x4720a29)
    at enso_callback::RegistryModel<F>::run_impl::{{closure}}::h1924d096d0b12d61 (http://localhost:8081/pkg-opt.wasm:wasm-function[265450]:0x45e51bb)
    at alloc::vec::Vec<T,A>::retain_mut::process_loop::ha28496adea31e4c5 (http://localhost:8081/pkg-opt.wasm:wasm-function[22551]:0x1aea108)
    at alloc::vec::Vec<T,A>::retain_mut::hac9662dba9342e57 (http://localhost:8081/pkg-opt.wasm:wasm-function[57260]:0x26a37fd)
    at enso_callback::RegistryModel<F>::run_impl::h9dd728c253998e28 (http://localhost:8081/pkg-opt.wasm:wasm-function[5649]:0xee089a)
    at enso_callback::Registry<F>::run_impl::h1e8cbd685c450177 (http://localhost:8081/pkg-opt.wasm:wasm-function[375926]:0x4c1bccc)
    at <enso_callback::Registry<dyn core::ops::function::FnMut<(T1,)>+Output = ()> as enso_callback::traits::RegistryRunner1>::run_all::hfc3b03add28f75c5 (http://localhost:8081/pkg-opt.wasm:wasm-function[316815]:0x499c899)
    at ensogl_core::animation::loops::on_frame_closure::{{closure}}::{{closure}}::hc9f18a55518ab566 (http://localhost:8081/pkg-opt.wasm:wasm-function[375527]:0x4c184b9)
    at core::ops::function::FnOnce::call_once::h85ada34ee8e36dc9 (http://localhost:8081/pkg-opt.wasm:wasm-function[293354]:0x4819f16)
    at <enso_frp::microtasks::TickPhases<enso_generics::hlist::Cons<H,T>> as enso_frp::microtasks::TaskPhasesScheduleImpl>::schedule::{{closure}}::h89f6bf83dd2f8490 (http://localhost:8081/pkg-opt.wasm:wasm-function[38834]:0x2115f38)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hfa6e836a616c9e6a (http://localhost:8081/pkg-opt.wasm:wasm-function[335276]:0x4aa3329)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2bc532f64519734a (http://localhost:8081/pkg-opt.wasm:wasm-function[316968]:0x499edfa)
    at enso_callback::RegistryModel<F>::run_once_impl::hf74c1e53ace8a58b (http://localhost:8081/pkg-opt.wasm:wasm-function[3237]:0xb587e9)
    at enso_callback::Registry<F>::run_once_impl::hfb88f0d1c102a229 (http://localhost:8081/pkg-opt.wasm:wasm-function[377675]:0x4c298e7)
    at <enso_callback::Registry<dyn core::ops::function::FnOnce<()>+Output = ()> as enso_callback::traits::RegistryRunner0>::run_all::h3ca7f0c95f1fa83d (http://localhost:8081/pkg-opt.wasm:wasm-function[500904]:0x4e20759)
    at enso_frp::microtasks::SchedulerData::run_all::hc04de7d9d045a260 (http://localhost:8081/pkg-opt.wasm:wasm-function[6666]:0xfffd9a)
    at enso_frp::microtasks::Scheduler::new::{{closure}}::{{closure}}::hfbd2fdd34a7d572b (http://localhost:8081/pkg-opt.wasm:wasm-function[36185]:0x2037c80)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4b3371bf6b251cd0 (http://localhost:8081/pkg-opt.wasm:wasm-function[155593]:0x39ba836)
    at __wbg_adapter_70 (eval at <anonymous> (http://localhost:8081/index.js:74:5709), <anonymous>:17035:8)
    at real (eval at <anonymous> (http://localhost:8081/index.js:74:5709), <anonymous>:16922:14)
```

### Expected behaviour

No panic.

### How we can reproduce it?

`./run ide watch --wasm-profile=dev --backend-source=release --backend-release=latest`

### Screenshots or screencasts

_No response_

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix an assertion that wasn't being run. Debug assertions are only enabled in `--wasm-profile=dev` builds, better to use `error!`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] ~The documentation has been updated, if necessary.~
- [ ] ~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~Unit tests have been written where possible.~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by mwu-tow — APPROVED** [review]

**Comment by wdanilo** [comment]
I'm OK with this change, but there is a more general question emerging. In performance-critical code, we should use debug assertions, right? We do not want to keep assertion code being run always. Maybe we should distribute 2 packages to users - one with and one without debug assertions?

**Comment by kazcw** [comment]
> I'm OK with this change, but there is a more general question emerging. In performance-critical code, we should use debug assertions, right? We do not want to keep assertion code being run always. Maybe we should distribute 2 packages to users - one with and one without debug assertions?

Debug assertions could be useful for development, but currently they are problematic: We are building with `debug-assertions = false` by default, so debug assertions are not being run (except in tests, which use a different profile). We could make debug assertions useful by enabling them in the default profile, and disabling them in release builds (and maybe nightlies)--the only problem I see with this approach is that we may go through some crashes as some existing debug-asserts are run for the first time.

IMO `debug_assert!` is not useful for end users, because a panic just ensures the app is broken. I think ideally we'd replace panicking assertions with assertions that display a warning on screen (a developer-build only version, and one enabled for users to use if something critical is wrong, that offers a reload option).

**Comment by sylwiabr** [comment]
@kazcw is it waiting for anything or it's ready for merge? Who is doing a QA?

**Review by wdanilo — APPROVED** [review]

**Comment by wdanilo** [comment]
@sylwiabr this is super small change. Q/A not needed. Accepted, thanks @kazcw for the reply, fully agree.

**Pull request merged**
