### PR TITLE
Updating paste crate

### PR DESCRIPTION
**Pull request by wdanilo**
[ci no changelog needed] 

### Pull Request Description

This PR updates the paste macro crate.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

### CODE REVIEW

**Review by MichaelMauderer — APPROVED** [review]
Looks good to me!

Only one comment: on a quick search, it seems that in `lib/rust/shapely/Cargo.toml` we also use the paste macro, so we might want to update this usage, too.

**Review by mwu-tow — COMMENTED** [review]
I don't think that `paste` crate is updated here, I don't see any update in the Cargo.lock, just removed dependency.

**Comment by wdanilo** [comment]
@mwu-tow it's more about updating the usage. `paste` macro has a new API still supporting the old one.

**Comment by MichaelMauderer** [comment]
@wdanilo What is the status of this?

**Comment by wdanilo** [comment]
@MichaelMauderer it should be merged. I missed it, sorry.

**Pull request merged**
