### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/676
  - Adds labels to the dashboard:
    - Filtering assets by label
    - Creating new labels
    - Displaying labels in "Labels" column
    - Adding a new label to an existing asset (multi-select)

### Important Notes
WIP: Use a color picker with pre-defined colors, instead of randomly generated colors

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
@somebody1234 one additional thing.. can we have small trash icon in top right corner of the label? if user wants to remove the label they can click it.. there also should be a confirmation modal before issuing the request
```
DELETE /tags/<tag_id
```

**Comment by somebody1234** [comment]
can do tomorrow i guess. i think the main issue would be that it'd be *tiny* on non-retina displays. like 8px by 8px or something

**Comment by somebody1234** [comment]
maybe we could do a low opacity, but full sized trash icon on hover, to the right of the label. thoughts?

**Comment by somebody1234** [comment]
:disappointed: it seems like *properly* deleting labels will be a bit difficult, as we will potentially need to recursively delete labels on both the frontend and backend side? (also, the backend should probably also (somehow) have a recycle bin for labels)

**Comment by somebody1234** [comment]
I've spent a while implementing basic visual regression tests for the labels panel (and create labels modal) - I didn't get around to implementing them for the labels column and manage labels modal, nor for the drag-n-drop PR

**Comment by PabloBuchu** [comment]
@somebody1234 backend will take care about recursively removing it from assets. we just need to show a confirmation for the user and probably relaod list directory

**Comment by PabloBuchu** [comment]
also for the record lets move to use repeted params for labels filtering when calling `/directories`

**Comment by somebody1234** [comment]
yeah re: repeated params, that *should* be implemented + pushed now.

**Comment by somebody1234** [comment]
as for reloading all directories... actually the frontend currently has no logic for that. also i think it might be quite expensive (both in redundant work on the backend, and long latency on the frontend).

after thinking about it for a bit, actually i think it should be doable to implement in the frontend as well, especially with the new variables i had to add to be able to delete it in the sidebar in the first place. i'll take a stab at it tomorrow

**Comment by PabloBuchu** [comment]
when I create a label and nothing more I see request `GET /directories?filter_by=Active&labels=` so:
1. something is triggering dashboard reload and I think we should not here
2. we send `label=` empty param

**Comment by somebody1234** [comment]
@PabloBuchu ah yeah. what's triggering dashboard reload is probably the list of currently selected labels...
... but that shouldn't change unless a label is actually clicked. so this is definitely a bug, will investigate tomorrow.

**Comment by somebody1234** [comment]
speaking of dashboard reload though - should we be recursively reloading the entire tree? or collapsing all folders?

i'd assume recursively reloading is the *right* thing to do here, but realistically i don't think it matters too much either way

**Comment by PabloBuchu** [comment]
@somebody1234 actually from user perspective its bad UX if creating a label would roll up all directory tree so yeah lets make an effort to reload recursively

**Comment by somebody1234** [comment]
some thoughts:
i think it may be possible to avoid reloading at all in certain cases, if we keep track of the labels sent on the request (per-directory)
e.g. if the new filters are (all of the old filters), plus (some extra filters), we can filter the entries we already have, purely on the frontend. thoughts?
- too complicated for too little gain?
- worth a try if it's simple enough?

more importantly: is the list of selected labels something we want to be persisting across sessions? i think yes, because it doesn't result in any extra requests being sent?
we have to be careful to filter out labels that no longer exist, but i think that should be simple enough

**Comment by somebody1234** [comment]
did some basic testing of the new features:
- recursive refresh
- frontend logic for deleting labels

they seem to have no major problems, it'd be good to have more thorough testing though.

one thing i *did* find out though, was that... of course, if there's a nested asset with a specific label, it doesn't show up - because the parent does not have the same label. thoughts?
i think one solution would be to return all results matching the query in a flat list, another solution would be to show the parent directories, on the frontend at least - but i think that would require the frontend to do *all* filtering for labels...

**Comment by somebody1234** [comment]
another issue (both frontend and backend): labels with duplicate names can be created. the frontend stores label names for each asset (i believe that's what the backend returns anyway) so i don't think it makes sense to allow duplicate labels?

**Comment by somebody1234** [comment]
also: for labels created from the "labels" column:
- the duplicate names seems to be a non-issue, as the filter returns some matching labels, meaning that the "create" button is disabled.
- the modal currently closes after a new label is created (using the "create" button). should it stay open instead?
  - fwiw i don't think it's a *bad* thing for it to close, i'd assume if you want to create a new label you generally only want to create one at a time (or just add that single label) anyway

**Comment by PabloBuchu** [comment]
Small bug:
1. create a label, dont put it on any asset
2. select it
3. remove it
4. you ends up with blank dashboard without a way to clear the query params that are being sent to API

we should make sure the label is cleared from `labels` sent to backend after delete

**Comment by somebody1234** [comment]
ah... good catch, thanks

**Comment by somebody1234** [comment]
found another issue... the sidebar doesn't like label names that are too long.
image

not sure what's the best solution though. we could set a hard character limit, or manually measure text

**Comment by somebody1234** [comment]
the small bug *should* be fixed by the latest commit.

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
weird... that one labels screenshot *is* flaky... it worked on retry but failed again after being merged...

**Pull request merged**
