### PR TITLE
Fix compilation error when building single graph_editor crate

### PR DESCRIPTION
**Pull request by farmaazon**
[ci no changelog needed]

### Pull Request Description

@akavel spotted a compilation error, when building test for graph_editor crate. The cause was that:
* prelude without serde still added serde derivatives in im_string_newtype
* and the graph_editor needs serde from prelude anyway (because it wants to have serializable ImStrings).

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
~~  - [ ] Unit tests have been written where possible.~~
~~  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.~~

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]
Fast question – why we do not build everything with serve always ?

**Review by akavel — APPROVED** [review]
Fixes the issue for me, thanks!

That said, @farmaazon I'll keep repeating my question (I didn't seem to see a response, did I overlook it?) - did you manage to confirm with 100% certainty that the `bounding_box` tests are being run in the CI at all? I'm still not confident it happens.

**Comment by farmaazon** [comment]
> Fixes the issue for me, thanks!
> 
> That said, @farmaazon I'll keep repeating my question (I didn't seem to see a response, did I overlook it?) - did you manage to confirm with 100% certainty that the `bounding_box` tests are being run in the CI at all? I'm still not confident it happens.

Yes, I am. At least, I negated one assert's condition and got the error in `./run test`. `./run test` is called in CI. But if you are still not convinced, you can also modify the test, push, and see CI failing.

**Comment by akavel** [comment]
> Yes, I am. At least, I negated one assert's condition and got the error in `./run test`. `./run test` is called in CI. But if you are still not convinced, you can also modify the test, push, and see CI failing.

Awesome, that's all I wanted to know, thanks! ❤️

**Review by wdanilo — APPROVED** [review]

**Comment by farmaazon** [comment]
> Fast question – why we do not build everything with serve always ?

@wdanilo Perhaps a bit of overpreparing, but I imagined that we will have crates in the future which will want to use prelude, but not incorporate the whole serde (it's a bit heavy after all).

**Pull request merged**
