### PR TITLE
Fix rest of user/team permissions checks and "new label" dialog

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix remaining permissions checks to check for team permissions as well, not just user permissions
- Fix https://github.com/enso-org/cloud-v2/issues/1498
  - Switch "new label" dialog from `Modal` (old) to `Popover` (new)
- Fix https://github.com/enso-org/cloud-v2/issues/1500
  - Show correct project state even for projects not opened as tabs
- Unconditionally show project play icon instead of network (graph) icon, even when user lacks access (no exec permissions, or in the trash category)
- Disable (attempting to) open project in trash via double click

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
not sure why eslint is being funny

**Comment by somebody1234** [comment]
nvm they are real warnings

**Comment by somebody1234** [comment]
or not? it seems like some lints are broken...?

**Comment by somebody1234** [comment]
never mind! my git hooks were just wrong so it was using latest versions

**Review by MrFlashAccount — APPROVED** [review]

**Comment by PabloBuchu** [comment]
Trash still has broken project icons

**Comment by somebody1234** [comment]
@PabloBuchu oh i think that is intentional because projects cannot be run from trash. should they perhaps just be disabled?

**Review by indiv0 — APPROVED** [review]

**Comment by PabloBuchu** [comment]
So they can / should be disabled but the project icon (play button) should be there nevertheless

**Comment by somebody1234** [comment]
@PabloBuchu ready for re-QA after push (soon :tm:)

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
Ok so I opened a project in Electron. Then wanted to check it in the browser. Despite `Project` being in `Opened` I can't open the graph editor. Up arrow does nothing.
Screenshot 2024-09-23 at 11 02 36

`Close` worked (send a request) but did not changed the icons back

**Comment by PabloBuchu** [comment]
| Disable (attempting to) open project in trash via double click
Yes but select + enter still works ;/

Screenshot 2024-09-23 at 11 04 57

**Comment by somebody1234** [comment]
> `Close` worked (send a request) but did not changed the icons back

i think this might be out of scope, i assume this would require periodic refreshes until the project is closed
(assuming the issue is that things do get refetched but FE is refetching too early)

**Comment by somebody1234** [comment]
> Despite `Project` being in `Opened` I can't open the graph editor

cloud projects still aren't opening for me so i kinda want to count this one as out of scope as well - although if it is a regression i am happy to investigate later

**Pull request merged**
