### PR TITLE
Update assets table design

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/552:
- Combines assets tables into a single table
- Double click to expand/collapse directory
- Ordering is *not* changed - the backend should return items in the correct order
- :warning: Name column scrolling is not implemented
- Rounded border for rows
  - :warning: Row background is not indented 

Other changes:
- Switch permission tags to new design

### Important Notes
As can be seen above, some elements are currently not implemented. This is intentional - this PR is already quite large, and I think it is close enough that it is a better use of time to implement the rest of the new design before coming back and polishing this one.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. When you are opening multiple directories the width of first column is growing. Instead we should show the horizontal scrollbar
2. Closing any directory in the directory tree should roll up the whole tree
https://github.com/enso-org/enso/assets/2855109/3424fa9e-fb11-4e26-8f75-cd26d68ec091
3. Selected row has different color in figma

**Comment by somebody1234** [comment]
1. i just looked into it and it seems quite difficult, unfortunately :(
  - solution 1: using `absolute` positioning. this means positioning every column other than the first one using exact pixel offsets from the left. this sounds pretty fragile so probably not the best idea
  - solution 2: using two tables (the name column in table 1, every other column in table 2). for the most part this would work decently since name state and everything else state is more or less separate, but it'd break things that the table/row data handle - selection state and insertion state mostly
  - solution 3: have a fake div for the scrollbar and use React to scroll every cell at the same time. i *think* this is the simplest solution, but it'd be good to confirm this
2. fixed and pushed
3. fixed and pushed

**Comment by somebody1234** [comment]
i've just noticed that the "view" button should have space for the docs/execute border (and both "view" and "read" tags should have smaller horizontal borders) - i might get around to fixing them later, but i don't think it'd be too late to fix them alongside the updated "shared with" modal design

**Comment by PabloBuchu** [comment]
I have merged in locally new background image for better visibility.
Screenshot 2023-07-26 at 11 17 30

1. `New project` isn't properly centered, font weight should be 600
2. Missing white background around new directory, secret, upload, download icons. Can't see right now cause icons don't have background but between `New project` and icon groups should be 10px gap
3. The table should have width of 100% (so the row highlighting reach till the end of the window. `Shared with` is now too narrow

**Comment by somebody1234** [comment]
@PabloBuchu issues should be fixed now

**Comment by somebody1234** [comment]
also changed the "New Project" button's background from white (100% opacity) to the correct background

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
