### PR TITLE
Download single edition by name

### LINKED ISSUE #7480: Creating a project on a new machine for the first time takes ages and eventually hangs infinitely
### Discord username

_No response_

### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I downloaded the newest nightly on a clean machine and created a new project. I took ages to download Graal and eventually hang on 
image

When I tried to open another project it was created quickly and run pretty smoothly. I was waiting for 30 min before doing any action.

### Expected behaviour

New project creation should not hang.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

Nightly 2.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

MacBookAir Apple M1 8gb MacOS Ventura 13.3.1

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

close #7480

Changelog:
- update: download the single required edition instead of batch update

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Comment by 4e6** [comment]
QA:
- Clean the [`ENSO_DATA_DIRECTORY`](https://github.com/enso-org/enso/blob/294ee46af4583ac1a2da0e797dc7193e8260a8d5/docs/distribution/distribution.md#installed-enso-distribution-layout) directory
- Build IDE with `./run ide build` or download one from the CI, i.e. commit [0afb206](https://github.com/enso-org/enso/actions/runs/6122309049?pr=7771)
- Open a new project or change the edition of the existing project, for example to `2023.2.1-nightly.2023.9.7`

**Comment by JaroslavTulach** [comment]
Shouldn't we avoid downloading anything (including an edition) when one downloads IDE and creates new project? Everything shall be ready locally (GraalVM, engine, stdlibs, edition).

**Comment by hubertp** [comment]
> Shouldn't we avoid downloading anything (including an edition) when one downloads IDE and creates new project? Everything shall be ready locally (GraalVM, engine, stdlibs, edition).

There is a separate ticket for that #7698.

**Comment by hubertp** [comment]
I'm still seeing
```
[DEBUG] [2023-09-12T10:27:56+02:00] [org.enso.projectmanager.requesthandler.ProjectListHandler] started (org.enso.projectmanager.requesthandler.ProjectListHandler@341bbd41)
[DEBUG] [2023-09-12T10:27:56+02:00] [org.enso.downloader.http.HTTPDownload] Fetching [https://editions.release.enso.org/enso/manifest.yaml].
[WARN] [2023-09-12T10:27:56+02:00] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.2.1-nightly.2023.8.15),None,Map(),Map()). Falling back to Edition(Some(0.0.0-dev),None,Map(),Map())
[DEBUG] [2023-09-12T10:27:56+02:00] [org.enso.downloader.http.HTTPDownload] Fetching [https://editions.release.enso.org/enso/manifest.yaml].
```
when I deleted the specific version and opening a different version project. Shouldn't these be gone as well?

**Comment by 4e6** [comment]
> when I deleted the specific version and opening a different version project. Shouldn't these be gone as well?

@hubertp it makes sense to fallback to default edition because there's no `2023.2.1-nightly.2023.8.15` version published https://editions.release.enso.org/enso/manifest.yaml

**Comment by hubertp** [comment]
> > when I deleted the specific version and opening a different version project. Shouldn't these be gone as well?
> 
> @hubertp it makes sense to fallback to default edition because there's no `2023.2.1-nightly.2023.8.15` version published https://editions.release.enso.org/enso/manifest.yaml

Yes, but why does it check it all? I'm not opening that project.

**Review by hubertp — APPROVED** [review]
Created a separate ticket for the discovered problem.

**Pull request merged**
