### PR TITLE
Allow downloading Data Links and projects

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/944
  - Allow downloading Data Links, not just files, from the Cloud backend.
- Close https://github.com/enso-org/cloud-v2/issues/947
  - Also allow downloading projects. This is SAFE to add before the cloud redeploy because the property is optional anyway.

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
Is it working? Still have download file disabled for datalinks and projects.. checking in new gui 
Screenshot 2024-03-11 at 15 42 02

**Comment by somebody1234** [comment]
oh, my bad, totally forgot about the context menu... will fix soonish

**Comment by somebody1234** [comment]
@PabloBuchu should be enabled now. i don't think there's anything else that needs to be done other than changing the logic of when the button is disabled, did some basic testing and it seems to work

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@somebody1234 you can rebase and merge

**Pull request merged**
