### PR TITLE
Simplify button variants

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Remove "cancel" variant in favor of "outline" variant
- Remove "bar" variant in favor of "outline" variant
  - Buttons in the Drive Bar have been switched to a new "outline-light" variant that is the same as the "outline" variant except with the border color of the "bar" variant
- Rename "tertiary" variant to "accent"
- Remove `components/Input` and `components/ControlledInput` which are no longer used

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by MrFlashAccount** [comment]
> Buttons in the Drive Bar have been switched to a new "outline-light" variant that is the same as the "outline" variant except with the border color of the "bar" variant

Maybe we can unify both `outline` and `outline-light`? IMO having both doesn't make much sense as they're serving the same purpose.

FWIW, in the future, I'd like to go deeper with customizing button styles and split colors (primary, accent, danger, etc) with variants (solid, outline, icon, etc), example: https://v2.chakra-ui.com/docs/components/button



<blockquote><div> Chakra UI: Simple, Modular and Accessible UI Components for your React Applications.</div><div><strong><a href="https://chakra-ui.com">Button</a></strong></div><div>Button component is used to trigger an action or event, such as submitting a form, opening a Dialog, canceling an action, or performing a delete operation.</div></blockquote>

**Comment by somebody1234** [comment]
@MrFlashAccount originally (?) i had `outline` with the lighter border of `outline-light`, but i tried it out a bit and thought that it makes other buttons (e.g. the smaller buttons) stand out quite a bit less - although i'm not *against* merging the two fully. wdyt?

**Comment by MrFlashAccount** [comment]
@somebody1234 could you please provide a screenshot ?

**Comment by somebody1234** [comment]
Current:
image

Lighter:
image

Replacing `outline-light` with `outline`, for comparison (the button and bar should have the same border):
image

**Comment by MrFlashAccount** [comment]
@somebody1234 lets rename `outline-light` to `outline`. `border-primary/20` better match other elements

**Comment by PabloBuchu** [comment]
Tbh don't see much difference 😅 but went through looking for regressions and haven't found any so ✅

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
i think the only visible diffrences should be:
- lighter outline of "outline" variant
- cancel buttons now use outlines instead of a lighter background (which is hard to see)

**Pull request merged**
