### PR TITLE
Fix performance issue with too many labels existing in the performance visualisation.

### PR DESCRIPTION
**Pull request by MichaelMauderer**
### Pull Request Description
This PR resolves the issue that too many text labels are created in the performance visualization.

https://user-images.githubusercontent.com/1428930/158601643-d8941752-2922-4551-9759-62fa468289ec.mp4

### Important Notes

[ci no changelog needed]

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

### CODE REVIEW

**Comment by kazcw** [comment]
I have tried to use this with real data, and it has a bug that might be related to panning. The labels for some boxes are rendering at the wrong X-position.

Example:
image

My cursor is over the big box to the left of the view, but the label is rendering at the right side of the screen.

**Review by wdanilo — COMMENTED** [review]
Please include a screencast with real world use case (testing all corner cases you'll think of) to every PR that it is possible for :) Good to see it implemented! I believe that by including such screencasts, such bugs as Kaz pointed out, will be matched up earlier.

**Comment by kazcw** [comment]
I'm looking in to the label position bug. It turns out it's not actually a problem with positions per se: Actually, what's happening is the mouseover event for a block seems to be controlling the label for some other block! I'm trying to understand the FRP network better, because I think that must be where the signals are getting crossed...

EDIT: There is a dividing point in the block order; everything defined after a certain block (i.e. to its right) is associated with the correct label; everything to the left of that point is associated with some label to the right of that point. So the oldest blocks have had their signals hijacked by the handlers for the newer blocks...

**Comment by kazcw** [comment]
@MichaelMauderer The comment above summarizes my understanding of the label bug at this point; I'm signing off for the day. I'm sure you could get to the root of this faster than I can, so if you'd like to take this back tomorrow let me know so I don't duplicate your efforts; otherwise, tomorrow I'll continue debugging the crossed labels and learning my way around the FRP system.

**Comment by kazcw** [comment]
So, I figured out why labels are showing up in the wrong place. It's not a bug in this PR; it is a deeper issue. [`scene::PointerTarget`](https://github.com/enso-org/enso/blob/b9172b46a170e0a1bacd52be403e12eca2af5287/lib/rust/ensogl/core/src/display/scene.rs#L151) is not designed to be able to support more than 4096 coexisting instances of one `Symbol`. A profile can easily have 20k intervals. Mouse events resulting from interaction with any block will be received by one of the 4096 most recently created blocks (with the recipient decided by modular arithmetic on the `InstanceIndex`).  I've opened a separate [issue for it](https://www.pivotaltracker.com/story/show/181578258).

I'm going to get back to finishing up #3332; for now I will work around the label limitation by adding an option to truncate logs to a time window, since the problem has to do with exceeding 4096 objects.

**Comment by MichaelMauderer** [comment]
@wdanilo Added screencast for the test use case. Since the issue spotted is independent to this PR, we should still be able to merge it after review.

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
