### PR TITLE
Fix improperly scoped styles in visualizations

### LINKED ISSUE #7210: Style leakage in `histogram.js` and `scatterPlot.js`
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

`button:hover` styles are not scoped to the visualization, so it is affecting dashboard appearance.

### Expected behaviour

`button:hover` is only applies to the specific visualization

### How we can reproduce it?

1. Open a project with either the "histogram" or "scatterPlot" visualizations. The "KMeans" template is one such project.
2. Go back to Dashboard
3. Hover over any button (most interactable elements are buttons)

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

b243a5f

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11 21H2 (OS Build 22000.1936)

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fixes #7210

### Important Notes
Can't test as of posting this PR. I will test later, just opening this PR in case anyone is willing to test (after reliably repro-ing the issue first).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
finally tested after switching `--backend-release` from `latest` to `nightly` - the fix seems to work, visualizations seem to still be working (or rather, looking) fine

**Review by jdunkerley — APPROVED** [review]

**Comment by PabloBuchu** [comment]
Can't really QA since I am having problems reproducing original error. @somebody1234 could you add a video before and after?

**Comment by somebody1234** [comment]
@PabloBuchu whoops, forgot to mention it only happens in the scatterplot and histogram visualizations - so it only happens on specific projects, like kmeans. posting screencast soon

**Comment by somebody1234** [comment]
current develop:

[screen-recorder-mon-jul-10-2023-20-09-04.webm](https://github.com/enso-org/enso/assets/4046547/fd81680a-3db6-44ed-9d70-68e246ed447f)

this branch:

[screen-recorder-mon-jul-10-2023-20-12-36.webm](https://github.com/enso-org/enso/assets/4046547/2ee58f4b-2556-4aa5-b8e2-84f405b90670)

**Comment by PabloBuchu** [comment]
@somebody1234 yeah I have read the original issue. Still can't reproduce. James approved so I think its safe to merge

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
