### PR TITLE
Fix dropdown laziness; also misc fixes

### LINKED ISSUE #6865: Loading dropdowns with many elements is too long.
https://github.com/enso-org/enso/assets/1436948/ed53ab2d-52eb-403b-9d31-515a3a0124e9

There are 3  issues in this video, but this task tracks only: 

3. Likely a separate issue but the video also shows that once the dropdown list has more elements it takes **ages** to load - the list from the video took **more than 10 seconds** to load. And during the whole time of it loading the IDE, the cursor were all frozen and no spinner was shown to tell the user that some operation is in progress - one may think that the application just crashed.

The other two are tracked in separate issues.

1. If I scroll with the mouse wheel, the dropdown _does scroll_ BUT along with it _the whole workspace_ also moves around. There is no focus management - both the whole viewport as well as the dropdown list are reacting to the scrolling events whereas only one should react at a time - probably when the mouse is over the dropdown list it should get 'focus' and scroll without scrolling the whole workspace. #6649 
2. If I click on the scrollbar displayed in the dropdown list and move it around using my mouse, it again does move, but that movement also causes 'dragging' of the related element for which the dropdown is shown in the vector editor - possibly reordering it (if multiple elements) or dragging out of the vector and deleting. Again - when dragging the scrollbar - the list should scroll without propagating the event further and moving the element. Overall, I think that clicking over the dropdown should not cause dragging of its parent element above it. #6823

### LINKED ISSUE #6975: Rendering issues following merger of "reduce draw calls"
While QAing this morning to do the book clubs a few issues appeared.

1. When editing text and hovering over a node with a connection the bottom half of the node gets coloured.
image

2. The error border is hidden behind the selected node highlight and makes it very subtle.
image

3. The error vis box no longer has rounded corners (other viz boxes do).
image

4. Two text nodes over the top of each  other merge the content into a single mix.
image

5. Docking appears to have become significantly more difficult and only reliable way was to go in from the bottom which seems to make it find it (not sure if related but feels much worse on this build).

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Several small changes:
- Dropdowns: Populate `GridView` lazily (fixes #6865).
- Clear disconnected edges when editing node (fixes case 1 in #7018).
- Fix regression in node selection rendering (2nd bug in #6975).
- Update profiler docs. The hotkey to *prOfile without exiting* is now `Ctrl+Alt+O` (`Ctrl+Alt+P` has been requisitioned by the CB).

Node selection:
| Pre-`Rectangle` | This PR |
| --- | --- |
| image | image |

### Important Notes

- `Rectangle`: When `inset > border`, the extra space is now between the body and the border, not outside the border.
- More robust node layering logic. Now an inconsistent layer order cannot occur, even if something strange happens (like editing an expression and an edge at the same time).
- The dynamic drop down in the `drop_down` example scene doesn't show any entries before (or after) this, so I can't test the dynamic case.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by sylwiabr** [comment]
@kazcw when this will be ready for review?

**Review by wdanilo — APPROVED** [review]
Perfect! One small request on my side: could you please add this info to the rectangle docs please? `Rectangle: When inset > border, the extra space is now between the body and the border, not outside the border.`

**Comment by vitvakatu** [comment]
QA: 🟨 

Everything is working fine, but in some cases, the edge is not dropped when editing the node. It happens for me reliably when you hover the edge over any port (so that it changes its shape), then press `ctrl-click`. Clicking anywhere while editing the node drops the edge. It does not affect the node editing but can be confusing, hence 💛 status on QA.


https://github.com/enso-org/enso/assets/6566674/afff5f3e-daf5-430a-b6fb-5eec4ef758fe

**Comment by kazcw** [comment]
On ctrl-click with a detached edge, we are connecting the edge, and also beginning to edit the expression. Later the edge is dropped when the graph is evaluated and the edge is found not to exist (because the edited expression doesn't contain the corresponding identifier). This case is independent of the issue this PR fixes, and fixing it will definitely touch code @Frizi is currently making major changes to--so let's fix it separately. I'll add it to #7018.

**Pull request merged**
