### PR TITLE
Use libraries merged from `rust-lib` directly

### PR DESCRIPTION
**Pull request by mwu-tow**
This is one of the post-merge cleanups: libraries that were once split across different repositories are now together, allowing for the direct dependency inclusion.

This will help us greatly in making sure that all code works together.
The paths now look cumbersome, but this should improve when we will rework the crates layout.

### CODE REVIEW

**Comment by vitvakatu** [comment]
Shouldn't we preserve at least one of the `Cargo.lock` files? You deleted both the root one and the one from ex-ide. Actually there is a third one: `gui/src/rust/test/Cargo.lock`, but it wasn't touched for the last two years it seems.

**Comment by mwu-tow** [comment]
@vitvakatu 
> Shouldn't we preserve at least one of the `Cargo.lock` files? You deleted both the root one and the one from ex-ide. Actually there is a third one: `gui/src/rust/test/Cargo.lock`, but it wasn't touched for the last two years it seems.

I don't think I've removed them, they were just regenerated. GitHub by default does not expand such large changes but the files and their contents is there.

**Comment by vitvakatu** [comment]
@mwu-tow oh, I'm sorry, github UI confused me, I thought they were deleted

**Comment by mwu-tow** [comment]
@vitvakatu Yeah, this had me UI scared for a moment when I opened list of changed files after reading the comment. :D
Anyway, thank you for raising the question — better safe than sorry!

**Review by farmaazon — APPROVED** [review]

**Review by MichaelMauderer — APPROVED** [review]

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
