### PR TITLE
Show spinner when opening/creating a project, take #2

### LINKED ISSUE #5505: Users should see a spinner / loading indicator when opening a project
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/181585195).
<hr />

### Steps to reproduce
1. Open the IDE
2. Select a project

### Expected
A spinner should show up until the project is ready for interaction.

### Actual
A blank canvas is visible.

### PR DESCRIPTION
**Pull request by Procrat**
### Pull Request Description

This is almost the same as #6321, but it got reverted since it created an impactful regression.

To recap, this fixes #5505: A spinner with the Enso logo is now shown for most of the duration when opening and creating projects.\

The only new code is the last commit which ensure that it works when there is no project manager available.

Note that the value of the spinner is somewhat lessened with the new dashboard since some of the startup time is covered after clicking the play button in the dashboard but before opening the project.

With the old dashboard:

https://github.com/enso-org/enso/assets/607786/f357263b-8a88-4ef1-9ca7-ced99ca75a2b

With the new dashboard:

https://github.com/enso-org/enso/assets/607786/d9f99248-5830-43e0-a731-f2a6e0147908

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] ~~Unit tests have been written where possible.~~
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]

**Comment by farmaazon** [comment]
## QA Report: :yellow_circle:   

When opening project with a new dashboard, there is a brief moment when I see "Initializing project..." what suggests the loading spinner is hidden a bit too early.

https://github.com/enso-org/enso/assets/3919101/a4c66a50-e00f-48c6-a9a7-a235a30fb601

We could live with it, but it should be checked + I'm not sure if it isn't more prominent on weaker hardware.

**Comment by wdanilo** [comment]
1. Could you link the regression ticket, please? I want to better understand what changed between this and previous implementation take.
2. Could you link the commit with the changes between this and the previous implementation? In the PR description you've written "The only new code is the last commit which ensure that it works when there is no project manager available.", which is probably not the case anymore.

**Comment by Procrat** [comment]
> 1. Could you link the regression ticket, please? I want to better understand what changed between this and previous implementation take.

This is the regression issue: https://github.com/enso-org/enso/issues/6708

> 2. Could you link the commit with the changes between this and the previous implementation? In the PR description you've written "The only new code is the last commit which ensure that it works when there is no project manager available.", which is probably not the case anymore.

It's this one: 8216a267eb8f293451e5a959975a57a16e14a9a6

**Comment by Procrat** [comment]
After discussion with @farmaazon, we decided to merge this as is since it contains useful changes, but not close the original issue since it's not resolved yet.

**Comment by wdanilo** [comment]
@Procrat I've left a comment in the code but it's not displayed here:

image

**Pull request merged**
