### PR TITLE
More E2E tests; `export default` classes from modules

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
This is a prerequisite for adding a CI action for E2E tests.

- Fix E2E tests
- Remove visual regression testing (VRT) and associated fixtures (screenshots) for now
- Switch dashboard almost fully to Vite, from ESBuild, to match GUI2's build tooling.
- Add some new E2E tests:
  - Creating assets
  - Deleting assets
  - Creating assets from the samples on the home page
  - Sort assets
    - Includes fixes for sorting:
      - Group sorted assets by type again (regression) (see https://github.com/enso-org/cloud-v2/issues/554)
      - Make sorting by title, case insensitive. This is because it is more intuitive for non-programmers if all items with uppercase names *aren't* separated from those with lowercase names - especially since the Windows FS is case-insensitive.
        - Normalization of Unicode letters is *not* currently being done. It can potentially be added later.
- Double-clicking *anywhere* on a directory row now expands it. Previously it was only being expanded when double clicking
- Add recursive label adding/removal to mirror backend
  - Note: The current implementation is not exactly the same as the backend's implementation.
- Fix https://github.com/enso-org/cloud-v2/issues/872
  - Unset "saved project details" (for opening the last open project) if fetching it produces an error.

### Important Notes
- All tests pass. (run `npm run test:e2e` in `app/ide-desktop/lib/dashboard`)
- All `npm` commands should be run in `app/ide-desktop/lib/dashboard`. `dashboard:*` npm scripts have been removed from `app/ide-desktop` to prevent a mess.
- `npm run dev` confirmed to still work. Note that it has not been changed as it was already using Vite.
- `npm run build` now uses `vite build`. This has been tested using a local HTTP server that supports `404.html`.
- Other cases have been tested:
  - `npm run test:e2e` works (all tests pass)
  - `./run ide build` works
  - `./run ide watch` works
  - `./run ide2 build` works
  - `./run gui watch` works

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
`cd app/ide-desktop/lib/dashboard && npm run test:e2e` results with 5 fails and 23 successes

```
Running 28 tests using 6 workers

  ✘  1 driveView.spec.ts:8:6 › drive view (11.7s)
  ✓  2 delete.spec.ts:8:6 › delete and restore (3.6s)
  ✓  3 changePasswordModal.spec.ts:8:6 › change password modal (3.5s)
  ✓  4 assetPanel.spec.ts:9:6 › open and close asset panel (3.8s)
  ✓  5 createAsset.spec.ts:8:6 › create folder (2.8s)
  ✓  6 copy.spec.ts:8:6 › copy (3.5s)
  ✓  7 createAsset.spec.ts:18:6 › create project (897ms)
  ✓  8 homePage.spec.ts:8:6 › create empty project (1.3s)
  ✘  9 copy.spec.ts:32:6 › copy (keyboard) (6.7s)
  ✘  10 delete.spec.ts:31:6 › delete and restore (keyboard) (6.6s)
  ✓  11 createAsset.spec.ts:27:6 › upload file (1.1s)
  ✓  12 assetPanel.spec.ts:22:6 › asset panel contents (1.6s)
  ✓  13 homePage.spec.ts:15:6 › create project from template (1.0s)
  ✓  14 createAsset.spec.ts:48:6 › create secret (1.0s)
  ✓  15 labelsPanel.spec.ts:8:6 › labels (1.8s)
  ✓  16 loginLogout.spec.ts:13:6 › login and logout (1.5s)
  ✓  17 loginScreen.spec.ts:12:6 › login screen (787ms)
  ✓  18 signUpFlow.spec.ts:10:6 › sign up flow (1.2s)
  ✓  19 signUpWithOrganizationId.spec.ts:12:6 › sign up with organization id (5.6s)
  ✓  20 signUpWithoutOrganizationId.spec.ts:10:6 › sign up without organization id (1.2s)
  ✓  21 sort.spec.ts:14:6 › sort (1.6s)
  ✓  22 userMenu.spec.ts:8:6 › user menu (691ms)
  ✓  23 userMenu.spec.ts:14:6 › download app (1.8s)
  ✓  24 copy.spec.ts:53:6 › move (1.2s)
  ✓  25 copy.spec.ts:77:6 › move (drag) (956ms)
  ✘  26 copy.spec.ts:94:6 › move (keyboard) (5.8s)
  ✓  27 copy.spec.ts:115:6 › duplicate (864ms)
  ✘  28 copy.spec.ts:130:6 › duplicate (keyboard) (5.7s)


  1) copy.spec.ts:32:6 › copy (keyboard) ───────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveCount(expected)

    Locator: getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
    Expected: 3
    Received: 2
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"


      43 |     await actions.press(page, 'Mod+V')
      44 |     // Assets: [0: Folder 2, 1: Folder 1, 2: Folder 2 (copy) <child { depth=1 }>]
    > 45 |     await test.expect(assetRows).toHaveCount(3)
         |                                  ^
      46 |     await test.expect(assetRows.nth(2)).toBeVisible()
      47 |     await test.expect(assetRows.nth(2)).toHaveText(/^New_Folder_2 [(]copy[)]/)
      48 |     const parentLeft = await actions.getAssetRowLeftPx(assetRows.nth(1))

        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/copy.spec.ts:45:34

  2) copy.spec.ts:94:6 › move (keyboard) ───────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

    Locator: getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row').nth(1)
    Expected pattern: /^New_Folder_2/
    Received string:  "New_Folder_12045-01-23, 01:23user name"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row').nth(1)
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"


      107 |     await test.expect(assetRows).toHaveCount(2)
      108 |     await test.expect(assetRows.nth(1)).toBeVisible()
    > 109 |     await test.expect(assetRows.nth(1)).toHaveText(/^New_Folder_2/)
          |                                         ^
      110 |     const parentLeft = await actions.getAssetRowLeftPx(assetRows.nth(0))
      111 |     const childLeft = await actions.getAssetRowLeftPx(assetRows.nth(1))
      112 |     test.expect(childLeft, 'child is indented further than parent').toBeGreaterThan(parentLeft)

        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/copy.spec.ts:109:41

  3) copy.spec.ts:130:6 › duplicate (keyboard) ─────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveCount(expected)

    Locator: getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
    Expected: 2
    Received: 1
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"
      -   locator resolved to 1 element
      -   unexpected value "1"


      136 |     await actions.press(page, 'Mod+D')
      137 |     // Assets: [0: Folder 1 (copy), 1: Folder 1]
    > 138 |     await test.expect(assetRows).toHaveCount(2)
          |                                  ^
      139 |     await test.expect(assetRows.nth(0)).toBeVisible()
      140 |     await test.expect(assetRows.nth(0)).toHaveText(/^New_Folder_1 [(]copy[)]/)
      141 | })

        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/copy.spec.ts:138:34

  4) delete.spec.ts:31:6 › delete and restore (keyboard) › Expect placeholder row ──────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

    Locator: getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
    Expected pattern: /You have no files/
    Received string:  "New_Folder_12045-01-23, 01:23user name"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"
      -   locator resolved to <tr tabindex="-1" draggable="true" class="h-8 transi…>…</tr>
      -   unexpected value "New_Folder_12045-01-23, 01:23user name"


       at actions.ts:489

      487 |     await test.test.step('Expect placeholder row', async () => {
      488 |         await test.expect(assetRows).toHaveCount(1)
    > 489 |         await test.expect(assetRows).toHaveText(/You have no files/)
          |                                      ^
      490 |     })
      491 | }
      492 |

        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/actions.ts:489:38
        at Module.expectPlaceholderRow (/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/actions.ts:487:5)
        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/delete.spec.ts:39:5

  5) driveView.spec.ts:8:6 › drive view ────────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveCount(expected)

    Locator: getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
    Expected: 2
    Received: 0
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByTestId('drive-view').getByRole('table').locator('tbody').getByRole('row')
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"
      -   locator resolved to 0 elements
      -   unexpected value "0"


      19 |     await actions.locateDrivePageIcon(page).click()
      20 |     await actions.locateNewProjectButton(page).click()
    > 21 |     await test.expect(assetRows).toHaveCount(2)
         |                                  ^
      22 |     await actions.locateDrivePageIcon(page).click()
      23 |     // The last opened project needs to be stopped, to remove the toast notification notifying the
      24 |     // user that project creation may take a while. Previously opened projects are stopped when the

        at /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard/e2e/driveView.spec.ts:21:34

  Slow test file: copy.spec.ts (24.7s)
  Consider splitting slow test files to speed up parallel execution
  5 failed
    copy.spec.ts:32:6 › copy (keyboard) ────────────────────────────────────────────────────────────
    copy.spec.ts:94:6 › move (keyboard) ────────────────────────────────────────────────────────────
    copy.spec.ts:130:6 › duplicate (keyboard) ──────────────────────────────────────────────────────
    delete.spec.ts:31:6 › delete and restore (keyboard) ────────────────────────────────────────────
    driveView.spec.ts:8:6 › drive view ─────────────────────────────────────────────────────────────
  23 passed (27.3s)
npm ERR! Lifecycle script `test:e2e` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: enso-dashboard@0.1.0
npm ERR!   at location: /Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/dashboard
```

**Comment by somebody1234** [comment]
@PabloBuchu I think this is due to race conditions because of differing settings between CI's Playwright settings and dev playwright settings. I've now changed to use CI settings for the time being, since a full run of every single E2E test currently takes ~90 seconds, which I'd assume is fine, especially if it gets run in the background alongside regular QA

(The main difference for Playwright defaults is that locally multiple tests are run in parallel, whereas on CI they are run in series, and retried up to 2 times (1 to 3 tries))

**Comment by somebody1234** [comment]
@ GUI team:
the only relevant change in the GUI codebase is here:
<https://github.com/enso-org/enso/pull/8730/files?w=1#diff-c5852711dc7adeceba6b07c1e107debad653bb57871578ea98833f7c90e5a390>

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/8730">More E2E tests; `export default` classes from modules by somebody1234 · Pull Request #8730 · enso-org/enso</a></strong></div><div>Pull Request Description
This is a prerequisite for adding a CI action for E2E tests.

Fix E2E tests
Remove visual regression testing (VRT) and associated fixtures (screenshots) for now
Switch dash...</div></blockquote>

**Comment by somebody1234** [comment]
all tests now pass :D

**Review by Frizi — APPROVED** [review]

**Comment by somebody1234** [comment]
note that the approval above is specifically for the one line of change in GUI2 code:
<https://github.com/enso-org/enso/pull/8730/files?w=1#diff-c5852711dc7adeceba6b07c1e107debad653bb57871578ea98833f7c90e5a390>

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/8730">More E2E tests; `export default` classes from modules by somebody1234 · Pull Request #8730 · enso-org/enso</a></strong></div><div>Pull Request Description
This is a prerequisite for adding a CI action for E2E tests.

Fix E2E tests
Remove visual regression testing (VRT) and associated fixtures (screenshots) for now
Switch dash...</div></blockquote>

**Comment by PabloBuchu** [comment]
Still failing with 14 tests thou
Screenshot 2024-01-25 at 10 24 11
Screenshot 2024-01-25 at 10 24 03

**Comment by somebody1234** [comment]
rip... i could swear they were all passing last time i checked, i wonder what happened. i'll look into it soonish

**Comment by PabloBuchu** [comment]
Still some errors

Screenshot 2024-01-25 at 16 15 37

**Comment by somebody1234** [comment]
ahh... yeah i suspect i know what's going on here. probably another issue with keypresses, because macos uses `Backspace` instead of `Delete`. should be an easy fix.

**Comment by somebody1234** [comment]
@PabloBuchu that should finally be fixed now too

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
