### PR TITLE
Make Asset Table selection backend specific

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix https://github.com/enso-org/cloud-v2/issues/1542
  - Ignore selection (and clear target directory) when the selection is for a different backend

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
not sure whether this makes sense tbh. i think we should be checking category instead because it still doesn't make sense to add to the "selected" directory if it's a selection from a different category (= not visible) in the current view

@MrFlashAccount thoughts? (also feel free to (re-?)take this task, especially since idk whether this is the correct approach at all due to the issues raised above)

**Comment by MrFlashAccount** [comment]
@somebody1234 my initial thought was to reset the selection and active folder entirely when we jump between categories. Thoughs?

**Comment by somebody1234** [comment]
@MrFlashAccount i guess that makes sense... on the other hand paste data would only be cleared when changing backend?

**Comment by MrFlashAccount** [comment]
@somebody1234 I think so even though it might confuse users (e.g. user hit ctrl+c, switch backend, hit ctrl+v -> nothing happens). If it's easy to do, maybe we should validate if it's possibe to paste inside the current context (selected folder, selected category) on pasting and display a notification if we're unable to paste?

**Comment by somebody1234** [comment]
true - i'm not against pasting across categories/backends but i guess i wanted to have some UI to tell the user that <X> assets are currently copied. we have logic to detect whether an asset drag is valid already, we can probably extract and re-use for copy-paste across categories/backends

**Comment by PabloBuchu** [comment]
So is this ready for QA? I remember you were saying to are working on more specific fix?

**Comment by somebody1234** [comment]
@PabloBuchu selection functionality should be done, the force-push switched to the new approach. i think there are still a few bugs with pasting *between* categories though, although it *shouldn't* affect copy-paste and cut-paste within a single category (on one hand, if it's broken then that's a regression, on the other hand it might be better if i test it... later today or something)

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@somebody1234 copy paste (with context menu) between user-team space doesn't send any request to the backend. moving assets throws 403 which is a bug on backend

**Comment by somebody1234** [comment]
@PabloBuchu thoughts? should we still merge this anyway and fix copy-paste across categories in a later PR?
(i guess we should check whether it's a regression at least?)
(or should we disable copy-paste across categories for now?)

**Pull request merged**
