### PR TITLE
Fix background color

### LINKED ISSUE #10393: Update dashboard bg color to match Figma
In Figma there's a semi-transparent color (#F4F6F799) overlayed on top of the background image (see: app > window > 2nd "window"); this layer seems to be the difference between the application bg color seen in Figma and our current color.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix #10393
  - Use correct background color
- Make background of Asset Panel white to match Figma design

### Important Notes
None

### Screenshots

Before:
image

After:
image

Search bar outline:
image

Search bar outline in settings:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
I am not an designer but wouldn't it be better to make `Asset Panel` the same colour as bg and just make a vertical line between dashboard and the panel to mark those are different zones. Right now it has a 3rd colour which doesn't occur anywhere else in dashboard. @MrFlashAccount wdyt?

Screenshot 2024-06-28 at 09 24 09

1. With new Asset Panel color the `Versions` and `Sessions` buttons are invisible... the same when you want to update description.
2. When you open panel it slides from the left nicely from the right.. When you close the content disappear and you see the blank panel slowly fading. How hard would it be to implement sliding to the right with content in it (so it looks like true side panel)?

**Review by MrFlashAccount — APPROVED** [review]

**Comment by MrFlashAccount** [comment]
@PabloBuchu This panel needs a stronger shadow to match the current design, making it the same color isn't necessary

**Comment by MrFlashAccount** [comment]
Searchbar/User "cloud" should have #fff bg 
CleanShot 2024-06-28 at 10 45 27@2x

**Comment by somebody1234** [comment]
> Searchbar/User "cloud" should have #fff bg

not sure about this. i think it would be more consistent to switch to an outline to match with the assets table search bar. @MrFlashAccount thoughts?

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
