### PR TITLE
Copy Figma design for Cloud Dashboard

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes [cloud-v2/#523](https://github.com/enso-org/cloud-v2/issues/523)
- Changes cloud directory breadcrumbs to show the full path, instead of the two last directories
- Adds rounded borders to rows
- Adds on-hover effects to template buttons

Implements type-to-search without having to click on the search bar first

### Important Notes
It's not a perfect replication of the Figma design, but I think (most of) the rest of the changes are more difficult to add and/or debug.

Main differences:
- Some features not in the Figma design (e.g. collapsible templates list, context menus)
  - Note: context menus were not changed
- Slight differences in spacing for the header rows of the assets tables
- The background for the rows of the assets tables extends too far
  - Not sure this one is possible without a lot of magic actually
    - The rounded background is currently on the row itself - which makes things really simple, but also very different from the Figma design
    - Changing this may require some JS code to find the last column containing an entry. Alternatively, using absolute positioning (+ max-width?) for each column may work

### Screenshots
Template button being hovered:
image

Drive bar with a hovered directory in the breadcrumbs display
image

Projects list with:
- An odd-indexed row
- An even-indexed row
- A hovered row
- A selected row
in that order
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
@somebody1234 I am unable to build GUI
```
/Users/pawelbuchowski/projects/enso/app/ide-desktop/lib/content/src/index.ts
 INFO ide_ci::program::command: npmℹ️   191:17  error  Unnecessary conditional, the types have no overlap  @typescript-eslint/no-unnecessary-condition
 INFO ide_ci::program::command: npmℹ️   191:53  error  Unnecessary optional chain on a non-nullish value   @typescript-eslint/no-unnecessary-condition
```

**Comment by somebody1234** [comment]
fixes (+ style fixes and changes to the auth flow UI) pushed

**Comment by PabloBuchu** [comment]
1. On hover is square finished at the right end. On the left it ends much closer to the icon. On the right we should draw it to the end of the screen
Screenshot 2023-07-13 at 11 37 25
2. Is the gap between `Drive` and table the same as in figma? Looks too close 
3. 
| Changes cloud directory breadcrumbs to show the full path, instead of the two last directories
Where this came from? Not sure if the infinite breadcrumbs is a good idea. When there is 3 element in breadcrumbs and user is about to entry 4th lets show `... -> grand parent -> parent-> current `
Screenshot 2023-07-13 at 11 42 54
4. Do the font color matches the figma `#3E515F`?

**Comment by somebody1234** [comment]
1. actually i think it should be have rounded borders on the right too - see the second highlighted row. i think it's just square there because that row goes past the right edge of the screen
    - (side note: i'm assuming that's the "even rows" style, because i don't think it's possible to hover two rows at the same time)
    - on the left it ends much closer - i think i did mention this in the original post. not 100% sure what's the best way to do things as each column has a... 2rem? padding?
      - actually i guess the name column should be specialcased anyway because it's not supposed to have left padding.
      - the background extending too far on the right side is still an issue though
2. will check later
3. good point... what about `cloud > ... > parent > directory`? i think being able to go back to the top immediately is kinda useful
4. it should. it has a different hex code here but that's because the font is at 90% opacity in figma. ideally we'd use that exact color but tailwind does not like alpha in its basecolors

**Comment by somebody1234** [comment]
oh re: the "where did the infinite breadcrumbs come from" - i had implemented it as the last two directories only, but after closer inspection i realized `cloud` is (probably) the name of the root directory

**Comment by PabloBuchu** [comment]
ad 3 yeah thats good idea lets do that

**Comment by somebody1234** [comment]
re: 2... not pixel perfect but i think it's pretty close. if your experience differs (e.g. differences due to macos) then screenshots would be helpful
image

**Comment by PabloBuchu** [comment]
One minor thing on the login page
Screenshot 2023-07-14 at 11 01 32

**Comment by xvcgreg** [comment]
@somebody1234 what's the holdup here?

**Pull request closed without merging**
