### PR TITLE
Add benchmarks for `==` and work days

### PR DESCRIPTION
**Pull request by radeusgd**
[ci no changelog needed]

### Pull Request Description

There are a few operations whose timing we'd like to measure.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
How shall one run the benchmark? Just `enso --run test/Benchmarks/src/Equality.enso`?

**Comment by radeusgd** [comment]
> How shall one run the benchmark? Just `enso --run test/Benchmarks/src/Equality.enso`?

Normally, I'm using the launcher so I'd do `enso run test/Benchmarks/src/Equality.enso`.

If you are using just the engine-runner, I think this needs to be `enso --in-project test/Benchmarks/ --run test/Benchmarks/src/Equality.enso`. But that's still the completely standard way to run an Enso file within a project (still I recommend to use the launcher to not have to think about these parameters too much, it detects projects automatically; the engine-runner frontend is mostly meant to be reserved for internal use only - well, unless something changed in the meantime).

**Comment by radeusgd** [comment]
We discussed with @mwu-tow that we may get a way to [dispatch Enso benchmark runs on our benchmark machine](https://www.pivotaltracker.com/story/show/183363770).

Until then, I've ran the benchmarks on my machine to get a general feeling of performance of each method - since most compare performance of various methods we can compare relative measurements which should not depend greatly on the specs.

Posting here the results for work days:
```
(Shift=1) work_days_until/iteration:0: 61.71ms
(Shift=1) work_days_until/iteration:1: 22.37ms
(Shift=1) work_days_until/iteration:2: 11.71ms
(Shift=1) work_days_until/iteration:3: 8.78ms
(Shift=1) work_days_until/iteration:4: 8.51ms
(Shift=1) work_days_until/iteration:5: 8.22ms
(Shift=1) work_days_until/iteration:6: 8.30ms
(Shift=1) work_days_until/iteration:7: 7.45ms
(Shift=1) work_days_until/iteration:8: 6.71ms
(Shift=1) work_days_until/iteration:9: 6.42ms
(Shift=1) work_days_until with holidays/iteration:0: 219.18ms
(Shift=1) work_days_until with holidays/iteration:1: 101.42ms
(Shift=1) work_days_until with holidays/iteration:2: 89.27ms
(Shift=1) work_days_until with holidays/iteration:3: 88.52ms
(Shift=1) work_days_until with holidays/iteration:4: 91.60ms
(Shift=1) work_days_until with holidays/iteration:5: 82.48ms
(Shift=1) work_days_until with holidays/iteration:6: 33.90ms
(Shift=1) work_days_until with holidays/iteration:7: 33.78ms
(Shift=1) work_days_until with holidays/iteration:8: 37.64ms
(Shift=1) work_days_until with holidays/iteration:9: 36.08ms
(Shift=1) add regular days/iteration:0: 1.40ms
(Shift=1) add regular days/iteration:1: 1.30ms
(Shift=1) add regular days/iteration:2: 2.14ms
(Shift=1) add regular days/iteration:3: 1.65ms
(Shift=1) add regular days/iteration:4: 1.38ms
(Shift=1) add regular days/iteration:5: 1.37ms
(Shift=1) add regular days/iteration:6: 1.39ms
(Shift=1) add regular days/iteration:7: 1.27ms
(Shift=1) add regular days/iteration:8: 0.98ms
(Shift=1) add regular days/iteration:9: 0.74ms
(Shift=1) add work days/iteration:0: 26.29ms
(Shift=1) add work days/iteration:1: 15.17ms
(Shift=1) add work days/iteration:2: 12.58ms
(Shift=1) add work days/iteration:3: 11.70ms
(Shift=1) add work days/iteration:4: 10.61ms
(Shift=1) add work days/iteration:5: 10.66ms
(Shift=1) add work days/iteration:6: 10.49ms
(Shift=1) add work days/iteration:7: 10.77ms
(Shift=1) add work days/iteration:8: 10.43ms
(Shift=1) add work days/iteration:9: 10.40ms
(Shift=1) add work days with holidays/iteration:0: 128.45ms
(Shift=1) add work days with holidays/iteration:1: 63.53ms
(Shift=1) add work days with holidays/iteration:2: 62.41ms
(Shift=1) add work days with holidays/iteration:3: 60.45ms
(Shift=1) add work days with holidays/iteration:4: 60.37ms
(Shift=1) add work days with holidays/iteration:5: 67.81ms
(Shift=1) add work days with holidays/iteration:6: 70.56ms
(Shift=1) add work days with holidays/iteration:7: 60.94ms
(Shift=1) add work days with holidays/iteration:8: 58.14ms
(Shift=1) add work days with holidays/iteration:9: 59.00ms
(Shift=5) work_days_until/iteration:0: 3.08ms
(Shift=5) work_days_until/iteration:1: 2.94ms
(Shift=5) work_days_until/iteration:2: 2.92ms
(Shift=5) work_days_until/iteration:3: 3.06ms
(Shift=5) work_days_until/iteration:4: 2.69ms
(Shift=5) work_days_until/iteration:5: 3.91ms
(Shift=5) work_days_until/iteration:6: 3.02ms
(Shift=5) work_days_until/iteration:7: 2.88ms
(Shift=5) work_days_until/iteration:8: 2.87ms
(Shift=5) work_days_until/iteration:9: 2.82ms
(Shift=5) work_days_until with holidays/iteration:0: 47.42ms
(Shift=5) work_days_until with holidays/iteration:1: 39.36ms
(Shift=5) work_days_until with holidays/iteration:2: 38.28ms
(Shift=5) work_days_until with holidays/iteration:3: 37.26ms
(Shift=5) work_days_until with holidays/iteration:4: 36.90ms
(Shift=5) work_days_until with holidays/iteration:5: 38.10ms
(Shift=5) work_days_until with holidays/iteration:6: 37.34ms
(Shift=5) work_days_until with holidays/iteration:7: 37.84ms
(Shift=5) work_days_until with holidays/iteration:8: 37.55ms
(Shift=5) work_days_until with holidays/iteration:9: 36.09ms
(Shift=5) add regular days/iteration:0: 0.29ms
(Shift=5) add regular days/iteration:1: 0.41ms
(Shift=5) add regular days/iteration:2: 0.31ms
(Shift=5) add regular days/iteration:3: 0.31ms
(Shift=5) add regular days/iteration:4: 0.31ms
(Shift=5) add regular days/iteration:5: 0.32ms
(Shift=5) add regular days/iteration:6: 0.32ms
(Shift=5) add regular days/iteration:7: 0.33ms
(Shift=5) add regular days/iteration:8: 0.31ms
(Shift=5) add regular days/iteration:9: 0.33ms
(Shift=5) add work days/iteration:0: 4.99ms
(Shift=5) add work days/iteration:1: 4.89ms
(Shift=5) add work days/iteration:2: 4.98ms
(Shift=5) add work days/iteration:3: 5.19ms
(Shift=5) add work days/iteration:4: 4.44ms
(Shift=5) add work days/iteration:5: 4.89ms
(Shift=5) add work days/iteration:6: 5.43ms
(Shift=5) add work days/iteration:7: 4.75ms
(Shift=5) add work days/iteration:8: 4.93ms
(Shift=5) add work days/iteration:9: 4.86ms
(Shift=5) add work days with holidays/iteration:0: 89.24ms
(Shift=5) add work days with holidays/iteration:1: 88.03ms
(Shift=5) add work days with holidays/iteration:2: 82.50ms
(Shift=5) add work days with holidays/iteration:3: 83.03ms
(Shift=5) add work days with holidays/iteration:4: 83.62ms
(Shift=5) add work days with holidays/iteration:5: 80.02ms
(Shift=5) add work days with holidays/iteration:6: 80.61ms
(Shift=5) add work days with holidays/iteration:7: 78.57ms
(Shift=5) add work days with holidays/iteration:8: 78.44ms
(Shift=5) add work days with holidays/iteration:9: 81.49ms
(Shift=20) work_days_until/iteration:0: 5.09ms
(Shift=20) work_days_until/iteration:1: 2.77ms
(Shift=20) work_days_until/iteration:2: 2.87ms
(Shift=20) work_days_until/iteration:3: 2.82ms
(Shift=20) work_days_until/iteration:4: 2.85ms
(Shift=20) work_days_until/iteration:5: 2.67ms
(Shift=20) work_days_until/iteration:6: 2.70ms
(Shift=20) work_days_until/iteration:7: 2.59ms
(Shift=20) work_days_until/iteration:8: 2.50ms
(Shift=20) work_days_until/iteration:9: 2.50ms
(Shift=20) work_days_until with holidays/iteration:0: 49.00ms
(Shift=20) work_days_until with holidays/iteration:1: 42.54ms
(Shift=20) work_days_until with holidays/iteration:2: 42.72ms
(Shift=20) work_days_until with holidays/iteration:3: 41.23ms
(Shift=20) work_days_until with holidays/iteration:4: 40.71ms
(Shift=20) work_days_until with holidays/iteration:5: 42.66ms
(Shift=20) work_days_until with holidays/iteration:6: 41.11ms
(Shift=20) work_days_until with holidays/iteration:7: 42.29ms
(Shift=20) work_days_until with holidays/iteration:8: 42.27ms
(Shift=20) work_days_until with holidays/iteration:9: 41.74ms
(Shift=20) add regular days/iteration:0: 0.26ms
(Shift=20) add regular days/iteration:1: 0.26ms
(Shift=20) add regular days/iteration:2: 0.27ms
(Shift=20) add regular days/iteration:3: 0.27ms
(Shift=20) add regular days/iteration:4: 0.28ms
(Shift=20) add regular days/iteration:5: 0.27ms
(Shift=20) add regular days/iteration:6: 0.25ms
(Shift=20) add regular days/iteration:7: 0.27ms
(Shift=20) add regular days/iteration:8: 0.27ms
(Shift=20) add regular days/iteration:9: 0.27ms
(Shift=20) add work days/iteration:0: 4.49ms
(Shift=20) add work days/iteration:1: 4.28ms
(Shift=20) add work days/iteration:2: 4.46ms
(Shift=20) add work days/iteration:3: 4.26ms
(Shift=20) add work days/iteration:4: 4.28ms
(Shift=20) add work days/iteration:5: 4.29ms
(Shift=20) add work days/iteration:6: 4.38ms
(Shift=20) add work days/iteration:7: 4.18ms
(Shift=20) add work days/iteration:8: 4.39ms
(Shift=20) add work days/iteration:9: 4.21ms
(Shift=20) add work days with holidays/iteration:0: 102.10ms
(Shift=20) add work days with holidays/iteration:1: 101.25ms
(Shift=20) add work days with holidays/iteration:2: 102.03ms
(Shift=20) add work days with holidays/iteration:3: 104.65ms
(Shift=20) add work days with holidays/iteration:4: 105.10ms
(Shift=20) add work days with holidays/iteration:5: 104.50ms
(Shift=20) add work days with holidays/iteration:6: 105.69ms
(Shift=20) add work days with holidays/iteration:7: 102.34ms
(Shift=20) add work days with holidays/iteration:8: 102.22ms
(Shift=20) add work days with holidays/iteration:9: 104.16ms
(Shift=100) work_days_until/iteration:0: 2.48ms
(Shift=100) work_days_until/iteration:1: 2.43ms
(Shift=100) work_days_until/iteration:2: 2.40ms
(Shift=100) work_days_until/iteration:3: 2.46ms
(Shift=100) work_days_until/iteration:4: 2.45ms
(Shift=100) work_days_until/iteration:5: 2.44ms
(Shift=100) work_days_until/iteration:6: 2.40ms
(Shift=100) work_days_until/iteration:7: 2.52ms
(Shift=100) work_days_until/iteration:8: 2.42ms
(Shift=100) work_days_until/iteration:9: 2.40ms
(Shift=100) work_days_until with holidays/iteration:0: 73.06ms
(Shift=100) work_days_until with holidays/iteration:1: 65.82ms
(Shift=100) work_days_until with holidays/iteration:2: 62.86ms
(Shift=100) work_days_until with holidays/iteration:3: 64.74ms
(Shift=100) work_days_until with holidays/iteration:4: 63.56ms
(Shift=100) work_days_until with holidays/iteration:5: 62.33ms
(Shift=100) work_days_until with holidays/iteration:6: 62.67ms
(Shift=100) work_days_until with holidays/iteration:7: 62.08ms
(Shift=100) work_days_until with holidays/iteration:8: 62.21ms
(Shift=100) work_days_until with holidays/iteration:9: 62.78ms
(Shift=100) add regular days/iteration:0: 0.27ms
(Shift=100) add regular days/iteration:1: 0.27ms
(Shift=100) add regular days/iteration:2: 0.27ms
(Shift=100) add regular days/iteration:3: 0.27ms
(Shift=100) add regular days/iteration:4: 0.27ms
(Shift=100) add regular days/iteration:5: 0.27ms
(Shift=100) add regular days/iteration:6: 0.27ms
(Shift=100) add regular days/iteration:7: 0.27ms
(Shift=100) add regular days/iteration:8: 0.27ms
(Shift=100) add regular days/iteration:9: 0.27ms
(Shift=100) add work days/iteration:0: 3.79ms
(Shift=100) add work days/iteration:1: 3.81ms
(Shift=100) add work days/iteration:2: 3.79ms
(Shift=100) add work days/iteration:3: 3.81ms
(Shift=100) add work days/iteration:4: 3.79ms
(Shift=100) add work days/iteration:5: 3.78ms
(Shift=100) add work days/iteration:6: 3.82ms
(Shift=100) add work days/iteration:7: 3.81ms
(Shift=100) add work days/iteration:8: 3.80ms
(Shift=100) add work days/iteration:9: 3.91ms
(Shift=100) add work days with holidays/iteration:0: 158.13ms
(Shift=100) add work days with holidays/iteration:1: 153.87ms
(Shift=100) add work days with holidays/iteration:2: 157.10ms
(Shift=100) add work days with holidays/iteration:3: 155.27ms
(Shift=100) add work days with holidays/iteration:4: 154.26ms
(Shift=100) add work days with holidays/iteration:5: 149.81ms
(Shift=100) add work days with holidays/iteration:6: 150.48ms
(Shift=100) add work days with holidays/iteration:7: 151.58ms
(Shift=100) add work days with holidays/iteration:8: 151.39ms
(Shift=100) add work days with holidays/iteration:9: 151.51ms
```

image
image
image

(note that one iteration involves 1000 date operations of the specific kind)

We can see that the majority of the computation cost is due to the `work_days_until` function with holidays - as it needs to traverse all holidays (and we inserted many entries) and perform deduplication at the end.

**Comment by radeusgd** [comment]
For the record, the equality benchmarks on my machine:

```
Integer Equality/iteration:0: 13.43ms
Integer Equality/iteration:1: 0.55ms
Integer Equality/iteration:2: 0.42ms
Integer Equality/iteration:3: 0.40ms
Integer Equality/iteration:4: 0.37ms
Integer Equality/iteration:5: 0.37ms
Integer Equality/iteration:6: 0.48ms
Integer Equality/iteration:7: 0.36ms
Integer Equality/iteration:8: 0.35ms
Integer Equality/iteration:9: 0.37ms
Boolean Equality/iteration:0: 14.71ms
Boolean Equality/iteration:1: 0.24ms
Boolean Equality/iteration:2: 0.25ms
Boolean Equality/iteration:3: 0.24ms
Boolean Equality/iteration:4: 0.24ms
Boolean Equality/iteration:5: 0.24ms
Boolean Equality/iteration:6: 0.24ms
Boolean Equality/iteration:7: 0.24ms
Boolean Equality/iteration:8: 0.24ms
Boolean Equality/iteration:9: 0.23ms
Text Equality/iteration:0: 23.58ms
Text Equality/iteration:1: 4.72ms
Text Equality/iteration:2: 4.68ms
Text Equality/iteration:3: 4.55ms
Text Equality/iteration:4: 3.94ms
Text Equality/iteration:5: 3.88ms
Text Equality/iteration:6: 3.96ms
Text Equality/iteration:7: 4.19ms
Text Equality/iteration:8: 4.87ms
Text Equality/iteration:9: 5.05ms
Date Equality/iteration:0: 33.19ms
Date Equality/iteration:1: 7.88ms
Date Equality/iteration:2: 7.44ms
Date Equality/iteration:3: 7.31ms
Date Equality/iteration:4: 7.07ms
Date Equality/iteration:5: 6.71ms
Date Equality/iteration:6: 7.37ms
Date Equality/iteration:7: 6.97ms
Date Equality/iteration:8: 6.71ms
Date Equality/iteration:9: 6.66ms
Date_Time Equality/iteration:0: 31.95ms
Date_Time Equality/iteration:1: 17.31ms
Date_Time Equality/iteration:2: 18.46ms
Date_Time Equality/iteration:3: 18.03ms
Date_Time Equality/iteration:4: 18.22ms
Date_Time Equality/iteration:5: 18.18ms
Date_Time Equality/iteration:6: 18.56ms
Date_Time Equality/iteration:7: 16.92ms
Date_Time Equality/iteration:8: 16.89ms
Date_Time Equality/iteration:9: 17.05ms
Custom Atom Equality - single constructor/iteration:0: 119.21ms
Custom Atom Equality - single constructor/iteration:1: 65.80ms
Custom Atom Equality - single constructor/iteration:2: 62.44ms
Custom Atom Equality - single constructor/iteration:3: 61.85ms
Custom Atom Equality - single constructor/iteration:4: 60.67ms
Custom Atom Equality - single constructor/iteration:5: 60.61ms
Custom Atom Equality - single constructor/iteration:6: 63.85ms
Custom Atom Equality - single constructor/iteration:7: 54.31ms
Custom Atom Equality - single constructor/iteration:8: 52.50ms
Custom Atom Equality - single constructor/iteration:9: 52.66ms
Custom Atom Equality - 2 constructors without data/iteration:0: 83.62ms
Custom Atom Equality - 2 constructors without data/iteration:1: 26.62ms
Custom Atom Equality - 2 constructors without data/iteration:2: 15.03ms
Custom Atom Equality - 2 constructors without data/iteration:3: 15.38ms
Custom Atom Equality - 2 constructors without data/iteration:4: 15.16ms
Custom Atom Equality - 2 constructors without data/iteration:5: 15.32ms
Custom Atom Equality - 2 constructors without data/iteration:6: 15.96ms
Custom Atom Equality - 2 constructors without data/iteration:7: 15.86ms
Custom Atom Equality - 2 constructors without data/iteration:8: 15.74ms
Custom Atom Equality - 2 constructors without data/iteration:9: 15.86ms
Custom Atom Equality - 2 constructors with data/iteration:0: 76.63ms
Custom Atom Equality - 2 constructors with data/iteration:1: 56.09ms
Custom Atom Equality - 2 constructors with data/iteration:2: 55.49ms
Custom Atom Equality - 2 constructors with data/iteration:3: 54.49ms
Custom Atom Equality - 2 constructors with data/iteration:4: 55.78ms
Custom Atom Equality - 2 constructors with data/iteration:5: 55.24ms
Custom Atom Equality - 2 constructors with data/iteration:6: 57.10ms
Custom Atom Equality - 2 constructors with data/iteration:7: 51.62ms
Custom Atom Equality - 2 constructors with data/iteration:8: 49.06ms
Custom Atom Equality - 2 constructors with data/iteration:9: 49.21ms
Java Polyglot ==/iteration:0: 154.09ms
Java Polyglot ==/iteration:1: 84.89ms
Java Polyglot ==/iteration:2: 83.73ms
Java Polyglot ==/iteration:3: 83.99ms
Java Polyglot ==/iteration:4: 84.82ms
Java Polyglot ==/iteration:5: 83.82ms
Java Polyglot ==/iteration:6: 86.82ms
Java Polyglot ==/iteration:7: 67.69ms
Java Polyglot ==/iteration:8: 66.75ms
Java Polyglot ==/iteration:9: 66.78ms
Java Polyglot .equals/iteration:0: 18.39ms
Java Polyglot .equals/iteration:1: 7.27ms
Java Polyglot .equals/iteration:2: 7.16ms
Java Polyglot .equals/iteration:3: 7.12ms
Java Polyglot .equals/iteration:4: 7.13ms
Java Polyglot .equals/iteration:5: 7.20ms
Java Polyglot .equals/iteration:6: 7.75ms
Java Polyglot .equals/iteration:7: 7.19ms
Java Polyglot .equals/iteration:8: 7.03ms
Java Polyglot .equals/iteration:9: 6.91ms
```

image


[The relevant task on Pivotal](https://www.pivotaltracker.com/story/show/183369386) for investigating and improving performance of `==`.

**Comment by radeusgd** [comment]
Vector.distinct benchmark results from my machine:

```
Random Integer Vector Distinct/iteration:0: 103.85ms
Random Integer Vector Distinct/iteration:1: 49.90ms
Random Integer Vector Distinct/iteration:2: 45.95ms
Random Integer Vector Distinct/iteration:3: 45.26ms
Random Integer Vector Distinct/iteration:4: 45.19ms
Random Integer Vector Distinct/iteration:5: 45.35ms
Random Integer Vector Distinct/iteration:6: 53.62ms
Random Integer Vector Distinct/iteration:7: 56.81ms
Random Integer Vector Distinct/iteration:8: 77.68ms
Random Integer Vector Distinct/iteration:9: 73.30ms
Uniform Integer Vector Distinct/iteration:0: 13.08ms
Uniform Integer Vector Distinct/iteration:1: 8.95ms
Uniform Integer Vector Distinct/iteration:2: 8.75ms
Uniform Integer Vector Distinct/iteration:3: 9.17ms
Uniform Integer Vector Distinct/iteration:4: 2.17ms
Uniform Integer Vector Distinct/iteration:5: 1.80ms
Uniform Integer Vector Distinct/iteration:6: 1.63ms
Uniform Integer Vector Distinct/iteration:7: 1.62ms
Uniform Integer Vector Distinct/iteration:8: 1.60ms
Uniform Integer Vector Distinct/iteration:9: 1.62ms
Random Text Vector Distinct/iteration:0: 836.41ms
Random Text Vector Distinct/iteration:1: 336.69ms
Random Text Vector Distinct/iteration:2: 260.80ms
Random Text Vector Distinct/iteration:3: 241.56ms
Random Text Vector Distinct/iteration:4: 228.33ms
Random Text Vector Distinct/iteration:5: 210.29ms
Random Text Vector Distinct/iteration:6: 221.17ms
Random Text Vector Distinct/iteration:7: 189.75ms
Random Text Vector Distinct/iteration:8: 172.59ms
Random Text Vector Distinct/iteration:9: 168.34ms
Uniform Text Vector Distinct/iteration:0: 164.26ms
Uniform Text Vector Distinct/iteration:1: 163.07ms
Uniform Text Vector Distinct/iteration:2: 161.88ms
Uniform Text Vector Distinct/iteration:3: 162.34ms
Uniform Text Vector Distinct/iteration:4: 163.43ms
Uniform Text Vector Distinct/iteration:5: 165.20ms
Uniform Text Vector Distinct/iteration:6: 165.36ms
Uniform Text Vector Distinct/iteration:7: 164.93ms
Uniform Text Vector Distinct/iteration:8: 164.58ms
Uniform Text Vector Distinct/iteration:9: 164.22ms
```

**Review by jdunkerley — APPROVED** [review]

**Pull request merged**
