### PR TITLE
Sentry React integration

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/720
  - Integrate Sentry with React and React Router.

### Important Notes
This is currently BROKEN as it requires the Sentry DSN, otherwise no requests are part of a transaction. Not sure how feasible this is unfortunately, especially as (I'm assuming) it will be different for each backend...
... I guess worst case it can be configured via an environment variable like some other build-time defines.

Also the sampling rates should be checked.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
pinging @indiv0 @PabloBuchu for feedback

**Comment by PabloBuchu** [comment]
@somebody1234 DSN is one `https://0dc7cb80371f466ab88ed01739a7822f@o4504446218338304.ingest.sentry.io/4506070404300800`

Not sure I understand why we should have separate for different backends? We wan't to gather information from react dashboard (as this dns points to dashboard project). We could generate another one for new GUI. Lets add `environment` support https://docs.sentry.io/product/sentry-basics/concepts/environments/ so we can distinguish prod|pb|np

<blockquote><div><strong><a href="https://docs.sentry.io/product/sentry-basics/concepts/environments/">Environments</a></strong></div><div>Learn more about how environments can help you better filter issues, releases, and user feedback in the Issue Details page on sentry.io.</div></blockquote>

**Comment by somebody1234** [comment]
@PabloBuchu ah, good point, i'll see what i can do

**Comment by somebody1234** [comment]
@PabloBuchu okay, DSN and environment should be present now.
this should probably be checked by someone with access to sentry, to make sure that we are logging what we want to log.

specifically, i've specified a low sample rate for both `tracesSampleRate` and `replaysSessionSampleRate`:
https://github.com/enso-org/enso/blob/4d1b35a44a20feea3124d2a2cf9f2a586e2b9426/app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx#L22-L23

https://github.com/enso-org/enso/blob/4d1b35a44a20feea3124d2a2cf9f2a586e2b9426/app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx#L55-L58

they recommend `1.0` for `tracesSampleRate`, which is why it would be good to get confirmation

**Comment by somebody1234** [comment]
i don't think i can do all that much testing but i can confirm a few things indicating that at least *some* things are working correctly:
- `sentry.io/.../envelope` is being sent occasionally
  - it does contain this though: `{"timestamp":1697620165.483,"discarded_events":[{"reason":"sample_rate","category":"transaction","quantity":1}]}`. this might mean the sample rate is too low?
- requests to the backend contain `Sentry-Trace` and `Baggage` headers
- `OPTIONS` cors requests do not contain the sentry headers
- requests to the server serving the webpage on `localhost` do not contain the sentry headers
- requests to cognito do not contain the sentry headers
  - note that the list of domains can be easily changed, so this can be changed if it's incorrect behavior

**Comment by PabloBuchu** [comment]
@indiv0 can you take a look as you played more with sentry on the backend?

**Review by indiv0 — APPROVED** [review]
LGTM. Sample rate should indeed be low because we quickly hit our quota otherwise. I think I've set ours on the backend to 0.001 (so 5x lower than here) but we log a lot more on the backend anyways so this should be fine for now.

We 100% should be using the same DSN on backend and frontend because we want to correlate requests. Also want to add the ability to set the `env` as pawel suggested.

**Comment by somebody1234** [comment]
marking as ready to merge as this changes zero lines of existing logic. self-testing has been done - see above for details

**Pull request merged**
