### PR TITLE
Add Progress Bar For Large Streamed Downloads

### PR DESCRIPTION
**Pull request by indiv0**
### Pull Request Description

This PR adds a progress bar to streamed downloads.

The build script displays a progress bar when downloading from a remote URL in non-streaming mode. It did not display a progress bar when downloading from a URL in streaming mode. Without a progress bar, large downloads in the build script make it appear as through the build script is stuck.

For example, when running with a remote backend source, the `project-manager-bundle` must be downloaded. This bundle is currently >1GB in size, so it takes several minutes to download. To avoid the appearance of the build script being stuck, we add a progress bar.

https://user-images.githubusercontent.com/641547/228154146-12ec8c6b-7027-4dd8-bf0d-6a375764e219.mov

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]
I always wanted it so badly! That's amazing!

**Review by mwu-tow — APPROVED** [review]

**Comment by indiv0** [comment]
@PabloBuchu could I get a QA on this PR please?

**Comment by PabloBuchu** [comment]
QA  🔴 Everything works fine although I couldn't make the loading bar to appear @indiv0  🤔

**Comment by indiv0** [comment]
@PabloBuchu I've fixed the issue you reported on discord RE: the progress bar clobbering logging output. Would you mind QA'ing again?

That is, it should no longer do this:

image

**Comment by indiv0** [comment]
@mwu-tow would it be possible to get a QA on this? This touches the build process so it needs to be a cross-platform QA :)

(Pawel doesn't have a Windows or Linux machine)

**Comment by mwu-tow** [comment]
@indiv0 I will do.

**Comment by mwu-tow** [comment]
@indiv0 

I did testing on Windows. Some observations:
1) Sometimes a leftover progress bar still remains in the terminal:
obraz
It seems to happen when the `Command` is printed, likely because its debug representation contains a newline character.
2) How does this `IndicatifWriter` approach compares with the https://docs.rs/indicatif/0.17.3/indicatif/struct.MultiProgress.html#method.println? It was my earlier, unfinished attempt at achieving this. 
3) Does this mean that we can write only to stderr without breaking progress bars?

Minor observations (feel free to leave them for later):
* Having some kind of information about what the progress bar is about would improve clarity
* Using pretty-printed size units rather than just total byte number would be more readable.

<blockquote><div><strong><a href="https://docs.rs/indicatif/0.17.3/indicatif/struct.MultiProgress.html#method.println">MultiProgress in indicatif - Rust</a></strong></div><div>Manages multiple progress bars from different threads</div></blockquote>

**Comment by indiv0** [comment]
@mwu-tow

1. **!** Looks like this was potentially fixed in https://github.com/console-rs/indicatif/pull/540, would you mind re-testing?
2. My understanding is that the `IndicatifWriter` approach is more general, since with the `println` approach there's a potential for output to overwrite the progress bar if there's multi-line output being written. With the `IndicatifWriter` approach, this shouldn't happen since the progress bar is removed before writing logs and re-drawn from scratch after. I may be wrong on this.
3. I'm not entirely sure, but I didn't see any issues with that in my testing.
4. I tried to add information to the progress bar, but that *did* break rendering, depending on how much info was provided so I decided to leave it out.
5. Pretty-printed size units would be helpful but I'm not sure how best to do that. Just manually convert the bytes to MB and print that?

**Pull request merged**
