### PR TITLE
Fix updating conflicting project

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

This PR fixes a bug, when uploading a duplicate project to local backend threw a crash on windows.

https://github.com/user-attachments/assets/fe1bd7a7-d840-4bb1-b3f6-e0beec70fcd4
I found a bug when we upload a project to a remote backend, it throws a 500 error. Notified @PabloBuchu about that.

Also, @hubertp proved that the ProjectManager always duplicates a project no matter which option we choose(either "update" or "rename“).  So I removed the "update" button if we upload a project locally

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark:

**Comment by jdunkerley** [comment]
Tested on my Windows box - neither the Update or Rename buttons appear to work.
Clicking cancel works.

**Comment by PabloBuchu** [comment]
@MrFlashAccount its another PR without any description nor issue. If the bug was reported with discord and there is no issue please create it yourself (its enough to copy paste from discord or insert screenshot and attach to the iteration) or ping me to provide it to you.

**Review by jdunkerley — CHANGES_REQUESTED** [review]
Please don't remove the functionality from local.
Lets work with @4e6 and @hubertp and get the behavior correct.

Cloud and Local should be the same.
- If no conflict imported named as in the enso-archive.
- If conflict, dialog should be shown.
  - If update then replace existing.
  - If rename then add (n) to make unique.

And this should be the case regardless of how the project was "imported" - button, drag drop, double click in OS.

**Comment by MrFlashAccount** [comment]
@jdunkerley reverted the update functionality back, created an issue: https://github.com/enso-org/enso/issues/11166

**Review by jdunkerley — APPROVED** [review]

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
