### PR TITLE
Imrpove BG rendering

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

<details><summary>Difference</summary>
<p>

The difference isn't significant, but noticeable

| Before | After |
|--------|--------|
| Before | After
 | 

</p>
</details> 

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@MrFlashAccount whats keeping us from merging this?

**Comment by MrFlashAccount** [comment]
> @MrFlashAccount whats keeping us from merging this?

First of all, it's not urgent 🙂, also I need to test this PR against the redesign once again.

**Comment by MrFlashAccount** [comment]
@somebody1234 I spent some time on refining the background - made it less reddish to better match the design, it still requires some polishing though(we need to replace bg-white/80 with bg-white/90) to match it perfectly. But this can be changed later (we need to merge the redesign first) 

Also, I did some refinement in `tailwind.css`: merged similar declarations, reduced specificity for basic styles

Would you like to take a look?

**Review by somebody1234 — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@MrFlashAccount I know it wasn't urgent but it was hanging for some time so I asked. We have a lot of waiting PRs and I want to clear it in the next couple of days

**Pull request merged**
