### PR TITLE
Use `.isEmpty()` instead of `.length() == 0`

### PR DESCRIPTION
**Pull request by hubertp**
[ci no changelog needed]

### Pull Request Description

Minor nit - since String is a CharSequence it's advisable to use the
corresponding method for checking the condition rather than writing
it by hand.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

### CODE REVIEW

**Review by radeusgd — APPROVED** [review]
Good catch

**Comment by jdunkerley** [comment]
Nice.

**Review by jdunkerley — APPROVED** [review]

**Comment by wdanilo** [comment]
@mwu-tow could you take a look at the CI config here? It looks like it's not running.

**Comment by mwu-tow** [comment]
@wdanilo I've enabled this to run.

**Pull request merged**
