### PR TITLE
Include current project session id in logging metadata

### PR DESCRIPTION
**Pull request by PabloBuchu**
### Pull Request Description

Small PRs that adds current project session id to logger metadata. It will allow for easier localisation and scoping of the projects logs.

### Important Notes

This PR also fixes some inconsistency in names returned by cloud API in `getProjectDetails` response

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
the code changes are minimal so everything's fine code wise

**Comment by PabloBuchu** [comment]
@somebody1234 removed more inconsistency in naming convention. can you do re-review and maybe some qaing?

**Comment by somebody1234** [comment]
yeah, can do this later

**Review by somebody1234 — APPROVED** [review]
there's no logic changes, and all the `eslint-disable`s seem to be removed as expected. will be doing basic QA now

**Comment by somebody1234** [comment]
@PabloBuchu the `createTag` endpoint's request body was changed to `camelCase` too on the backend, but wasn't changed to camelCase on the frontend
https://github.com/enso-org/enso/blob/92ac11c4fc6d08edf0e77a7f173e9979c488a03c/app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts#L653-L656

**Comment by somebody1234** [comment]
unable to test `listTags` because it gives `500 Internal Server Error` when there are no matching tags. if this is intentional, it might be a good idea to change the backend endpoint to return `[]` on error:
https://github.com/enso-org/enso/blob/92ac11c4fc6d08edf0e77a7f173e9979c488a03c/app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts#L669

similarly to how it's currently being done for `listDirectory`:
https://github.com/enso-org/enso/blob/92ac11c4fc6d08edf0e77a7f173e9979c488a03c/app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts#L275-L278

on that note, not sure if the backend still returns `500 Internal Server Error` for empty directories - maybe that code can be removed

**Comment by somebody1234** [comment]
another issue:
:x: (?!) `model::User` isn't renamed to `camelCase`, but *is* renamed on the frontend typings, so the "shared with" column shows no username.
(for the same reason, the "share" entry is missing from the context menu)
`model::User`: https://github.com/enso-org/cloud-v2/blob/main/src/lambdas/src/model/mod.rs#L1036

image

email-on-hover is also broken as there is no permission matching the current user, meaning that the `managesThisAsset` boolean that determines whether email-on-hover is enabled is never `true`


<blockquote><div> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.</div></blockquote>

**Comment by somebody1234** [comment]
QA :red_circle: 

Summary of cases to test based on the code:
- :heavy_check_mark: `currentSessionId` should be sent in remote logs
- :grey_question: `remoteBackend.listTags({tagType:'project'})` should work (at least after calling `remoteBackend.createTag(name:'a',value:'aaa',objectType:'project',objectId:'project-id-here?')`)
- :x: User should be able to open the permissions management modal if they are an owner or admin
- :x: "Share" option in context menu is present if and only if a user is the owner or an admin
- :x: Same with show-email-on-hover on the "shared with" column
- :x: Usernames should be present in "shared with" column
- :grey_question: Autocomplete in the permissions management modal should never suggest users that already have permissions for the asset
- :grey_question: The "Own" permission should be faded out in the permissions management modal if the current user is the only owner
- :grey_question: Display of newly added permissions should be correct - both in the permissions management modal, and in the "shared with" column

**Comment by somebody1234** [comment]
for posterity, the corresponding cloud PRs are here:
- https://github.com/enso-org/cloud-v2/pull/614
- https://github.com/enso-org/cloud-v2/pull/613

**Review by indiv0 — APPROVED** [review]
LGTM

**Comment by somebody1234** [comment]
merged develop into this branch by preferring the version on `develop`. i've made sure to keep `currentSessionId` in `editor.tsx` but it'd probably be good to make sure everything still looks (and works) fine

**Comment by sylwiabr** [comment]
@PabloBuchu anything blocking the merge here?

**Comment by PabloBuchu** [comment]
Closing. We turned off logging as it was too verbose without much on information. We will re-do it with new gui

**Pull request closed without merging**
