### PR TITLE
Cloud/desktop mode switcher

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Creates buttons to switch between cloud and local backends for listing directories, opening projects etc.

### Important Notes
- ~~Opening a different project *does not work*. (afaict, the relevant APIs are not exposed to JS)~~
- ~~Opening projects from the dashboard on the desktop IDE *does not work*, for the same reason.~~

### Screenshots
To be added

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
for posterity, things that should be checked:
- opening a project
  - make sure your test projects all have different contents
- switching project (for now you need to use inspect element - launch with `-debug.dev-tools` or `--ide-option -debug.dev-tools` if in watch mode, and then remove the `hidden` class from `.enso-dashboard`'s second child)
- opening a desktop project, then opening a cloud project
- opening a cloud project, then opening a desktop project

cloud frontend (in-browser) is intentionally *not fully supported*, since the priority right now is the desktop electron app.

**Comment by somebody1234** [comment]
as of now, what i'm implementing/testing is opening cloud projects. opening+switching desktop projects should be working locally, not pushed yet though

**Comment by PabloBuchu** [comment]
@somebody1234 I did some QAing and actually it looks good. Whats missing from making this PR ready to review? It is super important to review and merge it as soon as possible

I have created issue https://github.com/enso-org/enso/issues/6399 for IDE for creating a button to take user back from opened project to dashboard. You may want to add there any specific requirements from the frontend

Right now to make testing and qaing easier are we able to add a simple keyboard shortcut that will switch back to dashboard view?

**Comment by somebody1234** [comment]
@PabloBuchu I don't think there should be much (if anything) remaining - I do have a hard time testing cloud projects because occasionally `pkg-opt.wasm` loads *really* slowly for some reason, but if that's working and switching between backends is working, this should be all ready to go - and it'll just be blocked on the `.drop()` PR being merged in

**Comment by somebody1234** [comment]
right now i'm adding the jsdoc lint back, which isn't that important but might as well do it sooner rather than later. after that's done it should be easy enough to add a keyboard shortcut. any ideas on what the shortcut should be? one thing to note is that it shouldn't conflicting with existing IDE keybinds, especially because the keybind only be active when the IDE is open

**Comment by somebody1234** [comment]
one thing to note: the cloud backend doesn't use the `ProjectManager` to load the wasm - i think this might be unavoidable as different versions of `index.js` may expect different options, so the current options passed to `runProject` may (or do) error on different versions

another thing to note: *all* of the cloud versions are missing `drop` because the relevant PR has not yet been merged in. in the few tests I did however, it seems like things were working more or less fine even without `drop`?

**Comment by PabloBuchu** [comment]
@somebody1234 lets open the PR for review

**Comment by somebody1234** [comment]
@PabloBuchu one second - there are merge conflicts, + i'm currently making templates work properly on desktop since it has a different set of templates

**Comment by PabloBuchu** [comment]
@somebody1234 one thing I've noticed. It's always happening on first electron run after the open.. see screnshot below

Screenshot 2023-04-25 at 18 16 40

**Comment by somebody1234** [comment]
@PabloBuchu re: the error - could you explain repro steps better? i don't think i've ever seen errors connecting to project manager i think, *but* i basically exclusively use `ide run watch` which might be why

**Comment by PabloBuchu** [comment]
> @PabloBuchu re: the error - could you explain repro steps better? i don't think i've ever seen errors connecting to project manager i think, _but_ i basically exclusively use `ide run watch` which might be why
@somebody1234 
basically `./run ide build --skip-version-check --skip-wasm-opt --wasm-profile=dev --backend-source release --backend-release nightly` and `./dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso -debug.dev-tools -authentication -feature-preview.new-dashboard`

**Comment by somebody1234** [comment]
can't repro, unfortunately :( might be a race condition

**Comment by somebody1234** [comment]
do you happen to have logs from the terminal? here's what they look like for me:
```
[info] [2023-04-25T16:43:14.642Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Project Manager...
[info] [2023-04-25T16:43:14.887Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[info] [2023-04-25T16:43:14.937Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [00c2842e-a65a-40ac-b2a7-f6614f1edbb4]
```
(indicating in my case that the project manager does start before the client tries to connect)

alternatively the project manager *may* be starting on a different port sometimes on macos

**Comment by PabloBuchu** [comment]
> do you happen to have logs from the terminal? here's what they look like for me:
> 
> ```
> [info] [2023-04-25T16:43:14.642Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Project Manager...
> [info] [2023-04-25T16:43:14.887Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
> [info] [2023-04-25T16:43:14.937Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [00c2842e-a65a-40ac-b2a7-f6614f1edbb4]
> ```
> 
> (indicating in my case that the project manager does start before the client tries to connect)
> 
> alternatively the project manager _may_ be starting on a different port sometimes on macos

so it looks like this... but eventually I can see it has connected.. 

Screenshot 2023-04-25 at 19 06 45

**Comment by somebody1234** [comment]
huh, that's pretty weird... so it seems like the Rust side of the JSON-RPC is already up, not sure what's up with the Electron side then. i think the next thing to try would be to check the network tab and filtering for just the websocket requests, but given that the connection doesn't even work in the first place i wouldn't be too optimistic about how much info the network tab will show...

**Comment by somebody1234** [comment]
(not tested yet)

**Comment by somebody1234** [comment]
(broken, one sec (or a lot))

**Review by PabloBuchu — APPROVED** [review]

**Comment by wdanilo** [comment]
I reverted the PR. 
1. It was not checked by all code owners - I don't know why I was not requested, but it touches Electron stuff and I was always handling it. 
2. There was no Q/A.
3. It introduces regression - it is impossible to work on debug scenes anymore as they throw tons of errors.

**Comment by somebody1234** [comment]
sorry - i didn't think it would affect other scenes (or rather, didn't even think about debug scenes)

**Pull request merged**
