### PR TITLE
Sort assets

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/511
  - Adds sorting. Currently supported columns: "Name" and "Last Modified"

### Important Notes
The sort arrows have a slightly thicker border (changed from 2px to 2.14px), to remove the (very small) internal hole in the Figma design. It is possible to make the shape more accurate to the original design by using a polygon (or a path) that traces around the original outline instead, but I figured it's not worth spending the extra time on a fix that may not be correct.

:information_source: The comparison function for sorting is quite complicated. I think this is the least intrusive change for now, but it is worth considering changing `AssetsTable` to store items internally as a tree instead, and do a preorder traversal to flatten it into an array when needed.

### Screencast

[screen-recorder-thu-aug-10-2023-16-41-50.webm](https://github.com/enso-org/enso/assets/4046547/386e1ff6-f1e8-4b4e-8534-f938b1eed907)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
ok so this is currently freezing when sorting new entries, since there is no folder with a *key* matching the asset's *parent id*. not sure what's the best way to solve this - there is no way to get the child's parent's *key*, since the asset table does not store the parent's current value (it has access to the initial value of the item, with the placeholder id - aka the key.)

**Comment by somebody1234** [comment]
i think (?) this isn't really high priority or anything, so i *think* i'll try refactoring from an assets list to an assets tree here. it will be a lot of changes to have to test ( :( ) but unfortunately i think it may be the simplest solution

**Comment by somebody1234** [comment]
post-refactor testing:
- :heavy_check_mark: adding entry to directory shows loading spinner while directory entries are loading
- :heavy_check_mark: generated name of new directory is one higher than all other *visible* children
- :heavy_check_mark: folder is inserted in correct position after sibling project has been inserted
- :heavy_check_mark: project is inserted in correct position after sibling folder has been inserted
- :heavy_check_mark: when deleting folders, an unrelated folder also disappeared for some reason. (logic bug - it reappears upon refresh) (fixed by new commit)
- :heavy_check_mark: sorting works properly and doesn't freeze, or put projects before folders, and works properly even with nested folders
- :heavy_check_mark: nested folders follow their parent folder when sorting

**Comment by somebody1234** [comment]
Note: I think this refactor also makes it possible (or I guess, easy) to show the "this folder is empty" placeholder row instead of collapsing the folder.

However, it would only show after a delay, after all children have been actually deleted - this is why the current behavior is just to silently collapse the folder.

**Comment by PabloBuchu** [comment]
Sorting works fine but the logic needs a bit more improvements. The sort by name or modification date should mix the asset types if it results from sorting order. Now the group takes precedence 

https://github.com/enso-org/enso/assets/2855109/3093bc01-4537-4c65-8ed6-1a156bf96c97

**Comment by somebody1234** [comment]
fixed locally, *but* i just realized that sorting currently uses the initial item - so after renaming, it will still use the initial name, and after running a project, it will still use the creation date (or original "last modified" date) not the last modified date

**Comment by somebody1234** [comment]
should be fixed now - also fixed creating new assets (e.g. "New Project" button)

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
