### PR TITLE
Fix IDE configs

### PR DESCRIPTION
**Pull request by kustosz**
### Pull Request Description
No .idea why this was added in the first place, but it made me spend more time than I'd like on rebuilding my run configurations after rebasing onto develop. Please don't break my IDE like that.

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by wdanilo — CHANGES_REQUESTED** [review]
We had a longer discussion why we want to ship build configurations in this repo. We want them because run configurations for IDE are fairly complex, require special flags, it is easy to forget about some, and we want to ship preconfigured project here. So instead of removing them, I'd like to learn why you had a problem with them and how can we solve it to still include them in the repo and not cause issues on your end (or in similar situations). 

Also, see the official guide: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

**Comment by kustosz** [comment]
@wdanilo 
Problems:
1. Rebasing onto develop trashed my existing IDE config – had to reconfigure pretty much everything, including java versions.
2. As a person that doesn't use these, I'd like to remove them and reduce clutter. I cannot do that, because I get 600 lines of changed files in git status, so my git workflow is impossible.
3. As a person that uses other configurations (for the 50% of the project this solution decides to pretend doesn't exist), I cannot add them, because again, that makes my git tree dirty.

Solution: really obvious and practiced e.g. across all GraalVM projects: have a script that will populate these. Solves all 3 issues:
1. I wouldn't have run it in the first place, until maybe _wanting_ to re-import the project, not mid-task.
2. I can remove these, because the actual files used by intellij are not under git
3. I can add new "dirty" configs without alerting git again.
In general, such a solution allows me to own my own editor env and allows you to share difficult to set up configs. I appreciate the need for shared configs (and the engine side could also use it!) but it cannot be at the price of not being able to configure my own everyday tools.

**Comment by wdanilo** [comment]
Thanks @kustosz, makes perfect sense. We actually have a script to generate these configs, but people (I don't remember now who exactly) preferred them to be in the repo rather than generated on-demand, but TBH both these ways work well for me. I would like to understand a few things though:

1. Why your local configs were removed? They are stored in a `.idea` folder that should not been altered by the pull. This is super strange to me and I'd love to understand how did it happen.
2. What clutter are you talking about? The number of options in the run config window or some other clutter? I know that when you use "run configuration" in IntelliJ you've got a bunch of our configurations, but don't you think that in a world where there are both IDE and Engine configurations the clutter would not be terrible? I know we have a lot of them, but even if we have 2x the amount (where 50% is from Engine), this will be easy to navigate: 

image

3. Regarding Engine configurations, the plan was to add them here the same way. We just created GUI configs for now, because it's really hard to do improvements on all parts of the projects at the same time. I do not understand here the argument: `As a person that uses other configurations [...] I cannot add them, because again, that makes my git tree dirty.`. You can add run configurations either as internal or external in IntelliJ. The internal configuration will NOT make git dirty, as they are NOT stored in the folder we are committing. You need to mark your run configuration as "external" for it to be stored there. According to IntelliJ manual, configs marked so are meant to be shared across teams. Anyway, we would be more than happy to take Engine run configs and add them there by default - this will probably help other people working on the Engine side. What do you think of it?

**Comment by kustosz** [comment]
Right, most of this was probably triggered by past intelliJ bugs. Gonna observe the behavior some more and come back to you if things are still problematic.

**Pull request closed without merging**
