### PR TITLE
Fix Dataflow Error propagation for Builtins accepting primitives

### PR DESCRIPTION
**Pull request by radeusgd**
### Pull Request Description

[ci no changelog needed]

Fixes https://www.pivotaltracker.com/story/show/181652841

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed: Enso GUI was tested when built using BOTH `./run dist` and `./run watch`.

### CODE REVIEW

**Comment by radeusgd** [comment]
Tests pass locally for me, but I've run the benchmarks and there are 3 regressions.
[bench-report.txt](https://github.com/enso-org/enso/files/8489279/bench-report.txt) (I had to rename `.xml` to `.txt` for GH to accept the file)

**Comment by radeusgd** [comment]
I've been chatting with @jdunkerley and the issue seems to be that we used to do the `expectLong` check first, and the `isDataflowError` later - and likely if the compiler saw that `arg` is `long` maybe it was able to optimize out the `isDataflowError` check?

Anyway we thought that the solution to that would be to handle checked and unchecked types slightly differntly. For unchecked, we just need to perform the dataflow error checks, there is no discussion.

But for checked ones, we can expect the happy path with our `expectT` and only do the errors checks in the unhappy path, i.e.:
```diff
    long arg1;
    try {
      arg1 = TypesGen.expectLong(arguments[1]);
    } catch (UnexpectedResultException e) {
+    if (arg1ConditionProfile.profile(TypesGen.isDataflowError(arguments[1]))) {
+      return new Stateful(state, arguments[1]);
+    }
+    else if (TypesGen.isPanicSentinel(arguments[1])) {
+      arg1BranchProfile.enter();
+      throw TypesGen.asPanicSentinel(arguments[1]);
+    }
      var builtins = Context.get(this).getBuiltins();
      var expected = builtins.fromTypeSystem(TypesGen.getName(arguments[1]));
      var error = builtins.error().makeTypeError(expected, arguments[1], "arg1");
      throw new PanicException(error,this);
    }
-    if (arg1ConditionProfile.profile(TypesGen.isDataflowError(arguments[1]))) {
-      return new Stateful(state, arguments[1]);
-    }
-    else if (TypesGen.isPanicSentinel(arguments[1])) {
-      arg1BranchProfile.enter();
-      throw TypesGen.asPanicSentinel(arguments[1]);
-    }
```

This relies on an assumption that `expectT` is used only for types `T` such that **not** `DataflowError <: T`. But I think this assumption should hold, right?

cc: @kustosz @hubertp Any thoughts on this? Do you think we are fine to move to this other approach as described in this comment?

**Review by hubertp — COMMENTED** [review]
Proposed changes in the last comment sgtm

**Review by jdunkerley — APPROVED** [review]
LGTM - but would be good to get @kustosz's feedback

**Review by 4e6 — APPROVED** [review]

**Review by hubertp — APPROVED** [review]

**Review by JaroslavTulach — APPROVED** [review]

**Review by kustosz — COMMENTED** [review]
Got asked to review this post-mergously. Letting you know it all looks good to me.

**Pull request merged**
