### PR TITLE
Fix error visualization positioning

### LINKED ISSUE #7256: Visualization for dataflow error appears in wrong position and occludes the node
image

Repro: type `Error.throw 42` and hover over the output port to see the visualization.

It does not appear below the node, but shifted up, occluding the contents of the node itself.

Even worse, it also happens when the preview is an error when editing the node:
image

This way, I cannot see big part of the text that I'm editing, so I cannot fix the error that is in there because I do not know where is my cursor and what I'm typing.

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

Fixes #7256 

Sadly no resizing for error vis yet, it is far too complicated and requires a separate task.

https://github.com/enso-org/enso/assets/6566674/77ddbe78-7f27-41d1-9f63-5dd1d717ecd3

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by farmaazon — APPROVED** [review]

**Comment by farmaazon** [comment]
### QA Report: :green_apple:

**Comment by radeusgd** [comment]
> Sadly no resizing for error vis yet, it is far too complicated and requires a separate task.

@vitvakatu do we have a ticket to track this? It would be really useful, as errors are hard to read in the very small box.

**Comment by farmaazon** [comment]
There is no ticket yet, and the question is to @wdanilo if we have any design of how should errors be displayed in the new design?

**Comment by wdanilo** [comment]
Yes, its in the design for pretty long time already:

image


However, it does not have good description – I will work on that and add there better description + icon to expand the error msg.

**Pull request merged**
