### PR TITLE
`localStorage` manager

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/571
- Moves all interaction with `localStorage` into a `LocalStorage` class
- Saves and loads current tab (dashboard, or IDE)
- Saves and loads currently open project

Unrelated fixes:
- Changes authentication toast notifications to replace loading toast, rather than creating a new toast

### Important Notes
:warning: `remoteLog` has not been parametrised with `projectId` (and `sessionId` for cloud projects)

There are several places that previously used manual `localStorage.setItem` and `getItem`:
- Whether the templates list is currently open
- The current project management backend (local, or cloud)
- The path to the current directory is (as far as I can tell) obsolete, as the new directory view always displays the root directory, and so it has been removed

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
:warning: This is not tested thoroughly (especially on the cloud backend), just opening the PR so I don't forget to later on.
Also (see original post) `remoteLog` has not been parametrised with `projectId` (and `sessionId` for cloud projects)

**Comment by somebody1234** [comment]
@PabloBuchu i think this PR is ready for testing btw

**Comment by somebody1234** [comment]
basic tests:
- :heavy_check_mark: all localstorage data is in a single object (fixed by new commit)
- :heavy_check_mark: localstorage data is cleared (and entry is removed from browser `localStorage`) when signing out (fixed by new commit)
- :heavy_check_mark: extra columns update in localstorage as they are clicked
- :heavy_check_mark: extra columns are restored after refresh
- :heavy_check_mark: templates list expanded/collapsed state updates in localstorage when it is toggled
- :heavy_check_mark: templates list expanded/collapsed state is restored upon refresh
- :heavy_check_mark: project + last opened page are updated in localstorage as they are clicked (fixed by new commit)
- :heavy_check_mark: last opened project is reopened after refresh
- :heavy_check_mark: page is switched to IDE after refresh, if the last opened page before shutdown/refresh was IDE (fixed by new commit - previously page was never being saved)
- :heavy_check_mark: project is opened in background, but page is not switched, if the last opened page before shutdown/refresh was not IDE
- :heavy_check_mark: project opens properly, even when its backend differs from current backend
  - this should more or less work because `Project`s contain backend endpoints. however, local projects use the PM endpoints instead of the LS endpoints, meaning the backend type must be saved too

**Comment by PabloBuchu** [comment]
1. So resurecting local project after close is working fine but on the project list the icon is indicating the project needs opening.
Screenshot 2023-08-10 at 11 55 55
2. So what with remote logging? Has been disabled by default in this branch? I am getting 
```
Not sending log to remote server. Data collection is disabled. Message: "graph_editor::visualization_chooser::vis_selected" Metadata: {"visualization_name":"JSON"}
```

on develop in works fine and it should be enabled. 

|  remoteLog has not been parametrised with projectId (and sessionId for cloud projects)
why? can't we add it here?

**Comment by somebody1234** [comment]
> remoteLog has not been parametrised with projectId (and sessionId for cloud projects)

can definitely add it here, i'm just not sure how it should work - should they just be added as text? like `projectId=${projectId} sessionId=${sessionId}` or something?

**Comment by PabloBuchu** [comment]
Can we ged rid off this nested metadata? 
Also prettier checks failed

Screenshot 2023-08-10 at 15 54 03

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
did basic testing, all localstorage items seem to still work, and so does logging on local projects

**Pull request merged**
