### PR TITLE
Fix auto layout

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
So it turns out auto-layout was broken if there were existing, already positioned nodes

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Review by farmaazon — COMMENTED** [review]
I strongly recommend adding a test for layouting nodes.

**Comment by somebody1234** [comment]
ah... yeah, good point

**Comment by somebody1234** [comment]
@farmaazon for the tests i've added, i did run into the same `getTextWidth` issue that you did. in this PR i've done the bare minimum to get tests working, so do let me know if you've solved it differently

**Comment by farmaazon** [comment]
> @farmaazon for the tests i've added, i did run into the same `getTextWidth` issue that you did. in this PR i've done the bare minimum to get tests working, so do let me know if you've solved it differently

@somebody1234 Of course I did! https://github.com/enso-org/enso/pull/8316/commits/f5942bdb6e2e0cd1c562162d09cbc6f730c7d17e

I prefer my solution :) and you?

**Comment by somebody1234** [comment]
@farmaazon tbh I agree with your comment there...

**Comment by somebody1234** [comment]
... so i've moved the code to `updateNodeRect`, which *does* know the size of the node.

as a side effect though, i've had to remove the tests... not sure whether there's a nice way to test `updateNodeRect` in the graph store.

**Review by Frizi — APPROVED** [review]

**Pull request merged**
