### PR TITLE
Propagate comparator warnings via Any.==

### LINKED ISSUE #10679: Comparator warnings should propagate to output of `==`
Warnings attached to the result of `Comparator.compare` do not propagate to the boolean return value of `==`.

[Failing Test](https://github.com/enso-org/enso/blob/wip/gmt/10679-failing-test/test/Base_Tests/src/Data/Ordering/Comparator_Spec.enso#L101)

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Fixes #10679 by changing the return type of `EqualsXyzNode`s to `EqualsAndInfo`. This class holds the result of the comparation as well as any attached warnings. `EqualsBuiltinNode` then re-attaches the warnings, if there are any.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
- [x] Unit tests have been written where possible.
- [x] Engine benchmarks are fine: [run](https://github.com/enso-org/enso/actions/runs/10806990046), [another run](https://github.com/enso-org/enso/actions/runs/11008652776), [run after merge](https://github.com/enso-org/enso/actions/runs/11017989534) - [run after fix](https://github.com/enso-org/enso/actions/runs/11026152039) with 2c4b522
- [x] Library benchmarks seem fine: [run](https://github.com/enso-org/enso/actions/runs/10807001210), [another run](https://github.com/enso-org/enso/actions/runs/11011276245) and [after fix run](https://github.com/enso-org/enso/actions/runs/11026208641)

### CODE REVIEW

**Comment by GregoryTravis** [comment]
[These tests](https://github.com/enso-org/enso/blob/develop/test/Base_Tests/src/Data/Decimal_Spec.enso#L378) should pass now.

**Review by GregoryTravis — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
There is [21 failing tests in Table_Tests](https://github.com/enso-org/enso/runs/29860179198#r8) what do you think about them, @GregoryTravis?

**Comment by GregoryTravis** [comment]
> There is [21 failing tests in Table_Tests](https://github.com/enso-org/enso/runs/29860179198#r8) what do you think about them, @GregoryTravis?

The failures say `first difference at index Nothing`, which is an error I have not seen before.

**Comment by JaroslavTulach** [comment]
> [These tests](https://github.com/enso-org/enso/blob/develop/test/Base_Tests/src/Data/Decimal_Spec.enso#L378) should pass now.

These tests pass after 445e500e74b2951fe37478d3b835c478e6223e86

**Comment by JaroslavTulach** [comment]
Engine benchmarks [run](https://github.com/enso-org/enso/actions/runs/10806990046) is finished. Here are potential problems:

- `AtomBenchmarks_benchGenerateListQualified` slightly slower
- `IfVsCaseBenchmarks_caseBench3` - improved!
- `RecursionBenchmarks_benchNestedThunkSum` slightly slower
- `RecursionBenchmarks_benchSumStateTCO` slighlty slower
- `TypePatternBenchmarks_matchOverAny` minimal regression
- `TypePatternBenchmarks_matchOverDecimal` minimal regression
- etc.

**Update** on Sep 25, 2024: The benchmarks regression should now be eliminated with 2c4b522 to be verified by [engine benchmarks run](https://github.com/enso-org/enso/actions/runs/11026152039).

**Review by Akirathan — COMMENTED** [review]
I don't like the introduction of the new `EqualsAndInfo` return type. Why can't `EqualsNode.execute` just return `Object` and for some specializations that should return a result with warnings just return `WithWarnings` object, and for other a boxed `Boolean`? Introduction of `EqualsAndInfo` adds an inconsistency to how we manipulate with warnings.

**Review by jdunkerley — APPROVED** [review]

**Comment by jdunkerley** [comment]
Approved the enso tests to allow it to proceed.

**Comment by JaroslavTulach** [comment]
> I don't like the introduction of the new `EqualsAndInfo` return type. 
> Why can't `EqualsNode.execute` just return `Object` and for some specializations that should return a result with warnings just return `WithWarnings` object, and for other a boxed `Boolean`? 

Such an approach has been tried already. Please see this diff: https://github.com/enso-org/enso/issues/10679#issuecomment-2302375703 - there are few problems to it:

**Checking the result becomes more complicated**. The above patch is using `instanceof Boolean`, but that's wrong. The code would probably deserve its own nodes: `CheckBooleanNode` and `RewrapWarningFromBooleanNode`, etc. Given the majority of use-cases (`EqualsBuiltinNode``HashMap` and _comparator_) are built around _really need the boolean_ use-case it seems inefficient to wrap and immediately unwrap the value.

**Warnings aren't efficient**. Given 99.9% of use-cases is going to work with `boolean` only, having all the machinery in place for warnings manipulation is an over kill. It should be conditional. The current PR does that by checking `equals()` and making a decision. Checking `warnings()` aren't `null` and rewriting itself to handle the complicated case. No `WarningsLibrary`, no `AppendWarningNode` until a `boolean` with warning appears.

> Introduction of `EqualsAndInfo` adds an inconsistency to how we manipulate with warnings.

A bit. But `EqualsNode` is special. It is not an _expression_! We have `EqualsBuiltinNode` now to represent an expression. `EqualsNode` is there to check `==` and give you `EqualsAndInfo` - `EqualsBuiltinNode` than extracts such info and converts it into regular `EnsoObject`.

I don't expect too much code in Enso to use `EqualsNode` directly. The `EqualsBuiltinNode` is one. The `HashMap` package is the other. The comparator is the 3rd. Maybe we can move the `EqualsNode` "family" into own package to demonstrate it is "special"?

**Review by Akirathan — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
Benchmarks seem to be fine. One good result on _bankers_, @GregoryTravis:

bankers

**Pull request merged**
