### PR TITLE
Improve the Signup experience

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

Closes: enso-org/cloud-v2#1460

This PR refactors the signup experience.
1. The confirmation page is redesigned. Now it shows instructions on what user should do next
2. Once user sign up, we navigate him to the next page, where user can either open a email client and follow the link or enter the code manually.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Review by vitvakatu — APPROVED** [review]
translation file only to unblock code ownership

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark:

**Comment by PabloBuchu** [comment]
Looks googs ✅

**Comment by PabloBuchu** [comment]
Can't build
```
 INFO ide_ci::program::command: pnpm ℹ️ src/components/Link.tsx(36,8): error TS2375: Type '{ children: (string | Element)[]; onKeyDown: (event: React.KeyboardEvent<Element> | KeyboardEvent) => void; ... 5 more ...; href: string | undefined; }' is not assignable to type 'LinkProps' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
 INFO ide_ci::program::command: pnpm ℹ️   Types of property 'href' are incompatible.
 INFO ide_ci::program::command: pnpm ℹ️     Type 'string | undefined' is not assignable to type 'string'.
 INFO ide_ci::program::command: pnpm ℹ️       Type 'undefined' is not assignable to type 'string'.
 INFO ide_ci::program::command: pnpm ℹ️ /Users/pawelbuchowski/projects/enso/app/dashboard:
 INFO ide_ci::program::command: pnpm ℹ️  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  enso-dashboard@0.1.0 compile: `tsc`
 INFO ide_ci::program::command: pnpm ℹ️ Exit status 2
 INFO ide_ci::program::command: pnpm ℹ️ /Users/pawelbuchowski/projects/enso/app/gui2:
 INFO ide_ci::program::command: pnpm ℹ️  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  enso-gui2@0.1.0 build: `corepack pnpm -r --filter enso-dashboard run compile && corepack pnpm run build:vite`
 INFO ide_ci::program::command: pnpm ℹ️ Exit status 2
 INFO ide_ci::program::command: pnpm ℹ️  ELIFECYCLE  Command failed with exit code 2.
TRACE ide_ci::program::command: pnpm ℹ️ <ENDUT>
TRACE ide_ci::program::command: pnpm ⚠️ <ENDUT>
```

**Comment by MrFlashAccount** [comment]
@PabloBuchu Fixed types

**Pull request merged**
