### PR TITLE
Check benchmarks as the last step in the build

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Verify functionality first, only then check benchmarks.

### Checklist

Please include the following checklist in your PR:

- [ ] All code conforms to the
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [ ] Check benchmarks are still run in the gates

### CODE REVIEW

**Review by mwu-tow — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
[JMH is still executed](https://github.com/enso-org/enso/actions/runs/4005959935/jobs/6876936725#step:10:794) too early! Have I changed wrong file?

**Review by hubertp — COMMENTED** [review]
This still runs benchmarks as part of the initial sbt command: https://github.com/enso-org/enso/actions/runs/4005959935/jobs/6876936725#step:10:729

**Review by jdunkerley — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
There is no compilation of [benchmarks in](https://github.com/enso-org/enso/actions/runs/4022763848/jobs/6912845000) - search for `jmh` - nothing important is there.

**Comment by JaroslavTulach** [comment]
Giving up on this PR.

**Pull request closed without merging**
