### PR TITLE
Dashboard hotfixes

### LINKED ISSUE #10279: Cannot use local projects if no Cloud plan is enabled
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I log in into an account that does not have an enabled Cloud plan, I get the following screen:
image

There is no way to switch to the Local mode - so I cannot use Enso at all.

### Expected behaviour

I should be able to use the Free tier of Enso locally.

### How we can reproduce it?

I've got this issue on this CI build: https://github.com/enso-org/enso/actions/runs/9487658469

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

d6d3709 / 2024.2.1-nightly.2024.6.13

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix the appearance of the `tertiary` button variant
- Fix spinner for projects that are opening being misaligned by 1px
- Fix appearance of "Login with Google" and "Login with GitHub" icons in the Login page
- Fix #10279
  - Switch to Local tab when on desktop app and user does not have an active plan

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
These tooltips are bit troublemakers.. On local project it appears like that making unable to close project

Screenshot 2024-06-13 at 12 38 28

The log out problem is persistent on my setup. I click log out and I am being redirected to the browser but going back to the dashboard. Reload properly lands on auth screen

https://github.com/enso-org/enso/assets/2855109/f4f72464-2353-4651-8eb4-614c061f3679

**Comment by somebody1234** [comment]
tooltips should be fixed. will look into the log out issue soon™️

**Review by kazcw — APPROVED** [review]
Approving vite change

**Comment by somebody1234** [comment]
not sure why CI is bugging out on packaging step, previous runs were working fine

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
