### PR TITLE
Remove obsolete GUI arguments

### LINKED ISSUE #8610: Stop Dashboard from passing obsolete options to GUI2, when GUI1 is removed
GUI2 should warn on invalid options instead of launching, but this is currently not useful as the dashboard passes invalid options which are required by GUI1 (e.g. the WASM URLs).

The invalid option handling (`{ onUnrecognizedOption }`) should be re-added to GUI2's `runApp` when the extra options are no longer needed.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close #8610

### Important Notes
QA notes:
- The GUI2 warning screen should not show up - the arguments that GUI2 do not understand have been removed.
- However, it should be tested that the warnings screen should correctly work when invalid arguments really *are* passed in:
  - Via URL query parameters (electron, might need to open the electron app then the browser, *or* do `location.href = ` in DevTools in Electron.)
  - By editing `Editor.tsx` to inject invalid args to the big configuration object we pass to the GUI entrypoint.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Review by Frizi — APPROVED** [review]

**Review by indiv0 — APPROVED** [review]
LGTM, will handle QA

**Comment by indiv0** [comment]
:x: QA failed (per discussion on discord). Spooky warning occurs when running with `-debug`.

image

**Comment by farmaazon** [comment]
This PR is stale for two weeks. @indiv0 @somebody1234 can we do something with it?

**Comment by somebody1234** [comment]
oops, totally forgot about this.
after some investigation... it seems like `-debug` isn't valid? not sure if it ever was, will download an old release to check.
@indiv0 would you happen to remember what the `-debug` flag was for?

edit: nvm,it was indeed an option... lemme check

**Comment by somebody1234** [comment]
ah. i guess it's intentional because currently we no longer intercept logs (and hence don't have `showLogs`) - so the `-debug` option becomes redundant

**Comment by indiv0** [comment]
In that case, QA passed ✅

**Pull request merged**
