### PR TITLE
Fix issue 3140 case insensitive collisions

### PR DESCRIPTION
**Pull request by IsaacTell**
### Pull Request Description

Issue #3140 still happens for me on a windows machine. Suggestion to delete one of the identical copies of each file that only differs in the case of the file name

### CODE REVIEW

**Comment by radeusgd** [comment]
Thanks for reaching out about the issue and providing us with a potential fix.

I think you are right that we should sort this out and avoid having the two clashing copies.

However, we need to ensure that our legal review tool still works correctly.

For now, I see that with the updated config it fails with:
```
sbt:enso> gatherLicenses
(...)
[warn] License Apache License v2.0 for net.java.dev.jna # jna # 5.5.0 is not reviewed.
(...)
sbt:enso> verifyLicensePackages
[info] Report for launcher is reviewed.
[info] Package distribution/launcher/THIRD-PARTY is up-to-date.
[error] Report for the engine has 1 warnings.
[warn] Please make sure to run `enso / gatherLicenses` and review the reports generated at /home/radeusgd/NBO/enso/target, ensuring that the legal review is complete and there are no warnings.
[warn] See docs/distribution/licenses.md#review-process for a more detailed explanation.
[error] stack trace is suppressed; run last verifyLicensePackages for the full output
[error] (verifyLicensePackages) GatherLicenses$LegalReviewException: Report for the engine has 1 warnings.
[error] Total time: 3 s, completed Sep 4, 2023, 6:26:58 PM
```

I think that in order to fix this, we need to ensure that the license matching code can find these license files in a case insensitive manner (so that indeed only one copy of this file will suffice). I guess I can try to make a fix for it.

But if you'd like to give it a try, that would be more than appreciated too 🙂 
If you'd like to try it, here are some pointers:
- the logic for finding the related license file is https://github.com/enso-org/enso/blob/8a60bc6dcd573d9b3087afbcdc4b4639e7b80b2a/project/src/main/scala/licenses/report/Review.scala#L269-L299
- I imagine what I'd do is just modify the [`normalizeName`](https://github.com/enso-org/enso/blob/8a60bc6dcd573d9b3087afbcdc4b4639e7b80b2a/project/src/main/scala/licenses/report/Review.scala#L352-L355) method to always lowercase the license identifier.
	- That would require renaming all `tools/legal-review/*/reviewed-licenses/*` files to be lowercase to fit the new naming scheme.
- Afterwards we need to ensure that `sbt gatherLicenses` was run (it has to be run on a UNIX system currently, Windows support has not been implemented fully, but it works under WSL) and afterwards we can check if everything works by running `sbt verifyLicensePackages` - this will succeed if all is OK and fail if there's anything missing.

**Comment by IsaacTell** [comment]
I will have a go and see if I can make this change.

**Comment by IsaacTell** [comment]
I went for a slightly different solution of making the legal review tool case insensitive. Let me know what you think.

~Although I've done something strange to my GitHub account so might need to push again...~ (OK sorted that)

**Review by radeusgd — APPROVED** [review]
Awesome! It looks all good and I like your solution even more than the one I originally proposed - indeed it feels more friendly to just match the file names case insensitively instead of modifying the normalization.

**Comment by radeusgd** [comment]
I've also ran `gatherLicenses` on my WSL box and it looks like the workflow runs OK, no modifications needed to the `report-state` files.

**Review by JaroslavTulach — APPROVED** [review]

**Comment by IsaacTell** [comment]
Did I break the tests? I'm struggling with how to read the logs to see what broke.

**Comment by radeusgd** [comment]
> Did I break the tests? I'm struggling with how to read the logs to see what broke.

Ah sorry, I was meaning to get back to you earlier but got caught up in other stuff.

----

I was looking at the tests. Some of our tests currently fail when run from outside forks (we want to improve on this in the future, but it is not that trivial).

I tested this manually and it seems OK. The engine tests on the CI have succeeded it's just some reporting action failing; a few IDE tests failed due to limitations on remote fork and Lint test failed due to a caching issue and some 'unexpected' files present from other branch.

We will be able to merge the PR skipping these tests that cause problems due to remote branch. However, before we will be able to accept the contribution and merge the PR, we need to make sure that you have signed the CLA, as [noted by the bot](https://github.com/CLAassistant). If you need any assistance of how to do this, feel free to ask @mwu-tow for additional details.

**Comment by IsaacTell** [comment]
Yes I signed the CLA. But think I upset the bot as my original commit had the wrong user name, as I was on new machine (space in my username that shouldn't have been there)

**Comment by radeusgd** [comment]
> Yes I signed the CLA. But think I upset the bot as my original commit had the wrong user name, as I was on new machine (space in my username that shouldn't have been there)

Hmm, I see. @mwu-tow could you have a look into this please?

**Review by hubertp — APPROVED** [review]

**Comment by mwu-tow** [comment]
I have no idea what's wrong with the CLA assistant. I'd expect it checks the username of PR contributor, not username in commits. 
Still, I see that the CLA was signed by @IsaacTell so I'll simply force-merge this rather than fight the assistant.

All CI failures seem to be spurious, caused by limited privileges of external fork build.

**Pull request merged**
