### PR TITLE
"Keyboard shortcuts" settings page

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/896
  - Add new settings page for viewing and editing keyboard shortcuts
  - Refactor shortcut manager to resemble GUI2's shortcuts module
- Minor refactor moving `dashboard/layouts/dashboard` to `dashboard/layouts`; and moving all moals to `dashboard/modals`

### Important Notes
- The modal for capturing keyboard shortcuts has not been tested on macOS.

### Screenshots
Main settings page. Scrollbars are unstyled as the screenshot was taken on Firefox.
image

Buttons for removing, adding, and resetting the list of shortcuts for a specific action:
(These buttons appear on hover, similarly to the `(+)` on the "Labels" and "Shared with" columns)
image

Keyboard shortcut input modal (no shortcut entered):
image

Keyboard shortcut input modal (shortcut entered):
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. When trying to assing `cmd + <anything>` I end up with double `cmd` (although it seems to work)
Screenshot 2024-02-26 at 16 24 57

2. We should not allow to assing the same key / combination multiple times. Making input red and small info that this combination is taken should be enough

3. What's the difference between `move to trash` and `delete` (+ all)

4. On local `Backspace` is activating search bar

5. Some combinations occurs multiple times within the same action
Screenshot 2024-02-26 at 16 41 43

**Comment by somebody1234** [comment]
1. will need to investigate
2. will do
3. this is a limitation of the current system - to display different text, they need to be different shortcuts... but on second thought - it's probably a better idea to simply override the text. will address soon.
4. it's possible that this is because i don't handle `Delete`. will check.
5. very weird, will investigate.

**Comment by somebody1234** [comment]
the latest commit *only fixes merge conflicts*.
only issue 3 has been addressed so far - the rest may be addressed tomorrow.

**Comment by somebody1234** [comment]
(another merge to fix conflicts. issues still not addressed.)

**Comment by somebody1234** [comment]
1. i think i found the problem but as usual cannot test.
2. TODO. this is the biggest task so i left it for last.
3. already addressed
4. also fixed but needs testing.
5. can't repro. will probably have to ask you to try some things tomorrow

**Comment by somebody1234** [comment]
update: all issues other than number 5 should now be fixed.

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
