### PR TITLE
Fixing build scripts to work on Apple Silicon.

### PR DESCRIPTION
**Pull request by wdanilo**
[ci no changelog needed]

### Pull Request Description

Currently, Enso does not build on Apple Silicon (like the M1 processor). This patch fixes the issues.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

**Comment by MichaelMauderer** [comment]
Does this issue affect whether our normal release builds work on Apple Silicon devices? If so, do we also need a new extra build to deploy to Apple Silicon?

**Review by mwu-tow — CHANGES_REQUESTED** [review]
Given that `curl` crate update has just landed that addresses this issue without requiring changes to the environment, I'd rather see it used.
See https://github.com/rust-lang/cargo/pull/10106/files

**Comment by wdanilo** [comment]
> Given that `curl` crate update has just landed that addresses this issue without requiring changes to the environment, I'd rather see it used.
> See https://github.com/rust-lang/cargo/pull/10106/files

Have you tried it? I do not understand how this could help here. The error we are facing is from `rustc`. I've reported it there, it is still an open issue in the compiler repository (the issue is linked in the comment). How changing curl in our codebase can affect the compiler error?

**Comment by wdanilo** [comment]
> Does this issue affect whether our normal release builds work on Apple Silicon devices? If so, do we also need a new extra build to deploy to Apple Silicon?

GUI builds no. Engine builds yes. Engine needs to be build for native M1 arch to get the right performance. Without it, users that do not have developer tools installed (with intel instruction set virtualisation) would not be able to use Enso.

**Comment by mwu-tow** [comment]
@wdanilo 
> Have you tried it? I do not understand how this could help here. The error we are facing is from `rustc`. I've reported it there, it is still an open issue in the compiler repository (the issue is linked in the comment). How changing curl in our codebase can affect the compiler error?

1. I have not tried, I don't have access to Apple Silicon machine. If it does not help, just let me know and I'll retract my comment.
2. The you linked issue describes that while this is a `rustc` issue, it is triggered by quite unusual code pattern of linking with C code. `curl` triggers this bug. Also, that issue has comments of people that were able to avoid this problem by using the latest `curl` that worked around this issue. No need for each crate that is using `curl` as a dependency to add this workaround on their own.

**Comment by wdanilo** [comment]
@mwu-tow I'll try that during weekend and let you know.

**Comment by mwu-tow** [comment]
> @mwu-tow I'll try that during weekend and let you know.

@wdanilo  In the meantime bug in Rust got fixed. It should be then enough to just bump toolchain to the latest nightly.

**Comment by wdanilo** [comment]
@mwu-tow amazing to know that!

**Pull request closed without merging**
