### PR TITLE
Drag and drop

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/697
  - Adds infrastructure to support drag-and-drop
  - Implements drag-and-drop for deleting and undeleting assets
  - Implements drag-and-drop for moving assets to a new directory (or the root directory)
- Also implements "cut" and "paste" context menu actions (and keyboard shortcuts) using the new endpoint for moving files
  - "Copy" and "duplicate" actions are *not* implemented, as I don't think there are backend endpoints for those yet.
  - Fades items out when cutting (Cmd+X), fades them back in when cancelling (Esc)
- Fixes bug where keyboard shortcut handlers were not registered for table-wide shortcuts (delete all, restore all, cut all)

### Important Notes
Drag-and-drop for more situations are planned but intentionally not yet implemented:
- Labels (backend is WIP, and blocked on the corresponding frontend PR)
- Moving assets between folders (backend functionality does not yet exist)

### Screencast

https://github.com/enso-org/enso/assets/4046547/28453c8f-8a49-47cf-96f3-81a3b3ee9250

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
@PabloBuchu dnd to directories should work now. i've implemented cut-and-paste as well, because the backend endpoints (*and* logic for moving assets to the new location) are already here

**Comment by PabloBuchu** [comment]
1. whats this weird earth icon that flies to the cursor when drag something?
Screenshot 2023-10-11 at 10 40 21

2. I can move directory and drop on itself making it disappear. Probably we need to fix both on be / fe this

**Comment by somebody1234** [comment]
1. very weird... the earth icon seems to maybe (?) be because i use a blank element as the drag image? no clue why that happens though, it doesn't happen for me on linux. as usual, still an issue but it means it will be difficult for me to debug. if there's no extra request for a nonexistent image i have no clue what it might be. i can try setting the div to 1px by 1px tomorrow, if macos doesn't like it when the placeholder drag element is 0px by 0px
2. will fix tomorrow.

**Comment by PabloBuchu** [comment]
Its flying towards my cursor :) no request for the image although there are 2 requests PATCH and 1 OPTIONS being send on drop

https://github.com/enso-org/enso/assets/2855109/24613f60-6d7b-413c-bc2e-ac6e3aff669a

**Comment by somebody1234** [comment]
note to self: i forgot to fade the icons out after they have been cut

**Comment by somebody1234** [comment]
oh, also being able to cancel a cut operation with <kbd>Esc</kbd>

**Comment by somebody1234** [comment]
@PabloBuchu a number of issues should be resolved now. as i'm not sure what's up with the safari issue, i can't confirm that it is *fixed* now, but i have implemented a *potential* fix. let me know if it is still an issue, and i can try implementing a different fix.

**Comment by somebody1234** [comment]
weirdly enough, i can't manage to find any info about this issue on the internet.

**Comment by PabloBuchu** [comment]
A glitch when dragging an object from nested structure. Also how hard would it be to add small higlight of the directory on which we are dropping (you want to do it with this PR or as seaprate, improvement?)

Screenshot 2023-10-13 at 13 07 59

**Comment by somebody1234** [comment]
@PabloBuchu oh, didn't see this comment - glitch should now be addressed. as for the highlight, that should also be implemented - it was relatively easy as the frontend is already listening to drag events anyway, to determine when to show the cursor as being able to be dropped (the drag cursor with the (+))

**Comment by PabloBuchu** [comment]
Yeah the highlight works but the directory stays selected and it can not be unclicked untill I move something else.. @somebody1234 please can you QA your changes before reporting something is delivered? this should be caught before pushing..

https://github.com/enso-org/enso/assets/2855109/a34b1ccd-8e89-4422-b686-5f5f558983ed

**Comment by somebody1234** [comment]
@PabloBuchu yeah, sorry. normally i do try to QA the changes, but i probably do need to make sure i test them more thoroughly.

... on second thought maybe this is something the visual regression tests (playwright tests) would be useful for?

**Review by PabloBuchu — APPROVED** [review]

**Comment by 4e6** [comment]
@somebody1234 this commit gives me the following error when I try to run ide with `$ npm --workspace=enso-gui2 run dev`. Do I need to clean something?
```
assetsTable.tsx:154 Uncaught TypeError: Cannot read properties of undefined (reading 'recent')
    at assetsTable.tsx:154:32
(anonymous) @ assetsTable.tsx:154
```

2023-10-16-162839_1427x1033_scrot

**Comment by somebody1234** [comment]
@4e6 i think so. you can try either `rm -r node_modules/.cache/` (and potentially `app/gui2/node_modules/.cache/` if it exists), and/or `npm ci` (or `npm i`), or `./run git-clean` then `npm ci`/`npm i` as a last resort i guess

**Comment by somebody1234** [comment]
actually i can reproduce... i'll check what's going on

**Comment by somebody1234** [comment]
ah... seems like a circular import. i'll make a hotfix PR for this asap

**Comment by somebody1234** [comment]
@4e6 PR opened at #8078, you can double check that it fixes the issue if you want

**Comment by 4e6** [comment]
Thank you! :heart:

**Pull request merged**
