### PR TITLE
Fix benchmark actions

### PR DESCRIPTION
**Pull request by Akirathan**
### Pull Request Description

Fix engine-benchmarks and std-libs-benchmarks actions that have been failing since #7991.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [X] The documentation has been updated, if necessary.
- [X] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [X] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [X] Unit tests have been written where possible.
  - [X] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by Akirathan** [comment]
@mwu-tow https://github.com/enso-org/enso/pull/8350/commits/f8c25cbb0e2ef99d9792dd432f234ab42fda8437 fixes [Benchmark Engine](https://github.com/enso-org/enso/actions/workflows/engine-benchmark.yml) and [Benchmark Standard Libraries](https://github.com/enso-org/enso/actions/workflows/std-libs-benchmark.yml) actions. Please, push any changes needed to also make the [Nightly Release](https://github.com/enso-org/enso/actions/workflows/nightly.yml) work.

**Comment by Akirathan** [comment]
I have just manually started https://github.com/enso-org/enso/actions/runs/6942823371 - a dry run of Engine benchmarks.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@f8c25cb</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment]
@mwu-tow, this PR [fixes InvalidaPathException](https://github.com/enso-org/enso/actions/runs/6938355119/job/18876398495#step:10:938) which is also happening in the nightly builds. As a result we don't have benchmarks and don't have daily builds right now. Can you please approve/integrate this quickfix (use it in daily builds as well) so we unluck everyone who's waiting for daily build or benchmark results?

**Review by jdunkerley — APPROVED** [review]

**Comment by Akirathan** [comment]
Dropping this PR in favor of https://github.com/enso-org/enso/pull/8285 that contains better fixes for the `LC_ALL` problem, among other fixes.

**Pull request closed without merging**
