### PR TITLE
Auth flow improvements

### LINKED ISSUE #7447: Improvements to sign up flows
image
We should include sign up in the Google and Git Hub text, as you click those to create an account.

image
On the direct sign up, password validation should be on enter of text not on submit.
Likewise, if the confirm does not match the validation should be of the same style as the first box (currently a notification) and occur on typing in the second box.

### LINKED ISSUE #7449: When clicking on the cloud icon if not logged in should be taken to log in screen.
Currently when you click on cloud icon in "offline mode" you get taken to an error message:
image

First, the "You are offline" text feels wrong. It should be something like "You are not signed in.".
It should also offer the log in boxes on that screen.

image
Likewise the text on the user icon should be "not signed in" rather than offline.

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fixes #7447
  - Change "login to X" to "sign up or login to X"
  - Trigger validation after a delay
- Fixes #7449
  - Change "offline" to "not signed in"
  - Add "login" button to cloud backend

### Important Notes
Feel free to suggest improvements to the appearance.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
@jdunkerley you may want to test out this PR

**Comment by jdunkerley** [comment]
The text changes and new log in link look great.

The validation on every character typed is too aggressive, I think something like:

- on defocus of a text box
- after a brief timeout following a keypress (so we don't validate as the user types everything but only when they pause).

The message for the confirm box should be updated as well. Instead of "Please match the format requested" should just be "Passwords do not match.".

**Comment by somebody1234** [comment]
@jdunkerley i think there's no way to avoid the "please match the format requested" message, because that is a system notification generated by chrome. we could have custom error dialogs in HTML instead - what do you think?

as for the validation stuff - yeah that's a good idea, will do.

**Comment by jdunkerley** [comment]
No need to change the format for the confirm we can just live with that error.

**Comment by somebody1234** [comment]
never mind... found a way to change the first line of the error.
i've been running into issues getting debouncing to work correctly though. specifically, `reportValidity` acts weirdly (after calling it once, the dialog appears continuously)

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
