### PR TITLE
Revert "Show spinner when opening/creating a project, take #2 (#6827)"

### LINKED ISSUE #7163: IDE does not retry to open project
Some time ago, [I've implemented](#5802) retry mechanism for IDE initialization to make it more robust in the cloud environment. However, currently it does not work if the _opening_ of the project fails: we instead print an error log and leave the IDE in the unopened state.

Instead, we should retry several times, and if the all tries fail: _show the error to the user_ and block the view from any interactions (as there is no point in adding nodes, for instance).

### PR DESCRIPTION
**Pull request by farmaazon**
This reverts commit 0ed78f99afbdb3654cf705f28278e66394a73b71.

Fixes #7163 

As it turned out, the issue with missing retries is quite important, because IDE does not launch on weak hardware. Reverting that commit is an easy way to fix it (and the loading spinner could be implemented in a better way, with cooperation with the new dashboard).

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- ~~[ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by farmaazon** [comment]
I expected the revert will just remove the "second" loading screen, but it's still there giving strange effect:

https://github.com/enso-org/enso/assets/3919101/7397f0a8-f601-41ee-bb13-c2ff9a0a0603

@PabloBuchu @somebody1234 as you know the dashboard more or less, do you know if there is some code in dashboard which makes the second loading screen? I haven't found anything in rust code.

**Comment by somebody1234** [comment]
oh you mean does the dashboard explicitly run a loading spinner? afaict no - the dashboard code actually doesn't have a full-screen loading spinner (nor one with the logo)
it's possible the entry point triggers the spinner somehow via the loader, but i don't think that should happen either.

i can see some logs are seemingly duplicated, may that be related?
it reminds me of React logging things twice in its debug mode, so it _may_ be caused by debug mode?

**Comment by somebody1234** [comment]
if it's possible to set a breakpoint on `show_progress_indicator` that might help with debugging?
alternatively you could try `-authentication=false -feature=preview.new-dashboard=false -startup.project=<project here>` which *should* be equivalent (and so should theoretically show only one spinner, if the dashboard is probably the cause)

**Comment by jdunkerley** [comment]
Testing on a weak VM this fix works and can get a not very usable but at least working instance of Enso.

**Comment by farmaazon** [comment]
Hmm, the effect is gone after merging develop. I like it.

Now, I only need an owner's accept. @MichaelMauderer or @wdanilo

**Review by MichaelMauderer — APPROVED** [review]

**Pull request merged**
