### PR TITLE
Implement documentation IR

### PR DESCRIPTION
**Pull request by vitvakatu**
### Pull Request Description

[Task link](https://www.pivotaltracker.com/story/show/184012434)

This PR implements Intermediate Representation for our documentation. Later these data structures would be used to generate HTML and CSS for the documentation panel. For now, we display it in the debug scene.

https://user-images.githubusercontent.com/6566674/210674850-480a3e6e-76c3-4f34-a235-15c44dc9ec01.mp4

### Important Notes

- `suggestion-database` now lives in a separate crate
- also, two utility crates were introduced for the `notification` and `executor` modules of enso-gui
- documentation debug scene is moved to a separate crate
- All refactorings are done in the last two commits

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]
❤️

**Comment by vitvakatu** [comment]
I just realized that the current layout of crates wouldn't allow using this IR for actual HTML generation in view. I need to refactor it a bit, so PR is WIP.

**Comment by vitvakatu** [comment]
PR was updated and reopened. In the last two commits, I moved the suggestion database into a separate crate, so now it can be used in the documentation demo scene and the implementation of the HTML generator.

**Review by wdanilo — APPROVED** [review]

**Comment by irdkwmnsb** [comment]
Dear @vitvakatu 
Since it looks like that's the only way we can expect you to read our message, we must do it here.
We are students from ITMO University of which you might have forgotten about.
It's currently our finals month and the students' homework aren't checked, and we know nothing about our grades.
Please, spare us some of your time.
This is a serious issue since if we fail your course we might get expelled and drafted into the army to participate in the Russian—Ukrainian conflict.
Thank you in advance.
And sorry enso-org for this message. We hope you will understand us.

**Pull request merged**
