### PR TITLE
Add COOP+COEP+CORP headers

### LINKED ISSUE #6645: Map visualization is not working anymore
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The map visualization is blank. It was working correctly on the package yesterday. I am assuming one of the commits from @somebody1234 broke loading the visualizations. Please confirm and fix it.

### Expected behaviour

Map visualization visible

### How we can reproduce it?

Open Restaurants example and see if the map is visible there.

### Screenshots or screencasts

_No response_

### Enso Version

nighty 11.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fixes #6645.
Re-implements #6597, with fixes included.

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
not tested as i am currently unable to build. i'll do a reboot soon, but for now maybe @PabloBuchu could test whether this fixes the issue?

**Comment by somebody1234** [comment]
never mind, build actually worked :o

**Comment by somebody1234** [comment]
ok this fix doesn't work: `net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200`

**Comment by somebody1234** [comment]
i *am* getting a different error but i don't think it's related, as this is a CORS error caused by the destination URL missing CORS headers. however, the code has been here for a while and there were no problems previously, so not sure why it's a problem now
image

**Comment by somebody1234** [comment]
correction: looks like it *is* caused by this change... not sure whether there's a good solution though

**Comment by somebody1234** [comment]
because of the change in ide code, i think testing must not use `--backend-source release --backend-release latest`??? or maybe the wasm needs to be rebuilt, not sure why it isn't getting rebuilt

**Comment by somebody1234** [comment]
error no longer in console. font seems to be working again:
image
broken font (well, the fallback on my system at least) for comparison:
image

**Comment by PabloBuchu** [comment]
qa 🟢 but lets wait with merge for https://github.com/enso-org/enso/pull/6605

**Comment by sylwiabr** [comment]
@wdanilo can you do the PR review here?

**Comment by PabloBuchu** [comment]
@sylwiabr PR was done previously. We just added fix for maps visualisation here

**Review by wdanilo — APPROVED** [review]

**Comment by wdanilo** [comment]
Let's merge it! But there are some conflicts now.

**Review by PabloBuchu — APPROVED** [review]

**Comment by wdanilo** [comment]
@PabloBuchu @somebody1234 I've got a question – how that was not noticed not watched during Q/A that when you start the app the warning is printed to console:

image

Which clearly shows that it is still broken?

**Comment by somebody1234** [comment]
that is a source map, which is not required to run the js script. mapbox itself should work, not sure whether there is a way to get rid of the error. i figured it would be safer to not special-case source maps, but we could explicitly allow them by setting a less restrictive CORP header maybe?

**Comment by somebody1234** [comment]
but yeah, we should probably have mentioned that before merging it in...

**Comment by wdanilo** [comment]
ahhh that's source map! Ok, uff ,that's much smaller than I thought. Ok, lets fix it in a separate PR then :)

**Pull request merged**
