### PR TITLE
Rework `ide-desktop` CI

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Refactors `ide-desktop` CI to move all the logic to JS. This should allow management of JS linting (almost) fully within the JS source tree.

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by indiv0** [comment]
Could you expand on what "This should allow management of JS linting (almost) fully within the JS source tree." means? Or rather, do you have an example of the benefit this provides?

**Comment by somebody1234** [comment]
well... the build script has been changed to run `npm run lint` - which should mean, in the future all that needs to be done would be to edit the `"lint"` npm script to add tasks to/remove tasks from/edit/fix JS linting. not sure this is that much of a *benefit* though

**Comment by somebody1234** [comment]
for me `./run lint` seems to still be working correctly, and it's running `npm run lint` in the right directory (as expected), which in turn does seem to run `npm install` and `npm run typecheck` and `npx eslint .` as expected

**Review by mwu-tow — APPROVED** [review]

**Comment by indiv0** [comment]
QA passed! Looks like there's an engine CI failure though :)

# Scenarios

- ✅ `./run git-clean && ./run lint` catches error

image

- ✅ `./run lint` succeeds when no error

image

**Comment by somebody1234** [comment]
i'll try rerunning - @indiv0 note that it does need an approving review before it can be merged though, because of the `package.json` change

**Review by indiv0 — APPROVED** [review]

**Comment by indiv0** [comment]
Thanks for the note. Approved :)

**Pull request merged**
