### PR TITLE
Fix a link in Readme.md and some punctuation.

### PR DESCRIPTION
**Pull request by audriu**
### Pull Request Description

Fix a broken link in Readme.md and some punctuation.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.

### CODE REVIEW

**Comment by audriu** [comment]
These changes are just Readme.md fixes but so many tests are failing. 
Especially interesting this one https://github.com/enso-org/enso/runs/8188909334?check_suite_focus=true
`if [[ false == false ]]; then exit 1; fi` LOL

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix a link in Readme.md and some punctuation. · enso-org/enso@ae6267c</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Review by mwu-tow — APPROVED** [review]

**Comment by mwu-tow** [comment]
> These changes are just Readme.md fixes but so many tests are failing.

This is currently expected for PRs created against repository forks -- some integrations and organization secrets are not available in such case.

> Especially interesting this one https://github.com/enso-org/enso/runs/8188909334?check_suite_focus=true
if [[ false == false ]]; then exit 1; fi LOL

It is not so stupid before GH Actions interpolates expressions:
```
         if [[ ${{ contains(steps.changed_files.outputs.list,'CHANGELOG.md') ||
          contains(github.event.head_commit.message,'[ci no changelog needed]') || contains(github.event.pull_request.body,'[ci
          no changelog needed]') || github.event.pull_request.user.login == 'dependabot'
          }} == false ]]; then exit 1; fi
```

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix a link in Readme.md and some punctuation. · enso-org/enso@ae6267c</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by mwu-tow** [comment]
@audriu  
The only relevant failure is in the `GUI CI / Lint` job that checks formatting.

Could you please run `prettier` on the readme file?
Or, if you have dev environment set up, can use `./run fmt`.

**Comment by audriu** [comment]
Just ran `./run fmt` and committed.

**Comment by mwu-tow** [comment]
Perfect, I'll proceed with merge.
Many thanks for contributing @audriu, and sorry for the rough edges in the process!

**Pull request merged**
