### PR TITLE
Dashboard improvements

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix most of https://github.com/enso-org/cloud-v2/issues/1322
- Implement https://github.com/enso-org/cloud-v2/issues/1323

### Important Notes
N/A

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. Having issues with cache (see video) not sure it misses latest develop or bug


https://github.com/enso-org/enso/assets/2855109/2024979d-2cd4-40a8-bd36-dda6e0151d2d

**Comment by PabloBuchu** [comment]
2 small fixes. The rest looks nice. QA ✅ 

1. Wasn't clear enough. `Recent` should also be moved similar to `Trash`
2. Copy as path works fine for `File` and `Directory` for other `Asset` we need to add type suffix. I will create an improvement for that. Maybe we should store the path on backend side and return in in list directory request
3. `Shouldn't have a download on a local folder.` I think this was not implemented

**Comment by somebody1234** [comment]
ohhh
> Shouldn't have a download on a local folder.

i was wondering what this meant (i was looking in the Drive Bar) - i guess you mean in the context menu


also yeah ideally FE gets the path in the list directory request, this way we don't have to do any hackiness in the Local Backend which currently uses ids as paths

**Comment by somebody1234** [comment]
@PabloBuchu i *think* the small fixes have been addressed now

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
