### PR TITLE
Fix build of engine benchmarks

### PR DESCRIPTION
**Pull request by Akirathan**
### Pull Request Description

After #8467, Engine benchmarks are broken, they cannot compile - https://github.com/enso-org/enso/actions/runs/7268987483/job/19805862815#logs

This PR fixes the benchmark build

### Important Notes

Apart from fixing the build of `engine/bench`:
- Don't assemble any fat jars in `runtime/bench`.
- Use our `TestLogProvider` in the benches instead of NOOP provider.
  - So that we can at least see warnings and errors in benchmarks.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] Try to run benchmarks manually and ensure there are no regressions.

### CODE REVIEW

**Comment by Akirathan** [comment]
Manual benchmark run scheduled at https://github.com/enso-org/enso/actions/runs/7297673595

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@eeacfc0</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Review by hubertp — APPROVED** [review]

**Comment by Akirathan** [comment]
The comparison of the benchmarks to `develop` are in [generated_site.zip](https://github.com/enso-org/enso/files/13751568/generated_site.zip).

The `ListBenchmarks` are slower, but that is expected, since I have added some imports so that the compiler does not produce warnings about non-existent symbols.

`org.enso.interpreter.bench.benchmarks.semantic.EqualsBenchmarks.equalsTrees` seems to be slower, but that is most likely because the warmup is set to a very low amount, as can be seen in the [bench output](https://github.com/enso-org/enso/actions/runs/7297673595/job/19887311954#step:10:2032) (If JMH reports only a single number, it suggests that the number of iterations of the benchmark was too low).

Other benchmarks stay the same. Let's merge this PR.

**Comment by JaroslavTulach** [comment]
This PR seems to cause some slowdown in `EqualsBenchmarks` and its `equalsTrees` test:

obrazek

CCing @Akirathan

**Comment by JaroslavTulach** [comment]
There seems to be slowdown in `ListBenchmarks` and its `mapOverList` caused by this PR:

obrazek

CCing @Akirathan

**Comment by Akirathan** [comment]
> There seems to be slowdown in `ListBenchmarks` and its `mapOverList` caused by this PR:
> 
> obrazek
> 
> CCing @Akirathan

Slowdown in `ListBenchmarks` is expected, as I have added some imports to the benchmarks in https://github.com/enso-org/enso/pull/8620/files#diff-ecbf82e01818e317cb89c77fc685e8cdc57be26e15b4ca9239d05c2d7afe9d3e. Without these imports, the compiler was complaining about "No such symbol `Text`" and similar. We apparently do not run benchmarks in strict error mode, but even so, I think it is sane to add these imports.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/8620">Fix build of engine benchmarks by Akirathan · Pull Request #8620 · enso-org/enso</a></strong></div><div>Pull Request Description
After #8467, Engine benchmarks are broken, they cannot compile - https://github.com/enso-org/enso/actions/runs/7268987483/job/19805862815#logs
This PR fixes the benchmark b...</div></blockquote>

**Comment by Akirathan** [comment]
> This PR seems to cause some slowdown in `EqualsBenchmarks` and its `equalsTrees` test:
> 
> obrazek
> 
> CCing @Akirathan

This is most likely caused by insufficient warmup iterations. We can see that by looking at the output in https://github.com/enso-org/enso/actions/runs/7297673595/job/19887311954#step:10:2025 :
```
 INFO ide_ci::program::command: sbtℹ️ # Warmup Iteration   1: 12.994 ms/op
 INFO ide_ci::program::command: sbtℹ️ # Warmup Iteration   2: 9.656 ms/op
 INFO ide_ci::program::command: sbtℹ️ # Warmup Iteration   3: 7.697 ms/op
 INFO ide_ci::program::command: sbtℹ️ Iteration   1: 5.981 ms/op
 INFO ide_ci::program::command: sbtℹ️ Iteration   2: 4.530 ms/op
```
Optimally, a few last warmup iterations should produce the same score.

I am solving this issue in https://github.com/enso-org/enso/pull/8636

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Benchmark Engine · enso-org/enso@eeacfc0</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Pull request merged**
