### PR TITLE
Fix leaks in input/output areas by partial revert of #3451.

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fix a memory leak introduced by #3451. Found this to be part of the cause of [the buffer leaks](https://www.pivotaltracker.com/story/show/181943457/comments/231558434).

The problem with this use of `define_endpoints_2` is,
- The FRP network contains (strong) references to the `Model`.
- The `Model` has a strong reference to `api::Private`, which owns the FRP network.

Thus we never free the `Model`.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide dist` and `./run ide watch`.

[ci no changelog needed]

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]
Perfect! Please add a FIXME comment next to `define_endpoints` with this info, so when we will be migrating to `define_endpoints_2` in the future, we will remember about this corner case.

**Comment by kazcw** [comment]
I added in a fix for another leak that turned out to be related. In the *input* area, since #3451, we have the same leak; it's a little more indirect in this case:
- Model owns the ports; the ports' networks keep references to the input area's `frp.private`.
- The `frp.private` owns the network; the network references the Model.

**Comment by kazcw** [comment]
The pattern to these bugs is: We have a backlink from a field or child of the model to the FRP network. With `define_endpoints`, this backlink is a reference to the `FrpEndpoints`, which *weakly-references* the network; with `define_endpoints_2`, the backlink is a reference to the `api::Private` that *owns* the network.

I'm not sure how this should be fixed. @MichaelMauderer Any thoughts on what we should be doing about these backlinks when porting to `define_endpoints_2`?

**Comment by kazcw** [comment]
(I meant to disable automerge until the new changes were reviewed. Oops.)

**Pull request merged**
