### PR TITLE
Add copy button to component messages.

### LINKED ISSUE #9878: Allow copying of text from errors and warnings
When you get an error:
There isn't an easy way to get the text for copy/paste for reporting  the isssue.

image

Can we allow the selection and copying of the text?
Right click -> copy menu?

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Add button to component messages that copies the message to the system clipboard.

https://github.com/enso-org/enso/assets/1047859/ab645ecd-78d6-4602-b210-9f0041f4329b

Closes #9878.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by AdRiley** [comment]
Would we be able to make the background of the button the same color as the error or warning or panic by default and then change color on hovor?

**Comment by farmaazon** [comment]
I implemented this. I wanted to post screencast, but... my screencasting tool broke and tried to find working replacement.

**Comment by farmaazon** [comment]
Also, added a code which makes copy-icon take precedence over output port (but icon only, not message panel).

**Comment by farmaazon** [comment]
No luck in finding screen recorders, so put pictures instead:

image

image

**Comment by AdRiley** [comment]
Could we use my new copy2 icon please? https://github.com/enso-org/enso/pull/10036 

I think the simpler icon will look better here (and feel like it is more standard)

**Review by Frizi — APPROVED** [review]

**Pull request merged**
