### PR TITLE
Fix permissions for Asset Panel for Team-owned assets

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix https://github.com/enso-org/cloud-v2/issues/1452
  - Previously, the team's permission was not being detected as the user's own permission

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
pinging @PabloBuchu for QA. i'm assuming CR is optional since it's a very small change

**Comment by PabloBuchu** [comment]
I found two bugs that might be fixed here ;)

1. When you create asset in team space in share with we autmatically add request user as owner rather than user group (after reload everything is as it should be)
2. I can't submit new datalink form with:
Screenshot 2024-09-03 at 12 30 52

**Comment by somebody1234** [comment]
@PabloBuchu both should finally be addressed. pushing right now, should be ready for QA afterwards

**Comment by somebody1234** [comment]
well actually number 2 is fixed, number 1 i forgot to address

**Comment by somebody1234** [comment]
ok
> When you create asset in team space in share with we autmatically add request user as owner

cannot repro - neither in root under `Teams/the-team/`, nor in the sidebar category for the specific team (and can confirm in code that theoretically both cases SHOULD be handled)

(specifically: this should have been working on `develop` for a while now)

**Comment by PabloBuchu** [comment]
1. New datalink and new secret context menu action are broken
2. New datalink form is still bugged when I try to create a datalink in `Users/Teams` view see the video.  I think assets should be appended developed catalog rathe than to org directory (which will fail)

https://github.com/user-attachments/assets/c8bbd3c1-5fb2-4c10-b7b0-bb49b8dd0d9c

**Review by MrFlashAccount — APPROVED** [review]

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
