### PR TITLE
Optimize AliasAnalysis hotspot

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

`scopeFor` is a real hotspot that hasn't been particularly optimized. By using iterator and a simple variable instead of a list and checking its length I was able to get 10% speedup.
Note that it seems tempting to throw the exception within the loop but that seems to create a less optimized code.

### Important Notes

I'm consistently getting ~10% speedup on a hello world example (with standard libraries).

For example I'm no longer seeing 20ms spent in `scopeFor` and most of them are below 10ms:
Screenshot from 2024-01-08 12-15-30

Before
Screenshot from 2024-01-08 12-17-32

After
Screenshot from 2024-01-08 12-17-09

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
Nice finding!

From a _strategic perspective_ we should first address
- #8419

and only then integrate this bugfix. Then we could demonstrate on the graphs how much we do care about _static compiler speed_.

On the other hand, we do have the `Startup_empty_startup` benchmark and if that one is improving, then we have an (at least indirect) evidence as well.

**Review by Akirathan — APPROVED** [review]
Very nice improvement. Just out of curiosity: Do you have profiling snapshots? If so, please attach some screenshots from them.

**Comment by hubertp** [comment]
Yes, I agree we need proper benchmarks. As I talked to @4e6 I think there is a big scope for improving the compiler performance, we haven't even started.

I was hoping that `Startup` benchmark will confirm my numbers. Started it.

I also added some screenshots. It's a bit hard to show but basically traversing a list is gone.

**Comment by hubertp** [comment]
Screenshot from 2024-01-08 15-28-57

hmm, that's weird. it looks like no difference? I'm clearly getting better results locally :thinking:

**Comment by hubertp** [comment]
Maybe the reason is because it is not built against latest develop. I will retry.

**Comment by hubertp** [comment]
Screenshot from 2024-01-09 10-15-09
I think something is wrong with the benchmark because I'm clearly getting improvements locally. Not sure what to do with that one for the time being.

**Review by 4e6 — APPROVED** [review]

**Comment by hubertp** [comment]
Here are files with VisualVM samping 
[before](https://github.com/enso-org/enso/files/13874602/hw-io-alias8-no-optimize.npss.txt) and [after](https://github.com/enso-org/enso/files/13874605/hw-io-alias8-with-optimize.npss.txt)

**Pull request merged**
