### PR TITLE
Offer no suggestion for single constructor

### LINKED ISSUE #5055: Dropdown for Table.join right is wrong
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184379354).
<hr />

Discovered during [book clubing](https://discord.com/channels/401396655599124480/1065951201860001792/1068417429891469363).

There is a drop down for `Table.join` `right` argument! And it offers `Table.Value`. `Table.Value` is just a function which needs a parameter of `java_table`, so it makes no sense to offer it as `tag_value`.

## Comments:
 (jaroslavtulach - Feb 2, 2023)
<hr />

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

Resolving #5055 - avoid putting single constructor into suggestion database.

### Important Notes

Another way to fix #5055 is to keep the single constructor information in the suggestion database and let the IDE filter that out.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by jdunkerley — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
@jdunkerley seems to be OK with this change. What do @4e6 and @hubertp think?

**Review by hubertp — COMMENTED** [review]
So what about `Pair.Value`? that takes two parameters, should that not be reported in suggestion DB either?

**Comment by JaroslavTulach** [comment]
> So what about `Pair.Value`? that takes two parameters, should that not be reported in suggestion DB either?

`Pair.Value` is a great example and there may be others.

`Pair.Value` is marked as `UNSTABLE` - users are likely supposed to use `Pair.new`. E.g. not including the constructor in suggestion DB in this case is probably OK... if that's what @Frizi and @jdunkerley want.

**Review by hubertp — APPROVED** [review]
I would probably limit this to a hardcoded `Value` to avoid some unexpected behaviour. Up to you if you want to include that.

**Comment by jdunkerley** [comment]
> > So what about `Pair.Value`? that takes two parameters, should that not be reported in suggestion DB either?
> 
> `Pair.Value` is a great example and there may be others.
> 
> `Pair.Value` is marked as `UNSTABLE` - users are likely supposed to use `Pair.new`. E.g. not including the constructor in suggestion DB in this case is probably OK... if that's what @Frizi and @jdunkerley want.

`Pair.Value` should indeed be hidden from users. `Pair.new` is supposed to be the method that users create it.

In general, the goal was that we wouldn't show a drop down for things with a single constructor as that (probably) isn't what we want.

**Pull request merged**
