### PR TITLE
Mark some tests as flaky on Windows

### PR DESCRIPTION
**Pull request by hubertp**
FS is not particularly reliable leading to FPs on CI.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]
> FS is not particularly reliable leading to FPs on CI.

Eh? I don't understand. Can you expand with some examples? "FS" probably standards for "file system". What does "FP" stands for? Probably not "floating point", right?

**Comment by hubertp** [comment]
> > FS is not particularly reliable leading to FPs on CI.
> 
> Eh? I don't understand. Can you expand with some examples? "FS" probably standards for "file system". What does "FP" stands for? Probably not "floating point", right?

FS - file system, yes.
FP - false positives.

Sorry for the shortcuts.

**Comment by JaroslavTulach** [comment]
> FP - false positives.

Do you really mean FP? E.g. the test passes even it should fail. Or do you mean FN? E.g. the test fails, while it should pass?

**Comment by hubertp** [comment]
> > FP - false positives.
> 
> Do you really mean FP? E.g. the test passes even it should fail. Or do you mean FN? E.g. the test fails, while it should pass?

The test fails (randomly) while it should pass. Depends how you define positive/negative ;)

**Pull request merged**
