### PR TITLE
Workaround for Electron sanbox issues on Ubuntu

### PR DESCRIPTION
**Pull request by hubertp**
### Pull Request Description

Disabling sanbox, while a non-secure option, appears to be currently the only option to workaround Electron issues on latest Ubuntu (24.04). When passed to Enso it is treated as a regular argument, preventing the start of the product.
This change treats `--no-sandbox` specially by ignoring all arguments that precede it (and including itself).

Related to #11035.

### Important Notes

This is not a final fix but a decent workaround that we could pass in the documentation.
Besides, so far it does not look like Electron will fix the problem.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.

### CODE REVIEW

**Comment by farmaazon** [comment]
Why do we ignore also the preceding arguments?

**Comment by somebody1234** [comment]
true, to ignore just that argument we can `.splice(index, 1)`. but do note that it mutates the array so we might want to `[...arr].splice()`

**Comment by hubertp** [comment]
> Why do we ignore also the preceding arguments?

Notice how in electron dev mode we do similar thing with `--`. I wanted to stay consistent as in general `--no-sandbox` _should_ not be used by users.

**Comment by farmaazon** [comment]
Well, `--` meaning of parting options in two is well established: sometimes as [marking the end of option list](https://unix.stackexchange.com/questions/11376/what-does-double-dash-double-hyphen-mean), sometimes as [separator between wrapper's and wrapped program's option](https://doc.rust-lang.org/cargo/commands/cargo-run.html). I cannot say it about `--no-sandbox`.

**Comment by hubertp** [comment]
@farmaazon Happy with the revised PR?

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
