### PR TITLE
Use the English locale for pretty-printing a Locale.

### PR DESCRIPTION
**Pull request by mwu-tow**
### Pull Request Description
The tests for `Locale` expect the English strings. However, no locale was specified for pretty-printing, leading to local locale being used on Windows.

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

**Comment by 4e6** [comment]
I believe this behavior is intentional. All functions are using the user's locale if it is not specified. The test should set up the desired locale instead.

**Comment by mwu-tow** [comment]
> 
> 
> I believe this behavior is intentional. All functions are using the user's locale if it is not specified. The test should set up the desired locale instead.

I don't know how to set this up, I'm not seeing API for this…?

**Comment by 4e6** [comment]
I suppose we need to refactor the test. I need to take a look otherwise it's hard to say how to fix it. Which one is failing for you?

**Comment by mwu-tow** [comment]
> 
> 
> I suppose we need to refactor the test. I need to take a look otherwise it's hard to say how to fix it. Which one is failing for you?

These two:
```rust
    Test.specify "should allow getting the display language" <|
        display = Locale.from_language_tag "en-GB" . display_language
        display . should_equal "English"
    Test.specify "should allow getting the display country" <|
        display = Locale.from_language_tag "en-GB" . display_country
        display . should_equal "United Kingdom"
```

**Comment by 4e6** [comment]
Locale tests were fixed in #3158

**Pull request closed without merging**
