### PR TITLE
Unify Frontend App

### LINKED ISSUE #8484: Merge dashboard and GUI2 to single project
Currently, the dashboard code and gui2 code are in completely different places (the former being a part of `ide-desktop`). They should be in a single IDE workspace. The current GUI2 should be rather named "project view".

### LINKED ISSUE #10668: Unify scripts for dashboard and GUI.
Now we have two vite configurations and thus two ways of building dev server (and everything else). This task is to unify the configuration (both vite.config and package.json) and stay with a single dev server, run in browser.

In this task also the relation between dashboard and GUI should be simplified: the dashboard should just have GUI as a dependency, and GUI part should not maintain any entry point invoking dashboard.

To consider: having both dashboard and current GUI in a single `app` subdir (`ide-desktop` being purely electron).

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description

Fixes #10668 
Fixes #8484

Summary of changes:
* `gui2` and `dashboard` are merged to `gui` directory. Various configs were merged (package.json, playwrigth, TS...). The src and e2e directories are split to `dashboard` and `project-view` for now.
* E2E tests run two servers on different ports. The tests are organized in projects. This is also to be changed soon, as we plan to [use better mocking in GUI/ProjectView](#9726)
* ESlint configs were merged to central `eslint.config.mjs`, and that file was moved to repository root. We kept the dashboard lints, but they can be relaxed. The dashboard code was changed to meet GUI lints.
* Also, the versions of linter plugins were bumped, and code fixed.
* The ide-desktop/client no longer has `dashboard` dependency - the only type used there was moved to common package.
* `common` package moved to `app`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.

### CODE REVIEW

**Comment by farmaazon** [comment]
We have still one problem with dashboard tests, but I think it's ready to review (the tests were working once after merging packages, so the issue should not be big).

**Review by Frizi — APPROVED** [review]
image

LGTM 👍

**Comment by somebody1234** [comment]
oops, it was a regression i introduced when fixing lints

**Comment by somebody1234** [comment]
```
  2 failed
    [Project View] › e2e/project-view/collapsingAndEntering.spec.ts:40:1 › Using breadcrumbs to navigate 
    [Project View] › e2e/project-view/componentBrowser.spec.ts:253:1 › Visualization preview: user visualization selection 
  1 skipped
  110 passed (3.7m)
```
all passing again except the usual flaky GUI tests

**Review by somebody1234 — APPROVED** [review]
approving to unblock, i'm assuming there have been no logic changes to dashboard files

**Review by AdRiley — APPROVED** [review]

**Pull request merged**
