### PR TITLE
Fix offline mode

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fixes offline mode immediately turning back into online mode

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
So the session is not being preserved when I enter the offline mode (`-authentication=false`) and then log in and then reload. Perhaps its because on reload we load the default value for the flags? 

https://github.com/enso-org/enso/assets/2855109/eec97aaa-f326-44f2-bea7-ddc4181327dd

**Comment by somebody1234** [comment]
yeah. it's easy enough to remove `authentication` from the flags on startup (after handling it for the first time)... what do you think?

**Comment by PabloBuchu** [comment]
are we able to remove it once user is logged in? If we remove it on startup and then I just reload then it would brake

**Comment by PabloBuchu** [comment]
qa 🟢

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
