### PR TITLE
Fix secrets, add "update secret" endpoint, fix search bar RWD

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fix https://github.com/enso-org/cloud-v2/issues/828
  - Fix appearance of search bar on small screens
- Close https://github.com/enso-org/cloud-v2/issues/830
  - Rename "Data Connector" back to "Secret" for now
  - Fix "create secret" endpoint
  - Add "update secret" endpoint
    - Repurpose "create secret" modal to also be usable for updating secrets
    - Add new context menu option for editing secrets
    - Add new shortcut (<kbd>Ctrl</kbd>+<kbd>E</kbd>) for editing secrets
    - Add double-click trigger for editing secrets
- Fix https://github.com/enso-org/cloud-v2/issues/831
  - Add the redirect, that was previously missing (only present in the very old dashboard)
- Fix https://github.com/enso-org/cloud-v2/issues/835
  - Fix search query not updating when clicking label in sidebar
  - Fix search query breaking when clicking a suggested label, after tabbing into a selection
- Fix https://github.com/enso-org/cloud-v2/issues/839
  - Make search query refresh when pressing <kbd>Enter</kbd>
- Fix some buggy behavior when applying autocomplete

### Important Notes
None

### Screencast

https://github.com/enso-org/enso/assets/4046547/3be89985-0882-4967-bedb-951db3ea9969

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
ignore the stretching of the screen at the end, that's because webm supports resizable videos but mp4 doesn't.
the important thing to note though, is that the search bar no longer does anything funky at any screen size

**Comment by PabloBuchu** [comment]
`create_secret` now returns just `secretId` encoded in json (with `"`). We should either adjust frontend to expect just string or I could add `return_type` optional param with `json` as value. @somebody1234 wdyt?

**Comment by PabloBuchu** [comment]
also ctrl+e is not working on mac

**Comment by somebody1234** [comment]
yup, frontend should already expect string.

as for the shortcut, I guess I'll change it - maybe it's being overridden by a system shortcut

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@somebody1234 qa 🟢 I aslo approved. Please fix ci actions and you can put `ready to merge`

**Pull request merged**
