### PR TITLE
Cognito auth 8/7 - fix prettier config; run prettier

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description

- Fixes prettier config to include `.tsx`
- `prettier -w .` has been run in `app/ide-desktop`
  - `prettier -w .` has also been run in `pack/js`, however there were no changes.

### Important Notes
After this is merged, a PR SHOULD be created to add the following file to the root directory:
`.git-blame-ignore-revs`
```
# <name of the commit for this PR>
<hash of the commit for this PR>
```
This makes `git blame` ignore the commit, which is a good idea since this PR only does formatting changes.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by wdanilo — COMMENTED** [review]
1. What is the status of this PR? I see that it has a lot of conflicts.
2. Regarding `⚠️ After this is merged, a manual commit to develop (or a PR) SHOULD be done to add the following file to the root directory:
.git-blame-ignore-revs` - there is no explanation of why this is needed and why it is not just part of this PR. Also, we are never doing manual commits to develop, so PR is the only option.

**Comment by somebody1234** [comment]
1. force-pushed. i think this is an acceptable time to force-push as the only thing that has been done is `prettier -w .`, and no chance of mis-merges > chance of mis-merges. also there were no comments on specific files that may disappear
2. edited original comment. basically, because this PR changes a *lot* of lines but doesn't change any logic, i think it would be good for `git blame` to skip over this commit.

**Comment by wdanilo** [comment]
1. But why you needed to force push instead of normal push?
2. Oh, that's interesting! I did not know about the `.git-blame-ignore-revs` file behavior! Good, lets do it this way :)

**Comment by somebody1234** [comment]
re: force push, i think it's just easier in this one specific case, because what it's *supposed* to do is:

1. `git checkout develop`
2. `prettier -w .`

and i think here it's easier just redoing these steps (and then force-pushing) rather than having to merge, potentially having to deal with an automated merge that retains some old code

plus because it's only the one step, i *think* reviews for specific lines would be out of scope, so the issue with losing comments shouldn't happen here

**Review by wdanilo — APPROVED** [review]

**Comment by indiv0** [comment]
QA: approved

- `./run ide build`: succeeds and runs
- `./run ide watch`: succeeds and runs

**Pull request merged**
