### PR TITLE
Run prettier on `CHANGELOG.md`; bump prettier

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Ran `npx prettier -w CHANGELOG.md`.
(side note: CI seems to be using a new version of prettier, whereas `/package.json` is using `"prettier": "2.8.1"` (an exact version. i'm using prettier@2.8.8 (newest) which does have minor differences in formatting, so we might want to consider bumping `prettier` to `2.8.8` on the root `package.json`)

### Important Notes
This will fix lint CI, which is failing for several current PRs

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by wdanilo** [comment]
Can we in the same PR bump the prettier so we are using the same version locally and on the CI, please? :)

**Comment by somebody1234** [comment]
done. it's worth noting that CI actually uses `^2.7.something`, but i'm not sure whether it's very much of an advantage to switch to `^` ranges at the root too, because `package.lock` will probably prevent the version from changing anyway.

**Comment by wdanilo** [comment]
I think the CI should also be locked, as if it updates things and breaks things accidentally, we will have similar problems in the future. CC @mwu-tow - what do you think?

**Comment by mwu-tow** [comment]
@wdanilo 
All `prettier` versions that we use should be part of the same lock file, so they don't diverge.

**Pull request merged**
