### PR TITLE
Merge Test_New into Test

### PR DESCRIPTION
**Pull request by Akirathan**
Follow-up of #8968

### Pull Request Description

Merges the temporary `Test_New` library into `Test`. This is the last PR in the series of PRs that refactor all the stdlib tests to the builder API.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by radeusgd — APPROVED** [review]
Does this do anything else other than:
1. `rm -rf Test`
2. `mv Test_New Test`
3. rename imports of `Standard.Test_New` into `Standard.Test`

If nothing non-trivial other than that, then it looks good :)

**Comment by Akirathan** [comment]
> Does this do anything else other than:
> 
> 1. `rm -rf Test`
> 2. `mv Test_New Test`
> 3. rename imports of `Standard.Test_New` into `Standard.Test`
> 
> If nothing non-trivial other than that, then it looks good :)

@radeusgd No, it doesn't do anything else. Just some marginal typo fixes after merges. Otherwise, it is this simple.

**Review by GregoryTravis — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]
Great job completing this.

**Review by hubertp — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
I was hoping to use the _last PR_ to through-fully review the testing API. However everyone else seems to be fine with the current state, so let's accept it...

**Pull request merged**
