### PR TITLE
Re-organize `lib/dashboard/`

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Significantly flattens directory structure of `lib/dashboard/`

### Important Notes
- Basic testing done on:
  - dashboard's `npm run dev` which (since quite recently) uses Vite.
    - specifically: `npm run dev` in `app/ide-desktop/lib/dashboard`, OR `npm run dashboard:dev` in `app/ide-desktop`
  - dashboard's bundle script (`npm run build`) which uses ESBuild.
  - GUI2's own entry point (GUI2's `npm run dev`).
  - `./run ide build`
  - `./run ide watch`
  - `./run ide2 build`
  - `./run gui watch`

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
restructure finished! the new directory structure might not be perfect, but i think this is probably worth merging regardless?

but anyway, given that it should be more or less complete, i'm now beginning to test using the `./run` script.

**Review by farmaazon — APPROVED** [review]
The /app/gui2 part looks good.

**Comment by PabloBuchu** [comment]
@somebody1234 please fix lin issues I will accept then

**Comment by somebody1234** [comment]
not 100% sure what's up with lint. it's possible that lint never worked properly with a clean build?
i've fixed the lint errors i get locally, but if this lint CI still fails i'll look into it further.

**Comment by somebody1234** [comment]
hopefully lint errors are fixed now... i guess we just have to wait and see

**Comment by somebody1234** [comment]
not sure why there was a merge error, automatic merged worked fine locally.

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
Basic testing re-done on all cases after merge.

**Pull request merged**
