### PR TITLE
Fix runtime-instrument-common benchmark

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

Fix the `runtime-instrument-common` benchmark compilation.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.

### CODE REVIEW

**Review by Akirathan — COMMENTED** [review]
I am surprised there even is a benchmark in `runtime-instrument-common`. If you think the benchmark has some value, why don't you move it into `runtime-benchmarks` so that this benchmark is actually run every day and we can keep track of its performance? Keeping benchmarks in other places than `runtime-benchmarks` or `std-benchmarks` does not make sense.

**Comment by 4e6** [comment]
I didn't know that it was not used. I thought it was silently failing on CI or smth. I'd rather remove it then

**Comment by Akirathan** [comment]
> I didn't know that it was not used. I thought it was silently failing on CI or smth. I'd rather remove it then

@4e6 It is not used anywhere, it is not tested anywhere, we don't observe the results ever. Therefore, I consider it *useless*. If it is not worth putting into `runtime-benchmarks`, I would rather remove it altogether.

PS: If you decide to remove it, please ensure that you also remove the `runtime-instruments-common/Bench` configuration from sbt. Let's simplify as many things as possible.

**Comment by JaroslavTulach** [comment]
This benchmark is supposed to measure speed of the `RuntimeCache`. The intention is good (measuring something like that would be good), but the realization is just too "naive".

- btw. #5027

Really **useful benchmark** would _compare running the same Enso code with and without instrumentation_ as done by language server.

**Review by JaroslavTulach — APPROVED** [review]
I have nothing against _fixing code that does not compile to compile_. I however agree with Pavel that usefulness of such an action is quite restricted when such a **code isn't used anywhere**.

**Pull request merged**
