### PR TITLE
Offline mode

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Adds offline mode. Disables the remote (cloud) backend when no internet connection is detected (`!navigator.onLine`). 

### Important Notes
None

### Screenshots
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
The `.enso.org` users whitelist stopped working. Now it works otherwise (block enabled and allows not enabled users)

Screenshot 2023-05-29 at 12 29 37
Screenshot 2023-05-29 at 12 35 42

**Comment by somebody1234** [comment]
might want to test by turning off wi-fi completely. not sure whether it's possible to simulate being offline without blocking localhost requests - neither the "network request blocking" tab nor the "throttling" option in the "network" tab are useful for testing.

**Comment by PabloBuchu** [comment]
Local project visualizations are not working when offline. 

Screenshot 2023-05-30 at 11 33 04

**Comment by somebody1234** [comment]
ah, nice catch. i wonder what's a good way to make this work?
i *think* a service worker is the normal way to do this, but not sure whether adding a service worker is acceptable.

we *are* already using service workers in dev mode, but that's mostly a workaround because the esbuild server cannot be configured

**Comment by PabloBuchu** [comment]
tbh we should download and cache the latest supported version on build time... probably like we do with `tailwind.css`

**Comment by somebody1234** [comment]
yeah that's definitely a good idea. i think a service worker might be an acceptable solution for the time being though, as it doesn't involve messing with the build scripts

**Comment by somebody1234** [comment]
pushed service worker... but on `localhost:8080` (gui watch with manually started PM, or ide watch) the GUI never receives `executionContext/executionComplete` so it's permanently stuck on "compiling standard library"

**Comment by PabloBuchu** [comment]
@somebody1234  Its even worse... panics when opening the project. did you try it before pushing?

Screenshot 2023-05-31 at 16 18 42
Screenshot 2023-05-31 at 16 18 36

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
