### PR TITLE
Add new aliases for take

### PR DESCRIPTION
**Pull request by AdRiley**
### Pull Request Description

Add some more aliases for take

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [ ] Unit tests have been written where possible.
  - [ ] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by jdunkerley — APPROVED** [review]

**Review by radeusgd — APPROVED** [review]
Where does `foot` come from in here?

**Comment by AdRiley** [comment]
> Where does `foot` come from in here?

James :) I think it is the opposite of head

**Comment by radeusgd** [comment]
> > Where does `foot` come from in here?
> 
> James :) I think it is the opposite of head

That's `tail` [usually](https://hoogle.haskell.org/?hoogle=tail), no?

I have never ever heard of `foot` being used in such a context.

**Comment by somebody1234** [comment]
or [`last`](https://hackage.haskell.org/package/base-4.19.1.0/docs/Prelude.html#v:last) perhaps

**Pull request merged**
