### PR TITLE
Fix `startup.project`

### LINKED ISSUE #7384: startup.project not working anymore
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Last week I was able to use:
`http://127.0.0.1:8080/?startup.project=Kadalian_Automotive_Sample`
to launch Enso directly into my project.
After rebasing to develop I now get the following message:
image

Nothing has changed with respect to the project name on my end.

### Expected behaviour

It should start into the startup project without error

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

1d2371f986c5a9d99db1c52ee6d5933ad42e33be

### Browser or standalone distribution

Chrome, Firefox (not supported officialy, but should work)

### Browser Version or standalone distribution

Mozilla Firefox 115.0.2

### Operating System

Linux

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Fixes https://github.com/enso-org/enso/issues/7384

### Important Notes
The only code that is changed should be asset loading code, so QA should focus around switching backends, `?startup.project` with local backend as saved backend, `?startup.project` with cloud backend as saved backend, things like that

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by JanBeelte** [comment]
Works in my use case!
Thanks for the super quick fix :+1:

**Comment by PabloBuchu** [comment]
I need to confirm what should be the proper acting here. Currently `startup.project` value is being searched among projects from the backend that was used as last. Meaning if user will close Enso on cloud page then only cloud projects can be opened like that.

**Comment by somebody1234** [comment]
yeah... that was how it worked previously, but it should be very easy to change either way

**Comment by JanBeelte** [comment]
Good point, to make the behavior more predictable and better testable one could either add two options (startup.project.cloud, startup.project.local) or one could add a special uri (startup.project=cloud:// startup.project=local:// ) or similar.

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
