### PR TITLE
Consistent Prettier options

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
:warning: :warning: :warning: This PR **MUST NOT** be squashed as it modifies `.git-blame-ignore-revs`.

- Reformat all JS/TS in the codebase to use 2 spaces.
  - This is helpful when diffing files from different modules (e.g. the Project Manager code which is *technically* duplicated between the Electron app and a dev-only GUI shim)
- Use GUI's Prettier config for dashboard's Prettier config

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] ~~Unit tests have been written where possible.~~

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]

**Comment by MrFlashAccount** [comment]
@somebody1234 can we put the whole reformat into a separate commit, add it to .git-blame-ignore-refs (see: https://gist.github.com/kateinoigakukun/b0bc920e587851bfffa98b9e279175f2) and merge it without rebase/squashing? 

<blockquote><div> Gist</div><div><strong><a href="https://gist.github.com/kateinoigakukun/b0bc920e587851bfffa98b9e279175f2">how-to-git-blame-ignore-revs.md</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Review by kazcw — APPROVED** [review]

**Comment by somebody1234** [comment]
i guess this needs approval by cloud and libs as well? @MrFlashAccount @jdunkerley

**Comment by somebody1234** [comment]
will be intentionally leaving with conflicts to make sure it doesn't accidentally get automatically merged in with squashing

**Review by jdunkerley — APPROVED** [review]
Approving libs stuff

**Review by MrFlashAccount — APPROVED** [review]

**Pull request merged**
