### PR TITLE
Smart search

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/782
  - `owner:` to do exact matches against owner username
  - `label:` (already existed)
  - `name:` to do exact matches against asset name (exact match; case insensitive; the glob character `*` matches 0 or more characters)
  - negated searches (`-owner:`, `-label:`, `-:` for negating keywords)
- Related changes that were not explicitly requested:
  - add `no:`, `-no:`, `has:` and `-has:` to filter for assets that lack a specific field. Currently this only works for labels, because most (if not all) other fields cannot be empty.
  - `label:a,b,c` to OR results together. `label:a label:b` ANDs results as usual.
  - shift-click labels to add/remove it to the last search term as an OR
  - clicking labels now cycles them from: absent -> present (positive) -> present (negative)
- Unrelated changes
  - Switches unit tests to use `vitest`

### Important Notes
Some other suggestions have been added in the original issue, but currently intentionally left out to avoid prematurely over-engineering this feature.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] ~~Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.~~
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. If there is a match in file name but the file is in folder we need to show the whole catalog tree
2. For matching empty directory the "This folder is empty" is not working
3. Is it hard for `owner` and `label` to support `*` as well?
4. Add suggestion for `owner`, `label`, `name` and autocomplete on tab. Maybe something like gmail has?
Screenshot 2023-12-20 at 12 21 20

5. `label:a,b,c to OR results together. label:a label:b ANDs results as usual.` for me the intuitive flow is other wat around? but lets leave it for now as it is

**Comment by somebody1234** [comment]
1. good point, this will take a while though as i think it'll need quite a bit of minor refactoring to display things that weren't directly matched (the parent folders)
2. yeah, the "this folder is empty" is a special placeholder value that *currently* doesn't actually have a title, the component itself is responsible for rendering that text. i *could* make it work but idk whether that's intuitive, maybe we could do something else instead, *but* i don't think it's too important of a feature right now. like *maybe* `no:children` would work, but it doesn't really fit in with the rest of the `no:*` which refer to other tags.
3. no! it's just regex replacement so it should be very simple
4. this may be true, i don't really have an opinion - i just copied how GitHub does it. FWIW, if you think it should be changed, it really isn't a big deal to change the order - the only change required would be to change `array.some(subArray => subrray.every())` into `.every(.some())` instead.

but, it's pretty late in the day so i suppose i'll address these tomorrow.

**Comment by somebody1234** [comment]
this PR has scope creeped quite a bit...
... but do note that some things are still considered out of scope for this PR:
- dedicated elements for individual search terms:
  - one issue is that we need to figure out how text input should interact with search terms
  - another issue is that the input will need to be completely refactored. *rendering* would be trivial using the backing data structure, however making sure *all* editing functionality (ctrl+a, ctrl+left, home, end) etc works would probably be *quite* difficult.
- being able to click to toggle *off* a search suggestion:
  - implementation-wise, it's not *trivial* to implement this. i don't think it'd be particularly difficult, but it's still difficult enough to take a step back and consider whether this is a good idea first
  - actually, i think it's potentially counter-intuitive until there is some indication as to which items are currently selected.

**Comment by somebody1234** [comment]
... on second thought i just went ahead and implemented toggling off of suggestions

**Comment by somebody1234** [comment]
@jdunkerley ping for visibility. no rush of course, just figured i'd ping before i forget

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
