### PR TITLE
New sharing menu

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/561
  - New "Invite" modal
  - Change autocomplete multi-select behavior
  - Fix scrolling for autocomplete
  - Scrolling when there are many users with permissions
  - New backend permissions

- :warning: Intentional differences from Figma design:
  - The permission type selector (the secondary modal) is slightly wider. This is because of minor changes to the text - check thread for details.
  - The permission type selector for sharing with new users (the top one, next to the input) is vertically offset 4px more than usual. This is intentional; it means there is roughly the same spacing on either side of the input's border, and also means there is spacing between the "invite" button and the permission type selector
  - Many buttons are faded out (`opacity-50`) when they are not interactable.
- Text changes
  - "Invite" changes to "Share" in blue button
  - "File" changes to "<asset type>" in permission type selector

### Screencast

[screen-recorder-thu-jul-27-2023-02-36-58.webm](https://github.com/enso-org/enso/assets/4046547/75cf413b-015a-491e-b31f-66d8d816b4da)

### Important Notes
Some options don't work because the backend representation for permissions is currently different - in particular, the `admin`, `edit`, and `read` permissions, and the `docs` sub-permission.

:information_source: Currently only works with new backend permissions - i.e. `ENVIRONMENT` must be `'pbuchu'` in `config.ts`.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
permission type selector going offscreen (as seen in screencast) is a known issue, and has just been fixed

**Comment by somebody1234** [comment]
i've just noticed that the appearance of the permission selection modal (view/read/edit etc) is slightly wrong - the current permissions should is in front of the background mask, and the modal is below. i'll probably get around to fixing this later

**Comment by somebody1234** [comment]
fixed positioning but blur is broken now for some reason...

... actually, found + fixed the problem

**Comment by PabloBuchu** [comment]
1. docs / exec are should toggle. cant select both at the same time
2. when I select email to share button text should be `share`
3. when I create project am I the `admin` after reload I am the `owner` (probably related to outdated permission action on backend, we will change it to admin)
4. can't delete the sharing option
5. Can we do a dynamic description? If I share project the `File` word should be `Project` etc

so the permission actions for new sharing (as they should be placed in payload):
view / view_docs / view_exec
read / read_docs / read_exec
edit
admin
own

**Comment by somebody1234** [comment]
1. i'm assuming both should be able to be selected at the same time, otherwise their borders wouldn't be on separate halves of the label. may want to double check with wojciech?
2. will do
3. yes, there is no "admin" permission currently
4. right... i think there's no ui for that currently? for now we can probably just add it as a fifth option, below "own"
5. should be done locally

**Comment by somebody1234** [comment]
i'm also working on adding username search, which might take a while

**Comment by PabloBuchu** [comment]
Sorry i missed that earlier but what happened to username / email multiselect? can we bring it back?
Also I can see usernames from below when rolling down users list
Screenshot 2023-08-02 at 10 43 50

Small improvement can we add toastr "You've invited <username / email> to join Enso!"

**Comment by somebody1234** [comment]
@PabloBuchu 
> add toast "You've invited <username / email> to join Enso!"

i'm assuming:
- this should only apply when inviting, not when sharing - since for sharing you already get immediate visual feedback
- in that case, it will never be a username, right? since when inviting, it needs an email to send the invite to

**Comment by somebody1234** [comment]
there are minor issues with text vertical alignment being different when multi-select is on, vs when it's off
haven't thoroughly tested everything else yet either

**Comment by somebody1234** [comment]
i've added scroll when the users list gets too long.
tested by replacing `usersPermissions.map` with `Array.from({ length: 10 }, () => usersPermissions).flat().map` (repeating the users list 10 times)

**Comment by somebody1234** [comment]
tests:
- :heavy_check_mark: user list is correct when updating permissions
- :heavy_check_mark: adding multiple users works, and stays correct after refresh
- :heavy_check_mark: removing permissions works, and stays correct after refresh
- :heavy_check_mark: inviting user works and shows toast
- :heavy_check_mark: email turns into username when typed in or selected
- :heavy_check_mark: "invite" turns into "share" when the email/name of an existing user is typed in or selected
- :heavy_check_mark: enter submits the form to invite user/add permission
- :heavy_check_mark: dropdown updates with matches
- :heavy_check_mark: dropdown displays name instead of email, if both match the search text
- multi-select:
  - :heavy_check_mark: background blurred so text underneath is not visible
  - :heavy_check_mark: no flickering
  - :heavy_check_mark: editable when 0 or 1 items are selected
  - :heavy_check_mark: dropdown doesn't ever disappear, unless clicking outside of it
- submit button:
  - :heavy_check_mark: disabled if there is an invalid email or nonexistent username
  - :heavy_check_mark: enabled if the manual input matches a username
  - :heavy_check_mark: enabled if the manual input matches an email
  - :heavy_check_mark: disabled if the manual input matches the email or username of a user that already has access

added features:
- :heavy_check_mark: scrolls when there are >10 users

**Comment by PabloBuchu** [comment]
Still can select view/read with both docs and exec

Something wrong with the scroll I think
Screenshot 2023-08-02 at 15 33 42

So multi select is broken? It nows add all users to the payload so I am always sharing the asset with everybody from the list also mind I have multiple users with the same username and selecting 1 highlights them all
 
https://github.com/enso-org/enso/assets/2855109/a5fa6767-ac79-4436-9fa7-c621d7dbdfa0

Can we adjust the permissions action with backend. Here are new values which should be used in payload:
Own
Admin
Edit
Read
Read_docs
Read_exec
View
View_docs
View_exec

**Comment by PabloBuchu** [comment]
also could we sort it (own, admin, edit, read, view) on frontend

Screenshot 2023-08-02 at 15 42 31

**Comment by somebody1234** [comment]
> scroll is broken

will try to repro and fix, should be simple

> add all users to the payload 

yes, i found that too. i've fixed it locally, will push soon

> new values

yeah i was holding off on that because i still think that the design implies that `Read_docs_exec` should be possible (since there are two half borders, meaning it's probably intended for both borders to be present at the same time). but i guess in the backend it's implemented as `docs: true` + `exec: true` internally so it'll be easy to change anyway

> sorting

yeah - but it'd probably be better to just sort it in the backend, especially if it can sort by userid too? but definitely simple enough to do in the frontend for now at least

**Comment by somebody1234** [comment]
oh, didn't see the same username thing. autocomplete should probably be refactored to take different inputs then

**Comment by somebody1234** [comment]
sorting: wip, because the permissions need to stay sorted when changed, which will require a bit of a refactor.
same username: will require a refactor too, not started yet

**Comment by PabloBuchu** [comment]
Small thing but actually may lead to sharing asset with wrong user. Not sure how to best fix that, maybe don't sort on update? It should be refreshed and sorted on adding / removing. How hard would it be?

https://github.com/enso-org/enso/assets/2855109/be7061ee-e705-4746-be50-7ecc36c86868

**Comment by somebody1234** [comment]
yeah good point. it should definitely be doable, i think removing the `.sort` should be all that's needed

**Comment by PabloBuchu** [comment]
When I try to delete myself the request contains `""` empty string in `userSubjects`. Could we also add a check with toastr when someone is removing the only owner or admin from permissions? "<Project|File|Connector> needs to have at least 1 admin or owner"

Screenshot 2023-08-03 at 11 10 26

**Comment by somebody1234** [comment]
re: at least one owner/admin:
- i think it should be at least one owner - it should be easy enough to promote any admin to owner, before removing yourself, anyway

other notes, i probably should double check:
- admin shouldn't be able to set owner permissions (frontend: shouldn't show up in the list, backend: request should fail)
- roles below admin shouldn't be able to edit permissions at all

some of the stuff above should probably be enforced by the backend too (if it isn't already), otherwise someone can just make a manual `fetch` in the browser console

**Comment by somebody1234** [comment]
new minor style change is untested because logins don't seem to be working on `pbuchu` environment.
(it shouldn't result in any visible changes, just need to make sure text still displays properly on the new sharing menu)

**Comment by PabloBuchu** [comment]
| admin shouldn't be able to set owner permissions (frontend: shouldn't show up in the list, backend: request should fail)
| roles below admin shouldn't be able to edit permissions at all

yeah we are checking asset ownership on the endpoint

**Comment by PabloBuchu** [comment]
@somebody1234 can you solve the conflicts? would love to merge this PR today

**Comment by somebody1234** [comment]
@PabloBuchu merge conflicts now fixed

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
