### PR TITLE
Support for creating and editing Data Links

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/734
  - Add modal to create a new Data Link
  - Add the same input to the asset right panel
  - Add entries on context menu and Drive Bar
    - The shortcut is <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>N</kbd>
  - Add (and use) corresponding backend endpoints

### Important Notes
- All UI is currently generated based off of a single-source-of-truth JSON Schema file.
  - JSON Schema was chosen for a few reasons:
    - trivial to parse (it's plain JSON)
    - sufficiently powerful (supports unions (used in the initial schema), objects, and singleton/literal types)
    - but still quite simple (this makes it easier to implement various utilities for, because there are fewer cases to cover)
  - Note that it is definitely possible to change this. The original suggestion was a TypeScript file, which can definitely be done even using just the `typescript` package itself - I just prefer to avoid adding another step in the build process, especially one that depends on the `typescript` package at runtime.
    - Note also that we *do* actually bundle transpilers as part of the visualization loading code in GUI2 - so for now at least, the size of the dependency isn't a primary concern, but rather just the mental overhead of having another dependency for this one specific task.

### Screenshots
The modal for creating a Data Link:
image

A Data Link alongside some secrets:
image

The asset panel for a Data Link:
(loading)
image
(loaded)
image

New context menu entry:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
New datalink modal:

1.  Missing validation for URl 
2. Auth -> AWS Access Key -> Enso Secret what is secret path? also I guess would be good to have a secret selector there (tbd on daily)
3. Format -> Delimited -> KBOOM!
4. Shortcut is not working on mac

**Comment by somebody1234** [comment]
re: URI validation
luckily that should be simple enough -  there is official support for a `uri` string format <https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers>
and [validator](https://www.npmjs.com/package/validator) which we are already using for email validation supports `isURL` which i assume checks for RFC3986.
(edit: it doesn't... i've resorted to using a regex `pattern` instead.)

incidentally, i think some of the extra json schema stuff that's been added as part of this PR will come in handy for doing URI validation in the form itself, because currently the form doesn't actually validate anything other than the input being non-empty.

<blockquote><div><strong><a href="https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers">JSON Schema - string</a></strong></div><div>JSON Schema</div></blockquote>

**Comment by somebody1234** [comment]
1. done.
2. i assume this is on hold for now until the endpoint for listing secrets exists
3. should be done.
4. tentative fix has been added

**Comment by somebody1234** [comment]
note re: 3. - while it currently works, there is currently no way to say that a key should not be present (the `format` key is optional, and therefore ignored when validating. this is incorrect; it needs to properly be able to be omitted, and then validated if it exists). this **MUST** be added before the PR is ready to merge, but the current stuff has taken a while so i'll be putting this PR on hold for a bit

**Comment by PabloBuchu** [comment]
| i assume this is on hold for now until the endpoint for listing secrets exists
@somebody1234 we will use existing `GET /secrets` for that. I will add some permissions validation on backend but the endpoint is there

**Comment by somebody1234** [comment]
ohhh... okay then

**Comment by somebody1234** [comment]
it has to return the path as well, right? so that the dropdown knows what path to insert

**Comment by PabloBuchu** [comment]
- add validation errors messages
- type s3 -> why `Format` can't be greyed out (looks like optional but it is required at the same time). Should looks like in active state but without default option selected
- s3 -> format -> delimited -> delimiter can be blank? if so what is default value?
- s3 -> format -> delimited -> what is header? could we add some tooltips?
- http -> uri no can we add `.startswith('http') here?

**Comment by somebody1234** [comment]
@PabloBuchu `S3` -> `Format` is optional, you might have had another field that failed validation?

anyway, hopefully this will no longer be an issue once i add UI for validation

overall status:
- add validation errors: i have some ideas, but i will implement this after the other changes which should be simpler
- s3 -> format: it is optional
- s3 -> format -> delimited -> delimiter: cannot be blank, now fixed locally.
- s3 -> format -> delimited -> headers: i think this means a header row is present. tooltip added for clarity.
- http -> uri: constraint added

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
