### PR TITLE
Fix dashboard issues

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Fixes [cloud-v2/#404](https://github.com/enso-org/cloud-v2/issues/404)
- Fixes [cloud-v2/#405](https://github.com/enso-org/cloud-v2/issues/405)
- Fixes [cloud-v2/#406](https://github.com/enso-org/cloud-v2/issues/406)
- Fixes [cloud-v2/#408](https://github.com/enso-org/cloud-v2/issues/408)
- Fixes [cloud-v2/#410](https://github.com/enso-org/cloud-v2/issues/410)

### Screenshots/screencasts
404:
image
405:

https://user-images.githubusercontent.com/4046547/235647739-125efb09-b72c-46a1-9065-9f5828310557.mp4

406:

https://user-images.githubusercontent.com/4046547/235649036-7b5c9299-6882-4d63-9848-aa1a10386ff0.mp4

408:
Local backend:
image
Remote backend:
image
410:
note the lack of webgl errors. errors do appear at the end, but that is caused by `drop()` from switching or stopping the currently active project. i don't think it will cause issues during usage as it only happens when the IDE is closing.
https://user-images.githubusercontent.com/4046547/235669442-f76636be-2685-4a6d-b996-df75387df53d.mp4

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
This PR is ready implementation-wise, but it is blocking on another PR.

**Comment by somebody1234** [comment]
typecheck: passing
eslint: passing
prettier: passing

**Comment by somebody1234** [comment]
not sure why the screencasts aren't embedding properly :(

**Comment by somebody1234** [comment]
force-pushed because github doesn't squash commits that were merged in for some reason

**Comment by PabloBuchu** [comment]
@somebody1234 Colorado Covid template is using wrong name when creating a project. Locally and remotly it should be `colorado_covid` now it is `coloradocovid` which is unrecognizable by local project manager

**Comment by somebody1234** [comment]
whoops, the logic was indeed wrong. i've kept the capitalization though, which is copied from the rust names i think. i've tested creating projects and they work and create the correct project locally, but @PabloBuchu you might want to check as well just to be extra sure it's really fixed

**Comment by PabloBuchu** [comment]
QA 🟢

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
