### PR TITLE
Fix copy and paste on local backend

### PR DESCRIPTION
**Pull request by MrFlashAccount**
### Pull Request Description

This PR adds check for localBackend on dragOver event

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [ ] The documentation has been updated, if necessary.
- [ ] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [ ] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [ ] Unit tests have been written where possible.
- [ ] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by somebody1234 — APPROVED** [review]
CR :white_check_mark: 
(minimal changes)

**Comment by PabloBuchu** [comment]
Why when I drag n drop something (or drag out) to the local directory it is automatically sorted? its big annoying tbh can we fix that?

https://github.com/user-attachments/assets/33176290-072c-4802-a61b-a705dd0cbde0

**Comment by MrFlashAccount** [comment]
@somebody1234 is it something with the default sorting?

**Comment by MrFlashAccount** [comment]
@PabloBuchu Found a place where we sort by the modified date. Removed this

**Comment by PabloBuchu** [comment]
@MrFlashAccount it still sorts when you rename a catalog. It works properly now on `develop` when renaming do not change directories order

**Comment by MrFlashAccount** [comment]
@PabloBuchu it's expected behavior. We sort things on each refetch. Folders come first, everything sorted alphabetically,
For example, this is how it works in Gdrive:

https://github.com/user-attachments/assets/cb154749-e3fe-4d67-9940-75ad54b59ef0

**Comment by PabloBuchu** [comment]
@MrFlashAccount not sure what do you call expected behaviour here.


https://github.com/user-attachments/assets/248fb2ed-3963-40d9-9228-1ae1976ab698

https://github.com/user-attachments/assets/da89e558-30f9-4261-adc1-d00b9919853b

Both examples (gdrive and develop) shows that renaming does not triggers sorting. Not sure whats different in your example but probably you have set non default sorting. It does nothing to do with refetch as reload nor refetch does not resort directories

https://github.com/user-attachments/assets/ce05a2e4-7671-40e2-a65c-771c134c6edf

Right now however renaming makes catalogs jumping around which is bit annoying

**Comment by PabloBuchu** [comment]
also click to rename feels really hard to trigger but I guess its not topic of this PR

**Comment by MrFlashAccount** [comment]
In your example you've set a different from the default sorting order in GDrive

**Comment by MrFlashAccount** [comment]
So we have only 2 options here:
1. Keep it as intended
2. Remove alphabetic sorting entirely

**Review by PabloBuchu — APPROVED** [review]

**Pull request merged**
