### PR TITLE
Upgrading to Frgaal 19.0.0 - removing need for sbt bootstrap

### PR DESCRIPTION
**Pull request by JaroslavTulach**
### Pull Request Description

No need for `sbt bootstrap` with Frgaal.

### Checklist

[ci no changelog needed]

### CODE REVIEW

**Review by 4e6 — APPROVED** [review]
Great! Just make sure that `sbt bootstrap` comand is not failing. Because now it only has a definition, and no implementation.

**Comment by JaroslavTulach** [comment]
> Great! Just make sure that `sbt bootstrap` comand is not failing. Because now it only has a definition, and no implementation.

I tried to execute:
```
enso$ sbt --java-home ~/bin/graalvm bootstrap
[info] welcome to sbt 1.7.1 (GraalVM Community Java 11.0.13)
[info] loading settings for project enso-build from plugins.sbt ...
[info] loading settings for project enso from build.sbt ...
[info] resolving key references (55525 settings) ...
[success] Total time: 0 s, completed Sep 29, 2022, 10:53:18 AM
```
and it seems to work.

**Review by hubertp — APPROVED** [review]
Let's hope we don't use `runtime/bootstrap` anywhere:
```
sbt:enso> runtime/bootstrap
[info] Truffle JARs are up to date.
```
and now
```
sbt:enso> runtime/bootstrap
[error] No such setting/task
[error] runtime/bootstrap
[error]                  ^
```

**Review by hubertp — CHANGES_REQUESTED** [review]
Seems to crash on a clean build
```
[warn] Error reading API from class file: org.enso.interpreter.epb.runtime.PolyglotExceptionProxy : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.runtime.PolyglotExceptionProxy (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.exception.AbstractTruffleException (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.exception to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.ContextRewrapNode : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ContextRewrapNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.Node (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.ReadOnlyArray : java.lang.IllegalAccessError: superinterface check failed: class org.enso.interpreter.epb.node.ReadOnlyArray (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.interop.TruffleObject (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.interop to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.JsForeignNode : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ForeignFunctionCallNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.Node (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.CoercePrimitiveNode : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.CoercePrimitiveNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.Node (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.runtime.PolyglotProxy : java.lang.IllegalAccessError: superinterface check failed: class org.enso.interpreter.epb.runtime.PolyglotProxy (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.interop.TruffleObject (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.interop to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.ForeignEvalNode : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ForeignEvalNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.RootNode (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.EpbLanguage : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.EpbLanguage (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.TruffleLanguage (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api to unnamed module @0x5006bd54
[warn] Error reading API from class file: org.enso.interpreter.epb.node.RForeignNode : java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ForeignFunctionCallNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.Node (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[error] ## Exception when compiling 15 sources to /home/hubert/tmp/stash/enso/engine/runtime-language-epb/target/scala-2.13/classes
[error] java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ForeignEvalNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.RootNode (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
[error] java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[error] java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
...
```

and actual failure:
```
[error] (runtime-language-epb / Compile / compileIncremental) java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.node.ForeignEvalNode (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.nodes.RootNode (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x5006bd54
```

**Comment by JaroslavTulach** [comment]
> Seems to crash on a clean build
> 
> ```
> java.lang.IllegalAccessError: superclass access check failed: class org.enso.interpreter.epb.runtime.PolyglotExceptionProxy (in unnamed module @0x5006bd54) cannot access class com.oracle.truffle.api.exception.AbstractTruffleException (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.exception to unnamed module @0x5006bd54
> ```

Yup. `sbt clean runtime/compile` fails. Sorry for premature _proposal_ of changes. I did clean build once, but then multiple builds to fix bugs incrementally. I haven't realized that the incremental invocations are fixing the bootstrap problem.

**Comment by JaroslavTulach** [comment]
Frgaal already [upgraded to 19.0.0](https://github.com/enso-org/enso/pull/3716/files?file-filters%5B%5D=.scala&show-deleted-files=true&show-viewed-files=true#diff-920048e724e99c51a282863cca6d5c9029300a48a594711c753cac20a46436cbL26). `sbt bootstrap` will have to stay for now.

**Pull request closed without merging**
