### PR TITLE
Improve performance of graph changes

### LINKED ISSUE #6471: Performance problems when diconnecting/reconnecting nodes
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When disconnecting the node by clicking on the connection -specially closer to the second node (the one that has the input connected), a significant perf drop can be observed. Connection is glued to the mouse pointer and there are issues with dropping it/reconnecting.

### Expected behaviour

Disconnecting/reconnecting nodes works smoothly.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

Enso_18NaPqDRuz

### Enso Version

nightly 28.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

_No response_

### Hardware you are using

_No response_

### LINKED ISSUE #6674: Errors in the workflow are making IDE sluggish
### Discord username

_No response_

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am working with bigger project and break it at the beginning first IDE is freezing for the time when errors are getting populated. Having many errors is also slowing down IDE when trying to work with it on weaker hardware (editing nodes, zooming, panning are having delays). Breaking first node on Restaurants example available in our templates is already freezing my IDE on M2 MacOS. 

### Expected behaviour

Errors on nodes should not affect IDE performance.

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Enso Version

nightly 12.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

_No response_

### Hardware you are using

_No response_

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

Fixes performance problems observed when creating/resolving errors (#6674):

|before|after|
|---|---|
|vokoscreenNG-2023-06-09_08-49-46.webm|vokoscreenNG-2023-06-09_08-50-54.webm|

This also helps with #6637, although I haven't been able to reproduce the degree of slowness shown there so I can't confirm that this resolves that issue.

### Important Notes

- Disable visualizations until shown. [Faster startup, and all graph changes.]
- 6x faster message deserialization. [Saves 400ms when making a change with many visualizations open.]
- Fast edge recoloring. [Saves 100-150ms when disconnecting an edge in Orders.]
- Add a checked implementation of a `profiler` data structure, used instead of the fast `unsafe` version when `debug-assertions` are enabled.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by kazcw** [comment]
While testing this, I noticed #6999, which turned out to be preexisting.

**Comment by kazcw** [comment]
#7006 is also a preexisting bug.

**Review by wdanilo — APPROVED** [review]
A lot of simplification in the code! And of course, the results are great :)

**Comment by MichaelMauderer** [comment]
QA 🟢 

Looks good to me.

**Pull request merged**
