### PR TITLE
Sort output of `File.list`

### LINKED ISSUE #11669: Sort results of `Data.list` alphabetically
The order of files returned by `Files.list` can be non-deterministic and depend on how the filesystem stores the directory tree internally.

image

As demonstrated in the example above, adding files can actually result in them appearing in unexpected order (e.g. 9 added after, appearing between 1 and 2).

To make sure that the order is more stable 
- [ ] let's add a `sort` by path on `Data.list`.
- [ ] think if we want to add this to `File.list` directly, or do it at `Data.list` level.

### PR DESCRIPTION
**Pull request by GregoryTravis**
Closes #11669.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      [TypeScript](https://github.com/enso-org/enso/blob/develop/docs/style-guide/typescript.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- [x] Unit tests have been written where possible.
- [x] If meaningful changes were made to logic or tests affecting Enso Cloud integration in the libraries, 
      or the Snowflake database integration, a run of the [Extra Tests](https://github.com/enso-org/enso/actions/workflows/extra-nightly-tests.yml) has been scheduled.
  - If applicable, it is suggested to paste a link to a successful run of the Extra Tests.

### CODE REVIEW

**Review by radeusgd — COMMENTED** [review]
Moving `sort` from `Data.list` into `File.list` makes `Data.list` sorted only when listing local directories, but not S3 nor Cloud.

Please, either bring it back onto `Data.list` or ensure that the sort is added to other backends.

My rationale for doing it on `Data.list` was that this was the user facing method and the more internal `(S3_|Enso_|)File.list` was a bit more low level and used in our internals so the overhead of sorting was not needed there. But perhaps it's good to just keep them consistent - so we probably want to sort everywhere.

**Comment by GregoryTravis** [comment]
@radeusgd I have put sort back in `Data.list`. This means in some cases, it will sort twice. These lists are often small, but if you think it's a good idea, I can add a `no_sort` parameter to to `File.list`.

**Comment by radeusgd** [comment]
Hmm, but why do it this way?

This way we are still inconsistent - we sort in `File.list` but don't sort in `Enso_File.list`. I think we should either sort in all backends (and then sort in `Data.list` is no longer needed) or sort in none (and then only sort in `Data.list`). 

I guess sorting in all backends is the way to go.

**Comment by GregoryTravis** [comment]
Sounds good. I've created #11899 for this, since this change needs to go into the release.

**Review by radeusgd — APPROVED** [review]

**Review by jdunkerley — APPROVED** [review]

**Pull request merged**
