### PR TITLE
Home screen

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Closes https://github.com/enso-org/cloud-v2/issues/580
  - Adds home screen

Other changes:
- Typing in the search bar from the home page, switches to the drive page. This is easy to change/remove, of course

### Important Notes
There are minor differences from the design:
- The Enso logo has opacity 0.6 to match the text color, rather than 0.665
- The list of samples is different
- The border-radius on the "create empty project" tile was changed from 18px to 16px, to match every other border-radius (especially the ones on the tiles for the other samples)

Implementation notes:
- The "new project" circled plus icon has a different color to the primary text color as well, but that has been left as-is
- The sample descriptions have a backdrop-blur, but the background image no longer extends underneath it
- There are currently no inset shadows for the home screen, but it will be easy to copy them from the old implementation from the old templates list
- "Read what's new in Enso 3.0 Beta" currently links to https://enso.org/, rather than a blog post (which does not yet exist)
- The new template backgrounds have been replaced with SVGs. The Excel one uses the Excel logo from Wikipedia; the new geospatial analysis one was converted to SVG via auto-tracing.

There are also several placeholders:
- Sample author icon
- Sample author
- Sample open count
- Sample like ount

### Screenshots and screencasts

image

[screen-recorder-tue-aug-08-2023-17-58-55.webm](https://github.com/enso-org/enso/assets/4046547/3b5ad289-9b4c-42d9-85c2-467aca51436d)

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
it seems like there are a few issues related to the project list in that screencast, not sure if i will be able to reliably repro though:
- occasional infinite spinner on local backend
- two projects open at once on local backend

these may or may not be related to specifically creating templates, rather than creating empty projects.

**Comment by somebody1234** [comment]
basic testing:
- :heavy_check_mark: all links in "discover what's new" work
- :heavy_check_mark: sample project buttons work
- :heavy_check_mark: typing into search bar changes page to drive page
- :heavy_check_mark: buttons on drive page still work after refactoring templates section out

not sure if there's anything else that should be tested tbh

**Comment by somebody1234** [comment]
when creating a project from a template on the cloud backend, and then switching to drive view, the spinner appears with 75% progress rather than 5%. not sure if this is important enough to fix, but either way i'll probably be doing other things before coming back to this PR

**Comment by somebody1234** [comment]
merged because github ui said there was a conflict but local merge (with `ort` strategy, as is default) worked without problems

**Comment by indiv0** [comment]
QA failed, but potentially due to issued not introduced in this PR :P

# Scenario 0

```sh
./run gui watch \
    --skip-wasm-opt \
    --wasm-profile=dev \
    --skip-version-check \
    --profiling-level=objective \
    --wasm-log-level=info \
    --wasm-uncollapsed-log-level=info
```

- ✅ GUI at http://localhost:8080 opens
- ✅ Can login
- ✅ Dashboard shows up
- ✅ Nodes in cloud project are visible

image

- ✅ Home screen appears to match design

image

- ✅ "What's new" link works
- ✅ YouTube tutorials link works
- ✅ Discord invite link works
- ✅ Creating a new project from home screen works
- ❌ When clicking "Log in with Google", a notice about "Please fill out this field" on the email field appeared. This shouldn't happen since I'm not logging in with email.
- ❌ If the IDE is trying to open a broken Cloud project, there is no way to leave the IDE without clearing application storage.
    - In my case, I'd misconfigured the `LATEST_IDE_VERSION` in DynamoDB to point at a non-existent version of the WASM (i.e., `2023.2.1-nightly.2023.8.22` when the latest available is `2023.2.1-nightly.2023.8.17`).
    - The IDE tried to auto-open the project and it'd show the loading spinner.
    - Loading would fail since there's no `2023.2.1-nightly.2023.8.22/manifest.json` in the Enso CDN
    - Because there was only the loading spinner, there was no way to back out of the project
    - Reloading the page would auto-open the same project, meaning I couldn't stop the project from the projects list
- ❌ Missing padding on top bar when scrolling down on home screen

image


<blockquote><div><strong><a href="http://localhost:8080/">unfurl | built with Probot</a></strong></div></blockquote>

**Comment by somebody1234** [comment]
>  If the IDE is trying to open a broken Cloud project, there is no way to leave the IDE without clearing application storage.

@indiv0 not sure whether this is particularly easy to fix unfortunately. The dashboard does not control the loading spinner (nor should it?) - I think a more ideal solution would be to open an issue for the GUI team (?) for them to remove the loading spinner on load failure. As for the other issues, I will investigate and fix soon

**Comment by indiv0** [comment]
@PabloBuchu @xvcgreg any idea who would best be able to handle the spinner issue reported above?

**Comment by somebody1234** [comment]
Style issue should (finally) be fixed. Also fixed some other style issues (most should only appear when the window is _very_ narrow though), there was also an issue with template background svgs not appearing

> When clicking "Log in with Google", a notice about "Please fill out this field" on the email field appeared. This shouldn't happen since I'm not logging in with email.

This should only happen when the email field is already focused.
- If it wasn't, then repro steps would be great
- If it was, it's true that it is still an issue - but I don't think it was introduced by this PR, so I'd probably fix it in #7500 instead

**Comment by somebody1234** [comment]
this one had no merge conflicts, just merging to pull in bug fixes

**Review by PabloBuchu — APPROVED** [review]

**Comment by PabloBuchu** [comment]
@somebody1234 we will probably refactor the spinner and opening the project when moving to vue.. lets merge this for now

**Pull request merged**
