### PR TITLE
Reject `@` as binary operator

### PR DESCRIPTION
**Pull request by kazcw**
### Pull Request Description

`@` should not be legal to use as a binary operator. I accepted it in the parser because it occurred in the .enso sources, but it was actually used to create a syntax error to test error recovery.

See: https://www.pivotaltracker.com/story/show/184054024

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed: Enso GUI was tested when built using BOTH
        `./run ide build` and `./run ide watch`.

### CODE REVIEW

**Review by JaroslavTulach — APPROVED** [review]

**Review by hubertp — DISMISSED** [review]
That's gonna break a couple of tests which rely on the old semantics. I can take a look at those since this is in engine.

**Comment by kazcw** [comment]
> That's gonna break a couple of tests which rely on the old semantics. I can take a look at those since this is in engine.

I see. If this will be hard to fix in the engine, I can correct the argument order bug as a quick fix to hold us over until we can stop relying on this behavior--let me know if that would be helpful, @hubertp.

**Comment by JaroslavTulach** [comment]
> That's gonna break a couple of tests which rely on the old semantics. I can take a look at those since this is in engine.

There is one failure in [RuntimeServerTest](https://github.com/enso-org/enso/actions/runs/3831953944/jobs/6521699266#step:10:5783) - and yes, it processes `@`:
```
      """from Standard.Base import all
        |
        |main =
        |    x = Panic.catch_primitive @ .convert_to_dataflow_error
        |    IO.println x
        |    IO.println (x.catch Any .to_text)
        |""".stripMargin.linesIterator.mkString("\n")
```
There are failures in [DataflowErrorsTest](https://github.com/enso-org/enso/actions/runs/3831953944/jobs/6521699266#step:10:5592) and `CompileDiagnosticsTest` - the latter one yields: `Method `@` of Function could not be found.`.

**Comment by hubertp** [comment]
> There are failures in [DataflowErrorsTest](https://github.com/enso-org/enso/actions/runs/3831953944/jobs/6521699266#step:10:5592) and `CompileDiagnosticsTest` - the latter one yields: `Method `@` of Function could not be found.`.

Yes, I'm mostly concerned about those as this was one the reasons I had to introduce my ugly workaround in micro-distribution. I will try to take a look at it as soon as I'm done with some other task.

**Comment by JaroslavTulach** [comment]
[c1dab6d](https://github.com/enso-org/enso/pull/4021/commits/c1dab6d7c46549a3925b9f277b552ffb55520e32) shows it might be enough  to replace `@` by 
```
`
```
to simulate some syntax error in these tests.

**Comment by kazcw** [comment]
Oh, `@` has only ever been used as a binary operator in order to intentionally produce syntax errors?! I implemented the parser assuming all our source files should parse without error. I will make this an error in the `Tree` so we don't need a hack for it in translation.

**Comment by JaroslavTulach** [comment]
> Oh, `@` has only ever been used as a binary operator in order to intentionally produce syntax errors?! 

All the tests I found need a syntax error and then try to verify the error is properly propagated (up to the IDE). I think the tests don't need `@` and are fine with [c1dab6d](https://github.com/enso-org/enso/pull/4021/commits/c1dab6d7c46549a3925b9f277b552ffb55520e32) error. There is a [failure on Linux](https://github.com/enso-org/enso/actions/runs/3941012620/jobs/6742858590), but macosx and windows engine builds are OK. E.g. we may be close to have this working even with the parser changes.

The failing linux tests are:
```
org.enso.languageserver.filemanager.WatcherAdapterSpec
org.enso.languageserver.websocket.json.ReceivesTreeUpdatesHandlerTest
```
very likely unrelated to our changes (there is a recently reported instability in `inotify`). I think we can restart the job few times and then the integration happens.

**Comment by kazcw** [comment]
I added a parser fix so that `@` is rejected when used outside of annotation syntax. I removed the backend tests comparing `@` parses to the old parser--I have frontend tests verifying that it is an error now; we don't need to test that it produces the same error message as the old parser.

**Review by wdanilo — APPROVED** [review]

**Comment by JaroslavTulach** [comment]
- There is still following comment in our code:
- https://github.com/enso-org/enso/blob/4558a07baa936205bb905b6f95981247ee08474d/test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso#L7
- this PR references the same pivotal story
- does that mean the code there can be removed?

**Comment by kazcw** [comment]
> * There is still following comment in our code:
> 
>     * https://github.com/enso-org/enso/blob/4558a07baa936205bb905b6f95981247ee08474d/test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso#L7
> 
>     * this PR references the same pivotal story
> 
>     * does that mean the code there can be removed?

It's not obvious to me how removal of that line would have been dependent on this PR which increases the parser's strictness in a particular error case. It seems `pivotaltracker.com` no longer exists, do we have an archive of our pivotal stories somewhere or are they lost to history? It looks like @hubertp wrote this comment, Hubert do you happen to remember the context here (4 years ago)? Anyway this file under `test/` is not part of the public API, right? So if we can't establish where we left off in '23, I would think we could try deleting this line and see what happens.

**Comment by JaroslavTulach** [comment]
> do we have an archive of our pivotal stories somewhere or are they lost to history?

Some of the pivotals were converted to GitHub issues, but otherwise they are lost in a history.

**Pull request merged**
