### PR TITLE
New top bar

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Closes https://github.com/enso-org/cloud-v2/issues/556
- Page switcher (home <-> drive <-> editor)
- New backend switcher design
- New search bar design
- New user bar design (chat button + user button)

### Screenshots

image

with temporary background to show partially transparent backgrounds:

image

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by somebody1234** [comment]
oh wait, forgot to test opening projects

**Comment by PabloBuchu** [comment]
1. cloud / local seems shifted a bit, not centered
Screenshot 2023-07-26 at 11 44 20

2. Can we add this icons as disabled?
Screenshot 2023-07-26 at 11 48 49

The rest looks good

**Comment by somebody1234** [comment]
@PabloBuchu changes should be made now

**Comment by PabloBuchu** [comment]
1. so the icons added recently (the disabled ones) are shrinking when I narrow the Enso window. The limit value seems to be 900px 
https://github.com/enso-org/cloud-v2/assets/2855109/c41ed484-83f2-49a7-a2d2-1afeb08eda85


2. When switching between cloud / local with open project I am getting weird project not found error. Also switching to local with open project moves me immediately to the workspace
https://github.com/enso-org/cloud-v2/assets/2855109/01b1d935-d3c9-4b88-8f7a-697ff0ab510a

3. I'll remove for now implementing this view on project workspace since we depend on https://github.com/enso-org/enso/issues/7411 to be finished before

**Comment by somebody1234** [comment]
@PabloBuchu both issues should be fixed now

**Comment by PabloBuchu** [comment]
@somebody1234 are we able to add a functionality where if there is an open cloud project and user close / open Enso they should be able to go to the workspace using current open project icon? 

https://github.com/enso-org/enso/assets/2855109/9a86d0b3-d061-4803-9347-e6942e394f3e

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
re: opening the current cloud project via the "open current project" icon - yeah that sounds doable
i think it *could* be implemented in the same PR as the localStorage stuff though https://github.com/enso-org/cloud-v2/issues/571
(where the same functionality will be implemented for local projects)

i'll be investigating bugs for a while so definitely won't get around to implementing this anytime soon

**Comment by PabloBuchu** [comment]
thanks I will update the issue

**Pull request merged**
