### PR TITLE
"Activity log" settings page

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
- Close https://github.com/enso-org/cloud-v2/issues/942
  - Add "Activity log" settings page
  - Show info common between all events
  - Specific event info NOT added yet as the appropriate info is currently lacking
- Add support for multi-select in dropdowns (required for the "Activity log" settings page)
- Animate opening of dropdowns

### Important Notes
None

### Screenshots
image

Date picker:
image

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] ~~The documentation has been updated, if necessary.~~
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] ~~Unit tests have been written where possible.~~
  - [x] ~~If GUI codebase was changed, the GUI was tested when built using `./run ide build`.~~

### CODE REVIEW

**Comment by PabloBuchu** [comment]
1. How do I deselect date? selected end date -> filtered -> want to go back to "No date selected"
2. Can we do sorting on timestamp, type and email?

**Comment by somebody1234** [comment]
1. good catch... i guess the simplest way would be to have an `x` button on the very right of the date display. thoughts? do you have any better suggestions?
2. absolutely, will try to do tomorrow.

**Comment by PabloBuchu** [comment]
@somebody1234 sorry missed your comment. yeah lets add `x` should be simple enough for users

**Review by PabloBuchu — APPROVED** [review]

**Comment by somebody1234** [comment]
(note: sorting is still not in. but i wouldn't mind adding it in a separate PR)

**Pull request merged**
