### PR TITLE
Add range info to `Out_Of_Range` error

### PR DESCRIPTION
**Pull request by GregoryTravis**
Followup from #9462.

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Review by radeusgd — COMMENTED** [review]
The message is ignored in `to_display_text` - but that is the user-facing text where it definitely should be included too.

Also please add a test of `to_display_text` - as I mentioned in some review recently - we used to have regressions in these and if they do not have unit tests, we learn about these only when they occur in the IDE - which may be found rarely if the warning is not one seen every day.

**Comment by GregoryTravis** [comment]
> The message is ignored in `to_display_text` - but that is the user-facing text where it definitely should be included too.
> 
> Also please add a test of `to_display_text` - as I mentioned in some review recently - we used to have regressions in these and if they do not have unit tests, we learn about these only when they occur in the IDE - which may be found rarely if the warning is not one seen every day.

Yes, I forgot to change that one -- done.

**Review by radeusgd — APPROVED** [review]

**Comment by jdunkerley** [comment]
looks good - might be worth having the limit in the message for clarity.

**Review by jdunkerley — APPROVED** [review]

**Comment by GregoryTravis** [comment]
> looks good - might be worth having the limit in the message for clarity.

Added.

**Pull request merged**
