### PR TITLE
Revert typescript CI Lint changes

### PR DESCRIPTION
**Pull request by somebody1234**
### Pull Request Description
Hotfix revert to make Lint CI work again

### Important Notes
None

### Checklist

Please ensure that the following checklist has been satisfied before submitting the PR:

- [x] The documentation has been updated, if necessary.
- [x] Screenshots/screencasts have been attached, if there are any visual changes. For interactive or animated visual changes, a screencast is preferred.
- [x] All code follows the
      [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md),
      [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md),
      and
      [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md)
      style guides. In case you are using a language not listed above, follow the [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guide.
- All code has been tested:
  - [x] Unit tests have been written where possible.
  - [x] If GUI codebase was changed, the GUI was tested when built using `./run ide build`.

### CODE REVIEW

**Comment by somebody1234** [comment]
(proper TypeScript CI lint coming soon)

**Review by wdanilo — APPROVED** [review]

**Comment by somebody1234** [comment]
@mwu-tow could you perhaps review this?

**Comment by somebody1234** [comment]
well actually... the fix is ready so...

**Comment by somebody1234** [comment]
feel free to split this into two PRs, but given that the fix should be ready, it should be faster to fix it as well?

**Comment by somebody1234** [comment]
darn, lint CI broke: https://github.com/enso-org/enso/actions/runs/4916999193/jobs/8781496456?pr=6602

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Properly fix TypeScript CI Lint  · enso-org/enso@afbe58a</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by somebody1234** [comment]
yeah... this is not working :( splitting the PR up

**Comment by somebody1234** [comment]
adding "ready to merge" label as:
- it's a hotfix
- it's a very small change
- it's a revert
so basically, urgent + unlikely to break anything

**Pull request merged**
